### ISSUE TITLE
id:200959906 Export charge - charge non planifiée remontée partiellement

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#174]
Remonter un bug pour nous permettre d\'améliorer l\'application<br />Workload-overview<br /> <br /> **Décrivez le bug**<br />L\'export de la charge sur le projet "LNVG Dosto - Traction" ne remonte pas toute la charge non planifiée. Seule la charge non planifiée de Suivi Fiabilité remonte bien. Il manque la charge non-planifiée des les autres métiers (acoustique, component validation, conception thermique, control/command..)<br /><br /><br /><br />@Alstom-WebFdl/method-tools<br /><br />Détails du PC/Browser:<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0<br />Adresse du PC :10.22.112.171<br />

**Comment by lokkotara** [comment]
15/01/24 : Après vérification, la charge non planifiée correctement remontée dans les exports correspond aux fois où la ressource générique a aussi du planifié.

Il faut modifier la requête pour faire une sous-requête récupérant la charge non planifiée pour chaque idActivité récupéré dans la première partie de la requête. Pour rappel, la charge non planifiée correspond à la charge de la ressource 1 (générique) au "0001-01-01".
