### ISSUE TITLE
id:244473 Création d'un ticket réinitialise la vue de travail en cours (pas de conservation de l'environnement de travail) 

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#179]
**Affichage concerné**<br /> multi-affichages<br /> <br /> **Décrivez le bug**<br /> Je perds le travail non sauvegardé sur la vue en cours lorsque je clique sur la création de ticket<br /> <br /> **A reproduire**<br /> Les étapes permettant de reproduire le comportement indésirable :<br /> 1. Sur l\'affichage \'Gestion des activités\'<br /> 2. Je clique sur \'PrEM\', puis \'BEMU-R&D\'<br /> 3. Je clique à gauche sur l\'activité \'planning eng et validation\'<br /> 4. Je clique sur la valeur de la tâche principale, la modifie puis appuie sur entrée<br />5. La couleur de la case est modifiée, indiquant qu'un changement a eu lieu<br />6. Je clique sur l'icône du menu de navigation, puis support et nouveau ticket<br />7. Si je reviens sur  \'Gestion des activités\' avec le même métier et le même projet, le changement temporaire n'y est plus<br /><br /> **Comportement attendu**<br /> Lorsque l'on revient sur l\'affichage, la modification temporaire devrait toujours être présente<br /> <br /> <br /><br /><br />@Alstom-WebFdl/method-tools<br /><br />Détails du PC/Browser:<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0<br />Adresse du PC :10.22.112.114<br />

**Comment by Daniel-Dupuy** [comment]
L'utilisateur est maintenant prévenu de la perte des données non sauvegardées au changement d'affichage sur tous les affichages dynamiques.
