### ISSUE TITLE
id:244473 Changement du nom de l'activité sous la vue Gestion des activités impossible

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#220]
<br /> **Affichage concerné**<br />Gestion des activités / Vue Liste<br /> <br /> **Décrivez le bug**<br />Pas possible de changer le nom d'une activité<br /> <br /> **A reproduire**<br /> Les étapes permettant de reproduire le comportement indésirable :<br /> 1. Gestion des activités<br /> 2. Choix Suivi de fiabilité, FDL Make Battery T18<br /> 3. Vue liste <br /> 4. JE clique sur le bouton éditeur à côté du nom de l’activité pour la modifier<br />5. J'entre un nouveau Nom <br />6. Clic sur "Valider les changements"<br />7. L'ancien nom réapparait <br /><br /> **Comportement attendu**<br />Possibilité de changer le nom d'une activité<br /> <br /> **Informations complémentaires**<br />J'avais commencer ce test avec une FDL TrSE qui avait le même comportement mais pour laquelle il y avait peut etre déjà du spent <br />Pour éliminer raison possible de la non modification sur présence spent , j'ai choisi cette FDL où il n'y a pas de spent<br /><br />**Liste des pièces jointes:**<br /><a href="http://webfdl.tnext.loc/api/public/Capture-174229.JPG" target="_blank" >http://webfdl.tnext.loc/api/public/Capture-174229.JPG</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Détails du serveur**<br />Version DB: 4.28.3; Version Soft: v1.0.9.-Beta; Version Back: v1.0.8-Beta<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0<br />Adresse du PC :10.243.98.3<br />

**Comment by lokkotara** [comment]
Pour que le changement de nom soit pris en compte avant d'appuyer sur le bouton de validation des changements, il faut appuyer sur la touche entrée ou cliquer sur un autre endroit de l'affichage pour que le champ éditable redevienne un simple texte.
Voici les étapes sous forme de capture d'écran :

## je clique sur l'icône pour éditer :

![Image](https://github.com/Alstom-WebFdl/ticket-service/assets/9353050/0a3a9f71-77ff-45bc-9c40-036eea40162d)

## je rentre le nouveau nom :

![Image](https://github.com/Alstom-WebFdl/ticket-service/assets/9353050/bfd27d26-70f0-4e9b-910b-cb6b98b57e93)

## j'appuie sur entrée ou je clique en dehors du champ (il passe en jaune) :

![Image](https://github.com/Alstom-WebFdl/ticket-service/assets/9353050/ed80c97d-4754-4a86-bfca-273967e013c9)

## je clique sur "valider les changements" (il passe en bleu) :

![Image](https://github.com/Alstom-WebFdl/ticket-service/assets/9353050/680bf7c3-980f-4661-a276-1a157624250e)

Cordialement,
