### ISSUE TITLE
id:244473 Bug dans gestion ticketing : Pas de confirmation création et possibilité duplication  

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#225]
<br /> **Affichage concerné**<br />Création du'un ticket de support <br /> <br /> **Décrivez le bug**<br />Renseignement de la description d'un ticket <br /> <br /> **A reproduire**<br /> Les étapes permettant de reproduire le comportement indésirable :<br /> 1. Renseignement de la description d'un ticket <br /> 2. Je clique sur 'Créer le ticket'<br /> 3. Pas d'affichage comme d'habitude de la fenêtre pop up donnant le numéro du ticket<br /> 4. Il est possible de recliquer sur Creer le ticket et de reprendre un numéro de ticket <br /><br /> **Comportement attendu**<br />Fenetre de confirmation du log du ticket <br />Pas de possibilité de réenregistrer exactement le même tiket<br /> <br /> **Informations complémentaires**<br /> Comportement non systématique <br /><br />**Liste des pièces jointes:**<br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Détails du serveur**<br />Version DB: 4.28.3; Version Soft: v1.0.9.-Beta; Version Back: v1.0.8-Beta<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0<br />Adresse du PC :10.243.98.3<br />

**Comment by lokkotara** [comment]
C'est un bug que l'on a rencontré au début de la mise en place du service de ticketing. L'erreur n'est plus reproduite depuis donc je clos ce ticket.

N'hésitez pas à ré-ouvrir un nouveau ticket si ce bug venait à revenir.

Amicalement,
