### ISSUE TITLE
id:244473 Fenetre non visible totalement sur tous les formats d'écran

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#228]
<br /> **Affichage concerné**<br />Charge / Répartition charge/ Filtre <br /><br /> **Décrivez le bug**<br />A l'ouverture de la fenetre filtre sous un grand écran , le bas de la fenetre cotenant les boutons de confirmation sont tronqués<br />Si je repasse sous un écran plus petit ils ré-apparaissent normalement<br /> <br /> **A reproduire**<br /> Les étapes permettant de reproduire le comportement indésirable :<br /> 1. Sur l'affichage 'Charge / Répartition charge/filtre'<br /> 2. Selection Suivi de Fiabilité/ Fiche de lot Extra / Brighline<br /> 3. Affichage tronquée de la fenetre <br /><br /> <br /> **Informations complémentaires**<br /> Affichage 3440*1440<br /><br />**Liste des pièces jointes:**<br /><a href="http://webfdl.tnext.loc/api/public/Capture-657156.JPG" target="_blank" >http://webfdl.tnext.loc/api/public/Capture-657156.JPG</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Détails du serveur**<br />Version DB: 4.28.3; Version Soft: v1.0.9.-Beta; Version Back: v1.0.8-Beta<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0<br />Adresse du PC :10.243.98.3<br />

**Comment by lokkotara** [comment]
Ce bug d'affichage vient de l'utilisation de CSS Flex pour gérer l'affichage de la modale.

Une solution pourrait être d'utiliser plutôt CSS Grid pour définir une ligne en bas de la modale qui conserverait l'espace pour les boutons.
