### ISSUE TITLE
id:244473 Affichage répartition charge vide sur FDL Extra

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#229]
<br /> **Affichage concerné**<br />Charge/Répartition Charge sur une FDL Extra<br /> <br /> **Décrivez le bug**<br />Besoin de planifier du générique sur une fiche de lot Extra, l'affichage répartition charge est vide bien que la FDL soit chargé (vérifié via la vue Gestion des activités)<br /><br /> <br /> **A reproduire**<br /> Les étapes permettant de reproduire le comportement indésirable :<br /> 1. Sur l'affichage 'Charge/Répartition Charge '<br /> 2. Selection Suivi de Fiabilité / FdL Extra Bulgaria<br /> 3. Aucune charge à répartir le tableau est vide<br /> 4. Controle sur l'affichage Gestion des activités => il y a bien du budget remonté sur un GAP<br /><br /><br />**Liste des pièces jointes:**<br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Détails du serveur**<br />Version DB: 4.28.3; Version Soft: v1.0.9.-Beta; Version Back: v1.0.8-Beta<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0<br />Adresse du PC :10.243.98.2<br />

**Comment by lokkotara** [comment]
La requête a été modifiée. A présent, elle récupère la ressource générique à partir du moment où il y a du non planifié. Dans cet exemple, on a donc bien maintenant une ligne générique sur le projet concernée. On peut donc planifier de la charge dessus


![Image](https://github.com/Alstom-WebFdl/ticket-service/assets/9353050/8f9426c8-0fe6-42f3-8db6-356acb7cfb64)

Les changements sont visibles à partir de la v.1.0.11-Beta
