### ISSUE TITLE
id:159224 liste projet

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#230]
<br /> **Affichage concerné**<br />affectation ressource<br /> <br /> **Décrivez le bug**<br />Page de sélection d'un métier :OK<br />Page de selection du projet => pas de liste, impossible de sélectionner un projet et donc d'aller plus loin<br /><br /><br /> **A reproduire**<br /> Les étapes permettant de reproduire le comportement indésirable :<br /> 1. Sur l'affichage '...'<br /> 2. Je clique sur '....'<br /> 3. Je descend le tableau '....'<br /> 4. L'erreur se reproduit<br /><br /> **Comportement attendu**<br /> Une description précise et concise du comportement attendu<br /> <br /> **Informations complémentaires**<br /> Ajoute tout autre information qui permet une meilleure compréhension<br /><br />**Liste des pièces jointes:**<br /><a href="http://webfdl.tnext.loc/api/public/Capture%20d%E2%80%99%C3%A9cran%202024-01-02%20114242-851633.jpg" target="_blank" >http://webfdl.tnext.loc/api/public/Capture%20d%E2%80%99%C3%A9cran%202024-01-02%20114242-851633.jpg</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Détails du serveur**<br />Version DB: 4.28.3; Version Soft: v1.0.10-Beta; Version Back: v1.0.9-Beta<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:101.0) Gecko/20100101 Firefox/101.0<br />Adresse du PC :10.24.100.106<br />

**Comment by lokkotara** [comment]
Bonjour, 

Cela vient du fait de ne pas avoir autoriser la fonction pour récupérer les projets sur cet affichage. Ce bug a été réglé localement et sera poussé à la prochaine mise à jour du serveur.

Cordialement,
