### ISSUE TITLE
id:20167 Les ressources sans capa apparaissent lors d'un filtre par métier

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#238]
<br /> **Affichage concerné**<br /> Tous les affichages où l'on retrouve les 3 filtres (métier, projet, ressource)<br /> <br /> **Décrivez le bug**<br /> Certaines ressources n'ayant pas de capa sur un métier apparaissent quand même dans la liste<br /> <br /> **A reproduire**<br /> Les étapes permettant de reproduire le comportement indésirable :<br /> 1. Sur l'affichage 'tableau de bord de la charge'<br /> 2. Je clique sur 'Rechercher par filtre'<br /> 3. Je clique sur le bouton 'Métier' et je choisis 'System validation traction'<br /> 4. Je clique ensuite sur le bouton 'Ressource'<br /> 5. Le nom de DROUEN Laurent apparaît alors que sa capa est à 0 sur ce métier depuis Mars 2018<br /><br /> **Comportement attendu**<br /> La liste affichée ne devrait contenir que les noms des ressources ayant une capa supérieure à 0 sur le métier correspondant<br /> <br /> **Informations complémentaires**<br /> Dans la capture d'écran , il y a aussi laurent Drouen, Lionel Casajus, Didier Colin, Alexandre Duvignau. Cette liste n'est pas exhaustive.<br /><br />**Liste des pièces jointes:**<br />![Image](https://github.com/Alstom-WebFdl/ticket-service/assets/9353050/2787654f-c381-4a10-ba7d-d737779ab81e)<br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Détails du serveur**<br />Version DB: 4.28.3; Version Soft: v1.0.6-Beta-1-g508b989; Version Back: v1.0.5-Beta<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/118.0<br />Adresse du PC :::1<br />

**Comment by lokkotara** [comment]
Bonjour,

Il n'y a pas de solution simple pour l'intégrer à la V1.

N'étant pas un point bloquant, il ne sera traité que lors d'une version ultérieure.

Cordialement,

**Comment by lokkotara** [comment]
En lien avec le ticket #331 . Ne peut être clôturer sans traiter les deux

**Comment by lokkotara** [comment]
La re-factorisation de la requête permettant de récupérer les ressources par rapport à leur capacité a permis de résoudre ce bug ainsi que celui de l'issue #331. Je clos donc ce ticket.
