### ISSUE TITLE
id:244473 Bug à l'enregistrement planification activité dans répartition charge 

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#240]
<br /> **Affichage concerné**<br /> Réparttion charge<br /> <br /> **Décrivez le bug**<br /> Connexion en mode manager<br />Selection répartition charge, métier RAMS, FdL DSB Traction<br />14,8 H non planifié dans ligne responsable métier<br />Affectation 14,8H à JS Benoit en Mai 24 => la colonne Non planifié passe de 14,8H à 0<br />Valider les changements => la colonne non planifié repasse à 14,8H et les 14,8H de mai 24 pour JS Benoit reste <br /><br /><br /> **Comportement attendu**<br />Après l'affectation de toute la charge non planifiée, la validation des changmeents ne doit pas changer de valeur<br /> <br /><br /><br />**Liste des pièces jointes:**<br /><a href="http://webfdl.tnext.loc/api/public/Capture-951365.JPG" target="_blank" >http://webfdl.tnext.loc/api/public/Capture-951365.JPG</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Détails du serveur**<br />Version DB: 4.28.3; Version Soft: v1.0.10-Beta; Version Back: v1.0.9-Beta<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0<br />Adresse du PC :10.243.98.3<br />

**Comment by lokkotara** [comment]
Une erreur faisait échouer la requête permettant de créer les heures de budget lors de la création d'une nouvelle activité. Cela a été modifié et est effectif à partir de la V1.0.11-Beta.
Cordialement,
