### ISSUE TITLE
id:244473 Ajout d'une activité => charge déclarée non sauvegardé

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#241]
<br /> **Affichage concerné**<br />Gestion<br /> <br /> **Décrivez le bug**<br />Nouvelle activité déclarée avec une charge associée qui passe à 0 après Validation des changements<br /> <br /> **A reproduire**<br /> Les étapes permettant de reproduire le comportement indésirable :<br /> Activité <br />Gestion (FDL Mainweser Armoire, 1 activité IGR SRIL risque chite sur GAP Principal 51,8H)<br />Vue matriciel <br />Click sur "+" à gauche pour ajout activité <br />Saisie Nom activité ("Activité FEI"), jalon ("FEI") , OTP ("Fake 032"), option ("Principal")<br />Clic sur Créer<br />A droite dans détail activité : budget changé de 0 à 10H<br />Valider les changements , après commentaires les 10H disparaissent …<br />Réapparition d'une activité à 0H précédemment supprimé pour un premier test non concluant <br /><br /><br /> **Comportement attendu**<br />Budget de la nouvelle activité conservé après validation des changements<br /> <br /> **Informations complémentaires**<br /> Ajoute tout autre information qui permet une meilleure compréhension<br /><br />**Liste des pièces jointes:**<br /><a href="http://webfdl.tnext.loc/api/public/Capture-631489.JPG" target="_blank" >http://webfdl.tnext.loc/api/public/Capture-631489.JPG</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Détails du serveur**<br />Version DB: 4.28.3; Version Soft: v1.0.10-Beta; Version Back: v1.0.9-Beta<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0<br />Adresse du PC :10.243.98.2<br />

**Comment by lokkotara** [comment]
Une erreur faisait échouer la requête permettant de créer les heures de budget lors de la création d'une nouvelle activité. Cela a été modifié et est effectif à partir de la V1.0.11-Beta. 
Cordialement,
