### ISSUE TITLE
id:244473 Non prise en compte nouvelle déclaration d'OTP

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#242]
<br /> **Affichage concerné**<br />Activité / Affectation des OTP<br /> <br /> **Décrivez le bug**<br />Décalration de nouvel OTP, à la validation des changements reset de la nouvel décalration, retour à l'état initial<br /> <br /> **A reproduire**<br /> Les étapes permettant de reproduire le comportement indésirable :<br /> Activité <br />Affactation de sOTP<br />Test sur plusieurs FDL (MAinweser Armoire- RAMS, DSB Armoire , RAMS - DSB Armoire-FEA)<br />Selection d'un nouvel OTP valide<br />En fonction des configurations, affichage des heures qui peuvent être transférées sur nouvel OTP en violet => ok<br />Click sur Valider les changements, retour à l'état intial avec les OTP FAKE <br /><br /> **Comportement attendu**<br />Enregistrer le nouvel OTP<br /> <br /> <br /><br />**Liste des pièces jointes:**<br /><a href="http://webfdl.tnext.loc/api/public/Capture-454461.JPG" target="_blank" >http://webfdl.tnext.loc/api/public/Capture-454461.JPG</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Détails du serveur**<br />Version DB: 4.28.3; Version Soft: v1.0.10-Beta; Version Back: v1.0.9-Beta<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0<br />Adresse du PC :10.243.98.2<br />

**Comment by lokkotara** [comment]
Ce ticket relève d'une ancienne procédure pour gérer le changement d'OTP sur une activité. 
Actuellement, nous sommes en train de refondre complément ce process. Dans cette nouvelle approche, il n'y aura plus de création d'activité et le process est facilité :
- Lors de la validation du  nouvel OTP, on crée une nouvelle entrée dans la table activitywbshistory
- On met à jour l'activité concerné en modifiant l'id de activitywbshistory sur la table activity avec l'id nouvellement créé.

Je laisse donc ouvert ce ticket tant que l'on ne s'est pas assuré que le nouveau process répond correctement au besoin .

Cordialement,

**Comment by lokkotara** [comment]
Finalement, le process a été encore simplifié et dorénavant, toutes les changements d'OTP  sur une activité sont pris en compte de la même façon. 

Il n'y a plus d'erreur ou d'effets non désirés. Je ferme donc ce ticket. 

Cordialement,
