### ISSUE TITLE
id:20167  "Aperçu de la charge"/ Capacité erronée

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#243]
<br /> **Affichage concerné**<br />Rôle manager/ Remarque 11 / Vue "Aperçu de la charge"<br /> <br /> **Décrivez le bug**<br />La capacité affichée dans l'outil n'est pas la même que celle dans l'outil excel actuel. <br /> <br /> **A reproduire**<br /> Voir le document joint<br /><br /> **Comportement attendu**<br />Affichage de la capa complète incluant les ST<br /> <br /> **Informations complémentaires**<br /> Ajoute tout autre information qui permet une meilleure compréhension<br /><br />**Liste des pièces jointes:**<br /><a href="http://webfdl.tnext.loc/api/public/WEB_FDL_%20remarque_11-695706.JPG" target="_blank" >http://webfdl.tnext.loc/api/public/WEB_FDL_%20remarque_11-695706.JPG</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Détails du serveur**<br />Version DB: 4.28.3; Version Soft: v1.0.10-Beta; Version Back: v1.0.9-Beta<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0<br />Adresse du PC :10.22.112.27<br />

**Comment by Daniel-Dupuy** [comment]
Un rapport semble exister entre le métier POH et les capa des ressources.
Certaines ressources n'ont plus que de la capa pour le métier  POH.

Dans l'exemple, il manque la capa des ressources ci-dessous dans le métier "System Validation Traction" ce qui fausse la courbe de capa :
BONNASSIES Davy
FORTASSIN Pierre
HILARIO Georges
LACASSAGNE  Jérôme
MAGHAMEZ Alfred
MANSOUR Zakaria

**Comment by lokkotara** [comment]
Le sous métier POH n'existant plus, le souci a été réglé.
