### ISSUE TITLE
id:200959906 Impossible de se connecter à l'appli avec Edge

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#244]
<br /> **Affichage concerné**<br />Page de connexion<br /> <br /> **Décrivez le bug**<br />Lorsque je lance l'appli sur Edge via l'adresse "webfdl.tnext.loc", je reçois une page blanche.<br /><br /> <br /> **Informations complémentaires**<br />L'inspecteur remonte de erreurs (cf. PJ)<br /><br />**Liste des pièces jointes:**<br /><a href="http://webfdl.tnext.loc/api/public/Bug%20connexion%20sur%20Edge-528863.JPG" target="_blank" >http://webfdl.tnext.loc/api/public/Bug%20connexion%20sur%20Edge-528863.JPG</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Détails du serveur**<br />Version DB: 4.28.3; Version Soft: v1.0.10-Beta; Version Back: v1.0.9-Beta<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/117.0<br />Adresse du PC :10.22.112.171<br />

**Comment by lokkotara** [comment]
Voici un lien qui, je pense, aborde bien la problématique de cette issue : 
[lien StackOverflow](https://stackoverflow.com/questions/66534759/cors-error-on-request-to-localhost-dev-server-from-remote-site)

Le problème ne devrait plus se présenter lorsque nous aurons obtenu le certificat pour l'appli web.

Je classe donc ce ticket en "step 1 terminé", pour vérifier une fois que nous aurons obtenu le certificat.

**Comment by lokkotara** [comment]
Depuis le passage en https, ce souci n'est pas réapparu. Je clos donc le ticket
