### ISSUE TITLE
id:159224 préférences connexion manager

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#246]
lors d'une connexion manager, l'appli nous demande 1 métier et 1 projet. <br />je suggère d'aller plutot à une vue qui ne nécessaite pas ces choix .<br />Dans mon cas l'idéal serait de pourvoir aller directement voir la charge de tout TD et tout projet<br /><br /><br /><br />**Liste des pièces jointes:**<br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Valentin TACHET vtachet 159224 Manager<br /> **Détails du serveur**<br />Version DB: 4.28.3; Version Soft: v1.0.11-Beta; Version Back: v1.0.10-Beta<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:101.0) Gecko/20100101 Firefox/101.0<br />Adresse du PC :10.24.100.106<br />

**Comment by Daniel-Dupuy** [comment]
Ce n'est pas un bug mais un choix de vue à la connexion qui n'est finalement pas pertinent.

La vue à la connexion a été modifiée temporairement sur la version v1.0.11-Beta
Elle sera définitivement modifiée à partir de la version v1.0.12-Beta
