### ISSUE TITLE
id:200959906 Recherche par filtre : lors d'un choix d'un métier la liste des ressources proposée est incomplète

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#248]
<br /> **Affichage concerné**<br />Tous les affichages avec Recherche par filtre<br /> <br /> **Décrivez le bug**<br />La liste des ressources est incomplète<br /> <br /> **A reproduire**<br />Filtre PrEM<br />Seuls 5 noms remontent<br /><br /> **Comportement attendu**<br />Toutes les ressources PrEM actives doivent remonter<br /><br />**Liste des pièces jointes:**<br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Daniel DUPUY e_ddupuy 200959906 Admin<br /> **Détails du serveur**<br />Version DB: 4.28.3; Version Soft: v1.0.11-Beta; Version Back: v1.0.10-Beta<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0<br />Adresse du PC :10.24.100.79<br />

**Comment by lokkotara** [comment]
Ce bug était causé par un bug avec le métier POH qui ne retenait que la capa POH et plus les autres. Cela a été corrigé et ce bug ne se reproduit plus à partir de la v1.0.13-Beta
