### ISSUE TITLE
id:206314 Masquer les pages non autorisées

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#260]
<br /> **Affichage concerné**<br />Tous<br /> <br /> **Décrivez la demande d'évolution**<br />Je n'ai pas accès au Tableau de Bord (Vous n'êtes pas autorisé à voir cette page !!!) pourtant je le vois dans le menu déroulant.<br />On pourrait masquer les pages bloquées dans le menu, pour alleger la navigation<br />**Liste des pièces jointes:**<br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Type de demande d'évolution**<br />Type : ajout<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Fabien GOY fgoy 206314 User<br /> **Détails du serveur**<br />Version DB: 4.34.1; Version Soft: v1.0.12-Beta; Version Back: v1.0.11-Beta<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36<br />Adresse du PC :10.22.108.171<br />

**Comment by lokkotara** [comment]
Cela a été mis en place et est disponible à partir de la v1.0.0. Cordialement,
