### ISSUE TITLE
id:206314 Pouvoir masquer la capacité

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#262]
<br /> **Affichage concerné**<br />Répartition de charge<br /> <br /> **Décrivez la demande d'évolution**<br />En filtrant par projet (par ex MP14) il y a très peu de charge, et du coup le graph est écrasé par une capacité très haute. Il faudrait pouvoir masquer la capacité, en choisissant "Aucun" dans "Type de capacité"<br /><br />**Liste des pièces jointes:**<br /><a href="http://webfdl.tnext.loc/api/public/Capture%20d%E2%80%99%C3%A9cran%202024-02-14%20145403-417444.png" target="_blank" >http://webfdl.tnext.loc/api/public/Capture%20d%E2%80%99%C3%A9cran%202024-02-14%20145403-417444.png</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Type de demande d'évolution**<br />Type : ajout<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Fabien GOY fgoy 206314 User<br /> **Détails du serveur**<br />Version DB: 4.38.3; Version Soft: v1.0.12-Beta; Version Back: v1.0.11-Beta<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36<br />Adresse du PC :10.243.98.3<br />

**Comment by lokkotara** [comment]
Le fait de masquer la capa lorsque celle-ci n'est pas pertinente (un filtre projet par exemple) était déjà envisagée par l'équipe de dev sans solution facile à mettre en place. Ce ticket proposant une solution simple et efficace, elle a été implémentée et sera disponible à partir de la v1.0.13-Beta.

Cordialement,
