### ISSUE TITLE
id:244473 Selection charge dans passé pour ressource générique ou interne différentes et affichages non cohérents

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#265]
<br /> **Affichage concerné**<br />Répartition de la charge Projet NT77 ESS / RAMS<br /> <br /> **Décrivez le bug**<br />Clic sur 7,4H de janvier 24 pour Eric Aboujdid => aucune ouverture de fenêtre pour corriger le forecast dans passé (capture 1) <br />Clic sur autres lignes contenant du générique : affichage d'une modale avec toutes les lignes de génériques mais en arrière plan la fenêtre principale a un affichage incorrect pour les fonds violets (capture 2&3 ) <br /> <br /><br /> **Comportement attendu**<br />Pouvoir corriger un forecast dans passé d'une ressource déclaré<br />Pour la correction sur une ressource générique qui mène à l'ouverture de modale:  Avoir un visuel cohérent entre la modale et les cellules de la fenêtre principale en fond violet <br /><br />**Liste des pièces jointes:**<br /><a href="http://webfdl.tnext.loc/api/public/Capture2-265000.JPG" target="_blank" >http://webfdl.tnext.loc/api/public/Capture2-265000.JPG</a><br /><a href="http://webfdl.tnext.loc/api/public/Capture1-678232.JPG" target="_blank" >http://webfdl.tnext.loc/api/public/Capture1-678232.JPG</a><br /><a href="http://webfdl.tnext.loc/api/public/Capture3-272241.JPG" target="_blank" >http://webfdl.tnext.loc/api/public/Capture3-272241.JPG</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : non<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 2<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Johana VALLY jvally 244473 User<br /> **Détails du serveur**<br />Version DB: 4.38.3; Version Soft: v1.0.12-Beta; Version Back: v1.0.11-Beta<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0<br />Adresse du PC :10.22.112.114<br />

**Comment by lokkotara** [comment]
Ce comportement était dû à une ancienne version de l'application. Ne se reproduit plus à partir de la v1.0.13. 
Je ferme donc ce ticket.

Cordialement,
