### ISSUE TITLE
id:244473 Erreur dans gestion de la répartition des actuals 

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#266]
<br /> **Affichage concerné**<br />Répartition des actuals<br /> <br /> **Décrivez le bug**<br />La saisie des dépenses sur la partie droite de la fenêtre est sommé uniquement sur la première ligne sur la partie gauche de la fenêtre<br /> <br /> **A reproduire**<br /> Les étapes permettant de reproduire le comportement indésirable :<br />Selection MArc Valmont / RAMS<br />Affichage Répartir les actuals <br />Saisie spent premier projet => ok<br />Saisie spent 2 eme projet => la somme des 2 projets est affectée sur le premier projet à gauche<br /> Cf Capture <br />**Liste des pièces jointes:**<br /><a href="http://webfdl.tnext.loc/api/public/Capture-467840.JPG" target="_blank" >http://webfdl.tnext.loc/api/public/Capture-467840.JPG</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : non<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 2<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Johana VALLY jvally 244473 User<br /> **Détails du serveur**<br />Version DB: 4.38.3; Version Soft: v1.0.12-Beta; Version Back: v1.0.11-Beta<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0<br />Adresse du PC :10.22.112.114<br />

**Comment by lokkotara** [comment]
Pour répartir la charge dépensée sur le deuxième actual, il faut d'abord le sélectionner en cliquant dessus (le cadre jaune doit se positionner autour). 

La capture d'écran montre ici la répartition d'un actual sur deux activités et non une activité sur chaque actual.

Cordialement,
