### ISSUE TITLE
id:244473 Répartition actuals : pas de svg d'une charge saisie 

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#267]
<br /> **Affichage concerné**<br />Répartition actuals <br /><br /> **Décrivez le bug**<br />Saise d'un spent non sauvegardé<br /> <br /> **A reproduire**<br /> Les étapes permettant de reproduire le comportement indésirable :<br />- Selection Eric Aboujdid / RAMS<br />- Clic sur répartir les actuals<br />- Saisie de tous les actuals pour lesquels une seule ligne s'affiche sur la partie droite<br />- Sur la ligne NT77 ESS pas de proposition de lien vers une FDL , clic sur "Plus"<br />- Dans l'affichage à droite apparait une ligne NT77 ESS avec l'OTP correct (première question : pourquoi n'y a t'il pas eu association directement proposé?)<br />- Saisie du pointage, la ligne à gauche apparait avec une coche verte (capture 1)<br />- Valider les changements<br />- Réouverture des actuals d'Eric , la saisie du pointage est toujours à 0 (capture 2)<br /><br /><br /> <br /><br /><br />**Liste des pièces jointes:**<br /><a href="http://webfdl.tnext.loc/api/public/Capture1-452088.JPG" target="_blank" >http://webfdl.tnext.loc/api/public/Capture1-452088.JPG</a><br /><a href="http://webfdl.tnext.loc/api/public/Capture2-964057.JPG" target="_blank" >http://webfdl.tnext.loc/api/public/Capture2-964057.JPG</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : non<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 2<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Johana VALLY jvally 244473 User<br /> **Détails du serveur**<br />Version DB: 4.38.3; Version Soft: v1.0.12-Beta; Version Back: v1.0.11-Beta<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0<br />Adresse du PC :10.22.112.114<br />

**Comment by lokkotara** [comment]
Concernant l'OTP non proposé en association directe, on peut voir sur la capture d'écran qu'il n'est pas identique puisqu'il diffère d'une lettre. 
Pour le reste du dysfonctionnement, il s'agissait d'une ancienne version serveur. Ce bug ne se reproduit plus à partir de la v1.0.13.

Je ferme le ticket.

Cordialement,
