### ISSUE TITLE
id:244473 Fonction équivalente à Tableau de bord PREV.xls 

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#268]
<br />Demande non prioritaire <br /><br /> Objectif : Vérifier que les offres prévisionnelles sont correctement planifiées<br />Avoir la même fonctionnalité que le fichier Tableau de bord PREV.xls actuel<br /><br />Besoin:<br />Sous menu une action Tableau de bord prev<br />Sélection d'un métier<br />Sélection automatique de tous les projets Extra, Previsionnel, Hors demand plan<br />Affichage de la charge planifié sur ces fiche de lot avec en première colonne la charge non planifiée (ce qui correspond à l'affichage que l'on obtient avec l'extract excel)<br /><br />**Liste des pièces jointes:**<br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Type de demande d'évolution**<br />Type : ajout<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Johana VALLY jvally 244473 User<br /> **Détails du serveur**<br />Version DB: 4.38.3; Version Soft: v1.0.12-Beta; Version Back: v1.0.11-Beta<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0<br />Adresse du PC :10.22.112.114<br />

**Comment by lokkotara** [comment]
Cette demande est remplie par l'affichage "Gestion des projets". Je clos donc le ticket. Cordialement,
