### ISSUE TITLE
id:244473 Problème de mise à jour de la charge global après modification sur un Projet

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#269]
<br /> **Affichage concerné**<br />Apercu charge<br /><br /> **Décrivez le bug**<br />Suite à une mise à jour sur un projet de la charge, la mise à jour n'est pas effective dans l'apercu de la charge globale<br /> <br /> **A reproduire**<br /> Les étapes permettant de reproduire le comportement indésirable :<br />-  Apercu charge RAMS/ Eric Aboujdid (Capture 1) => surcharge en Avril 300H (dont 148H sur IPCEI Make Bzttery)<br />- Répartition charge / RAMS / Eric Aboujdid / MAke IPCEI Batterie => Charge de 148H en Avril 24 passé à 0H (capture 2)<br />- Apercu charge RAMS/ Eric Aboujdid (Capture 3) => surcharge en Avril 300H (dont 148H sur IPCEI Make Bzttery) => aucun changement . <br />Note : par contre dans apercu charge / Eric Ajoujdid/ Projet IPCEI MAKE Battery la charge est correctement affiché (0H en Avril24)<br /><br /><br /><br />**Liste des pièces jointes:**<br /><a href="http://webfdl.tnext.loc/api/public/Capture1-154211.JPG" target="_blank" >http://webfdl.tnext.loc/api/public/Capture1-154211.JPG</a><br /><a href="http://webfdl.tnext.loc/api/public/Capture2-831934.JPG" target="_blank" >http://webfdl.tnext.loc/api/public/Capture2-831934.JPG</a><br /><a href="http://webfdl.tnext.loc/api/public/Capture3-586707.JPG" target="_blank" >http://webfdl.tnext.loc/api/public/Capture3-586707.JPG</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : non<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 2<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Johana VALLY jvally 244473 Manager<br /> **Détails du serveur**<br />Version DB: 4.38.3; Version Soft: v1.0.13-Beta; Version Back: v1.0.12-Beta<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0<br />Adresse du PC :10.22.112.114<br />

**Comment by lokkotara** [comment]
Ce bug est causé par une méthode qui permet de mettre en cache une requête sur cet affichage. Si l'on appelle de nouveau la même requête, il ne refait pas d'appel à la base de données et renvoie plutôt les données mises en cache.

Ce comportement n'est pas désiré et l'équipe de dev va réfléchir à une solution pour régler ce souci.

Une mise à jour de ce ticket sera faite au fur et à mesure de l'avancement dans sa résolution.

Cordialement,

**Comment by lokkotara** [comment]
La mise en cache des données par rapport aux filtres sélectionnés sur l'affichage "Aperçu de la charge" a été retiré. Cependant, il est toujours nécessaire de mettre à jour l'affichage pour afficher les modifications (Rappel des infos en Base de données).
