### ISSUE TITLE
id:244473 Historique de charge en jours au lieu d'heures

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#270]
<br /> **Affichage concerné**<br />Charge / historique charge<br /> <br /> **Décrivez le bug**<br />L'affichage de l'historique de charge est en jours alors que tout le reste de l'environnement est en heures (capture)<br /> <br /> **A reproduire**<br />Vu sous RAMS/DSB Traction <br /><br /><br />**Liste des pièces jointes:**<br /><a href="http://webfdl.tnext.loc/api/public/Capture-883652.JPG" target="_blank" >http://webfdl.tnext.loc/api/public/Capture-883652.JPG</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : non<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 2<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Johana VALLY jvally 244473 User<br /> **Détails du serveur**<br />Version DB: 4.38.3; Version Soft: v1.0.13-Beta; Version Back: v1.0.12-Beta<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0<br />Adresse du PC :10.22.112.114<br />

**Comment by lokkotara** [comment]
En effet, la conversion n'avait pas été prise en compte sur cette partie des données.
Le changement a été fait et sera visible sur la prochaine version ( à partir de la v1.0.14)
Je laisse donc ouvert ce ticket le temps de vérifier que le changement est bien effectif.
