### ISSUE TITLE
id:244473 Problème de mise à jour de la fenetre Répartition des actuals

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#271]
<br /> **Affichage concerné**<br />Répartition des actuals<br /> <br /> **Décrivez le bug**<br /> APrès avec saisie intégralement son pointage sous la fenetre répartion des actuals et valider les changements, si on ouvre à nouveau la fenetre répartition des actuals il reste de la charge à répartir<br /> <br /> **A reproduire**<br /> Les étapes permettant de reproduire le comportement indésirable :<br />RAMS/ Marion Soussens / Répartir les Actuals<br />Saisie de tout le pointage (Capture 1)<br />Nettoyage du forecast dans passé<br />Valider les changements (plus de spent dans passé affiché)<br />Réouverture de la fenetre  Répartir les Actuals => il reste des activités à répartir (Capture 2)<br />Note: les prévisionnel dans le passé n'indique par contre plus de charge dans passé, cela semble être unqiuement un pb d'affichage de la fenetre Répartir les actuals<br /><br /> **Comportement attendu**<br /> Une description précise et concise du comportement attendu<br /> <br /> **Informations complémentaires**<br /> Ajoutez toutes autres informations qui permettraient une meilleure compréhension<br /><br />**Liste des pièces jointes:**<br /><a href="http://webfdl.tnext.loc/api/public/capture1-47197.png" target="_blank" >http://webfdl.tnext.loc/api/public/capture1-47197.png</a><br /><a href="http://webfdl.tnext.loc/api/public/Capture2-585640.JPG" target="_blank" >http://webfdl.tnext.loc/api/public/Capture2-585640.JPG</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : non<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 2<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Johana VALLY jvally 244473 User<br /> **Détails du serveur**<br />Version DB: 4.38.3; Version Soft: v1.0.13.1-Beta; Version Back: v1.0.12.1-Beta<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0<br />Adresse du PC :10.243.98.3<br />

**Comment by lokkotara** [comment]
Cela était dû à une mauvaise configuration des autorisations pour le rôle user sur cet affichage. Le changement est dores et déjà effectif sur la version de prod manuellement et sera pris en compte à partir de la v1.0.14.

Je clos le ticket.
