### ISSUE TITLE
id:244473 Pointage à saisir => éliminer la ligne CFR4930528 pour éviter les fausses manips

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#273]
<br /> **Affichage concerné**<br />Répartition des Actuals / Partie gauche remontée SAP<br /><br /> <br /> **Décrivez la demande d'évolution**<br />Dans la liste des actuals à répartir , éliminer la ligne :<br />CFR4930528 (Centre de coût : TRB Engineering)<br />je crains que des personnes essayent de saisir leur vacances ou formation<br /> <br />**Liste des pièces jointes:**<br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Type de demande d'évolution**<br />Type : ajout<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Johana VALLY jvally 244473 User<br /> **Détails du serveur**<br />Version DB: 4.38.3; Version Soft: v1.0.13.1-Beta; Version Back: v1.0.12.1-Beta<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0<br />Adresse du PC :10.243.98.3<br />

**Comment by lokkotara** [comment]
En effet, les actuals CFR ne devaient pas figurés dans la liste et ne seront plus récupérés à partir de la V.1.13.1.

Cordialement,
