### ISSUE TITLE
id:244473 Bug à confirmer sur charge restante en générique après affectation ressource

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#275]
<br /> **Affichage concerné**<br />Ressource / Affectation<br /> <br /> **Décrivez le bug**<br />Après transfert d'activité d'une ressource Générique à une ressource existante il reste un reliquats de charge non compréhensible<br /> <br /> **A reproduire**<br /> Les étapes permettant de reproduire le comportement indésirable :<br /> RAMS/ IPCEI2_HTPG/ Affectation <br />Modifier<br />Selection ligne SGR => IQA (Cf capture)<br />Selectionner Générique => Badr<br />Toute la charge est basculé vers Badr sauf 29,4H qui reste en générique (Cf Capture2)<br /><br /> **Comportement attendu**<br />Il ne doit pas rester de charge dans générique (controle dans FDL pas de charge en spent générique par erreur, valeur qui ne corresond pas non plus au delta, ligne avec des cout voyage mais pas la bonne valeur etc...)<br /> <br /><br /><br />**Liste des pièces jointes:**<br /><a href="http://webfdl.tnext.loc/api/public/Capture-296580.png" target="_blank" >http://webfdl.tnext.loc/api/public/Capture-296580.png</a><br /><a href="http://webfdl.tnext.loc/api/public/Capture2-57870.JPG" target="_blank" >http://webfdl.tnext.loc/api/public/Capture2-57870.JPG</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : non<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 2<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Johana VALLY jvally 244473 User<br /> **Détails du serveur**<br />Version DB: 4.38.3; Version Soft: v1.0.13.1-Beta; Version Back: v1.0.12.1-Beta<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0<br />Adresse du PC :10.243.98.3<br />

**Comment by lokkotara** [comment]
Cela correspondait à de la charge prévue  sur la ressource générique en dehors de la fenêtre de temps. Dans cet exemple, la charge correspondait à de la charge prévue dans le passé. Il fallait donc aller sur l'affichage "prévisionnel passé" si l'on voulait nettoyer cette charge non dépensée ou se rendre sur l'affichage "Répartition de la charge" et faire la dépense sur cette activité à partir des actuals.
