### ISSUE TITLE
id:206314 Passage HTTPS

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#276]
<br /> **Affichage concerné**<br />Tous<br /> <br /> **Décrivez la demande d'évolution**<br />Le site fonctionne en HTTP, mais pas HTTPS. Les navigateurs modernent tendent à limiter l'acces aux sites HTTP, on risque donc de se retrouver avec un outil bloqué à l'avenir lors d'une prochaine maj de Chrome ou Firefox.<br /><br /> **Informations complémentaires**<br /> Ajoutez toutes autres informations qui permettraient une meilleure compréhension.<br /> N'hésitez pas à rajouter des schémas, organigrammes, dessins dans les fichiers joints.<br /><br />**Liste des pièces jointes:**<br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Type de demande d'évolution**<br />Type : ajout<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Fabien GOY fgoy 206314 User<br /> **Détails du serveur**<br />Version DB: 4.38.3; Version Soft: v1.0.13.1-Beta; Version Back: v1.0.12.1-Beta<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36<br />Adresse du PC :10.24.103.235<br />

**Comment by lokkotara** [comment]
Le demande avait été faite auprès de l'IT il y a déjà quelques temps. Nous avons reçu le certificat il y a quelques jours et l'appli est donc passée en https.

Je clos donc cette demande d'évolution.

Cordialement,
