### ISSUE TITLE
id:206314 Ajout d'un lien vers les vidéos

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#277]
<br /> **Affichage concerné**<br />Tous<br /> <br /> **Décrivez la demande d'évolution**<br /> Il serait utile d'avoir un endroit dans le menu déroulant qui nous envoie vers le mode d'emploi ou les vidéos<br /> <br /> **Informations complémentaires**<br /> Ajoutez toutes autres informations qui permettraient une meilleure compréhension.<br /> N'hésitez pas à rajouter des schémas, organigrammes, dessins dans les fichiers joints.<br /><br />**Liste des pièces jointes:**<br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Type de demande d'évolution**<br />Type : ajout<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Fabien GOY fgoy 206314 User<br /> **Détails du serveur**<br />Version DB: 4.38.3; Version Soft: v1.0.13.1-Beta; Version Back: v1.0.12.1-Beta<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36<br />Adresse du PC :10.22.108.171<br />

**Comment by lokkotara** [comment]
Un onglet "liens utiles" est ajouté à partir de la v1.0.0 où l'on retrouve la playlist des vidéos tuto, la racine du sharepoint où se trouvent les docs nécessaires ainsi que le Teams dédié à l'application.
