### ISSUE TITLE
id:244473 Ticket 242 à réouvrir à l'identique

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#278]
<br /> Ticket 242 clos avec des commentaires indiquant son traitement<br /><br /><br />Descriptif du prob à reprendre => Je refais exactement la même manip et ai le meme resultat (la seule différence est que le test est fait avec une activité dont il n'y a plus de prévisionnel)<br />**Liste des pièces jointes:**<br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : non<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 2<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Johana VALLY jvally 244473 User<br /> **Détails du serveur**<br />Version DB: 4.38.3; Version Soft: v1.0.13.1-Beta; Version Back: v1.0.12.1-Beta<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0<br />Adresse du PC :10.243.98.3<br />

**Comment by lokkotara** [comment]
Le process a bien été modifié et le ticket traité.

 Le problème se situait au niveau de l'autorisation d’exécuter la requête en fonction du rôle. Cela était mal configuré.
J'ai apporté un changement immédiat sur le serveur afin de vous laisser la possibilité de vous en servir de suite. Il sera aussi ajouté automatiquement lors des prochaines mises à jour.

Cordialement,
