### ISSUE TITLE
id:244473 Plus de visulisation de l'historique de charge

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#279]
<br /> **Affichage concerné**<br />Historique de charge<br /> <br /> **Décrivez le bug**<br />Plus de visualisation de l'historique de charge<br /> <br /> **A reproduire**<br />Connexion Manager (comportement idem User)<br />Charge / Historique de charge<br />RAMS/ DSB Traction<br />Plus d'info graphique ni de rappel des commentaires de modifs (capture2)<br />Sur version précédente affichage foncitonnait (mais avec bug sur heure) (capture 1)<br /><br /><br /><br />**Liste des pièces jointes:**<br /><a href="https://awa-dev.tnext.loc/api/public/capture1-616800.jpg" target="_blank" >https://awa-dev.tnext.loc/api/public/capture1-616800.jpg</a><br /><a href="https://awa-dev.tnext.loc/api/public/Capture2-412823.JPG" target="_blank" >https://awa-dev.tnext.loc/api/public/Capture2-412823.JPG</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : non<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 2<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Johana VALLY jvally 244473 Manager<br /> **Détails du serveur**<br />Version DB: 4.42.0; Version Soft: v1.0.13.1-Beta-18-gd7f87ab; Version Back: v1.0.12.1-Beta-11-g84fd47f<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0<br />Adresse du PC :10.22.112.114<br />

**Comment by lokkotara** [comment]
Ce comportement a été rectifié et sera modifié à partir de la v1.0.15.

Je clos ce ticket, cordialement.
