### ISSUE TITLE
id:244473 Ticket 278 : toujours même comportement

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#280]
<br /> Cf Ticket 278<br />Connexion sur User ou Manager mène au même résultat<br />Pas de changement d'OTP<br />Pas de message d'alerte en mode user <br />**Liste des pièces jointes:**<br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : non<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 2<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Johana VALLY jvally 244473 Manager<br /> **Détails du serveur**<br />Version DB: 4.42.0; Version Soft: v1.0.13.1-Beta-18-gd7f87ab; Version Back: v1.0.12.1-Beta-11-g84fd47f<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0<br />Adresse du PC :10.22.112.114<br />

**Comment by lokkotara** [comment]
Un décalage entre les mises à jour de la partie front et de la partie back de l'appli causait ce souci. Le changement est effectif à partir de la v1.0.14.

Cordialement,
