### ISSUE TITLE
id:244473 Affichage du graphe sous Gestion de la capacité des ressources à améliorer

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#281]
<br />Sous « Ressource », « Capacité » <br />L'affichage de la capacité dans le temps ne semble pas avoir une logique uniforme en fonction des ressources<br />En l'état cet affichage n'est pas très utilisable<br /><br />Ressrouce 1 : Cf Capture 1 , pas de lien entre date de modification du profil de la ressource et affichage qui démarre en 2011<br />Ressrouce 2 : Cf Capture 2, affichage cohérent entre la date de démarrage de la ressource et l'affichage de sa capacité<br /><br />**Liste des pièces jointes:**<br /><a href="https://awa-dev.tnext.loc/api/public/capture1-342508.jpg" target="_blank" >https://awa-dev.tnext.loc/api/public/capture1-342508.jpg</a><br /><a href="https://awa-dev.tnext.loc/api/public/Capture2-735008.JPG" target="_blank" >https://awa-dev.tnext.loc/api/public/Capture2-735008.JPG</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Type de demande d'évolution**<br />Type : modification<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Johana VALLY jvally 244473 User<br /> **Détails du serveur**<br />Version DB: 4.42.0; Version Soft: v1.0.13.1-Beta-18-gd7f87ab; Version Back: v1.0.12.1-Beta-11-g84fd47f<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0<br />Adresse du PC :10.22.112.114<br />

**Comment by lokkotara** [comment]
Le graph sur cet affichage a été retiré car non pertinent. Cordialement,
