### ISSUE TITLE
id:244473 Droit User possible pour affecter une ressource à un métier 

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#282]
<br /> **Affichage concerné**<br /> Ressource / Capacité<br /> <br /> **Décrivez la demande d'évolution**<br />Actuellement en mode User il est possible d'ajouter une ressource sur un nouveau métier<br />Cette action doit être réserver au mode Manager<br /><br />Il est obligatoire qu'un manager verrouille la liste des personnes qui travaille sur son métier et que cette action soit accessible à un nombre restreint de personne <br />Car inversement et idéalement il ne faudrait pas pouvoir déclarer une ressource partagée si le manager en charge de la personne n'est pas au courant<br />**Liste des pièces jointes:**<br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Type de demande d'évolution**<br />Type : modification<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Johana VALLY jvally 244473 User<br /> **Détails du serveur**<br />Version DB: 4.42.0; Version Soft: v1.0.13.1-Beta-18-gd7f87ab; Version Back: v1.0.12.1-Beta-11-g84fd47f<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0<br />Adresse du PC :10.22.112.114<br />

**Comment by lokkotara** [comment]
Cette vue est pour le moment ouvert à tous. Mais elle sera restreinte au rôle Manager avant le  passage en production

**Comment by lokkotara** [comment]
Comme annoncé mi Mars, cet affichage a été restreint au rôle manager. Il n'est donc plus possible un rôle utilisateur standard d'effectuer cette action. Je clos donc la demande.
