### ISSUE TITLE
id:244473 Bug mineur d'affichage dans répartition charge

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#283]
<br /> **Affichage concerné**<br />Répartition charge sur futur lointain<br /> <br /> **Décrivez le bug**<br />Répartition charge sur futur lointain => le forecast par mois apparaît en transparence dans les colonnes récap du tableau à gauche (Cf visu Capture)<br /> <br /> **A reproduire**<br /> Les étapes permettant de reproduire le comportement indésirable :<br />Répartition charge Suivi de fiabilité/ Stéphane Gauthier<br />Pic de charge en Mars 24 sur RERNG à 500H<br />Répartition sur 30 mois du pic de charge de 14,8H<br />En déplaçant le visuel du planning de charge, la charge par mois apparaît en transparence des colonnes Delta Activité et Delta Projet (Cf Capture)<br />**Liste des pièces jointes:**<br /><a href="https://awa-dev.tnext.loc/api/public/Capture-545562.JPG" target="_blank" >https://awa-dev.tnext.loc/api/public/Capture-545562.JPG</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : non<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 2<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Johana VALLY jvally 244473 Manager<br /> **Détails du serveur**<br />Version DB: 4.42.0; Version Soft: v1.0.13.1-Beta-18-gd7f87ab; Version Back: v1.0.12.1-Beta-11-g84fd47f<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0<br />Adresse du PC :10.22.112.114<br />

**Comment by lokkotara** [comment]
La couleur bleue était définie avec une opacité inférieure à 100%, d'où l'effet de transparence. Cela a été corrigé depuis la v1.0.14
