### ISSUE TITLE
id:485386 Défaut affichage Icônes

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#284]
<br /> **Affichage concerné**<br /> Tous<br /> <br /> **Décrivez le bug**<br /> La librairie FONTAWESOME n'est pas chargée au démarrage<br /> <br /> **A reproduire**<br /> Les étapes permettant de reproduire le comportement indésirable :<br /> 1. Sur l'affichage '...'<br /> 2. Je clique sur '....'<br /> 3. Je descend le tableau '....'<br /> 4. L'erreur se reproduit<br /><br /> **Comportement attendu**<br /> Une description précise et concise du comportement attendu<br /> <br /> **Informations complémentaires**<br /> Navigateur Edge Version 121.0.2277.83<br /><br />**Liste des pièces jointes:**<br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : non<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 2<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Olivier FICHET 485386 485386 User<br /> **Détails du serveur**<br />Version DB: 4.42.0; Version Soft: v1.0.13.1-Beta-18-gd7f87ab; Version Back: v1.0.12.1-Beta-11-g84fd47f<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0<br />Adresse du PC :10.243.98.2<br />

**Comment by lokkotara** [comment]
Le lien externe vers la bibliothèque pouvait être bloqué par le pare-feu Alstom. Afin d'éviter ce souci à l'avenir, la librairie a été transféré localement dans l'appli. Ce changement est disponible à partir de la v1.0.14
