### ISSUE TITLE
id:480245 Probleme d'adaptation de l'affichage sur la table bas/droite 

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#287]
<br /> **Répartition de la charge**<br /><br />**Décrivez le bug**<br />j'ai affiché la page répartition de charge et filtré sur le métier validation System traction pour voir tous les membres de l'équipe (> 20 personnes).<br />J'ai ensuite fait CTRL + scroll pour réduire la taille de police et afficher plus de membres dans le tableau en bas à droite de la page.<br /><br />Par contre un blanc "inutile" se créé entre la table et les boutons, sans me permettre de voir plus de personnes en même temps dans la table.<br /><br /> **A reproduire**<br />Les étapes permettant de reproduire le comportement indésirable :<br />1. Sur l'affichage 'Répartition de la charge'<br />j'ai affiché la page répartition de charge et filtré sur le métier validation System traction pour voir tous les membres de l'équipe (> 20 personnes).<br />J'ai ensuite fait CTRL + scroll pour réduire la taille de police et afficher plus de membres dans le tableau en bas à droite de la page.<br /><br />**Comportement attendu**<br />mise à l'échèle de la table pour permettre de voir la totalité des ressources en même temps<br /><br /><br /><br />**Liste des pièces jointes:**<br /><br /><br />**Liste des pièces jointes:**<br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : non<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 2<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Davy BONNASSIES 480245 480245 Manager<br /> **Détails du serveur**<br />Version DB: 4.42.0; Version Soft: v1.0.14-Beta; Version Back: v1.0.13-Beta<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0<br />Adresse du PC :10.24.100.87<br />

**Comment by lokkotara** [comment]
L'adaptation au de-zoom a été mis en place sur l'affichage "Répartition de la charge" à partir de la v1.0.14 et sera harmonisé sur tous les autres concernés dans une prochaine mise à jour.
