### ISSUE TITLE
id:521415 Ajout de justification lors de création chiffrage ou VO

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#288]
<br /> **Affichage concerné**<br />Lors de la création de la charge initiale d'une FdL ou lors d'une VO, il est nécessaire d'ajouter des commentaires / documents sous forme d'image/mail/tableau/texte (1 ou plusieurs choix afin de justifier et enregistrer les hypothèses de base.<br /> <br /> **Décrivez la demande d'évolution**<br />Dans un 1er step "simple", ajouter une text box (aujourd'hui une seule ligne est possible et ce n'est pas suffisant)<br />Dans un 2ème temps, pouvoir joindre un document.<br /> <br /> **Informations complémentaires**<br /> <br /><br />**Liste des pièces jointes:**<br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Type de demande d'évolution**<br />Type : ajout<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Jean-Yves RITZMANN 521415 521415 Manager<br /> **Détails du serveur**<br />Version DB: 4.42.0; Version Soft: v1.0.14-Beta; Version Back: v1.0.13-Beta<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0<br />Adresse du PC :10.24.101.20<br />

**Comment by lokkotara** [comment]
Une zone de texte a été mise en place dans la modale permettant de laisser un commentaire. De même, sur l'affichage "Historique de la charge", un bouton permet maintenant d'ouvrir une modale pour afficher le détail du commentaire. Ces changements sont disponibles à partir de la v1.0.14.

Le step 2 sera traité ultérieurement.

**Comment by lokkotara** [comment]
A partir de la V2, le nouvel affichage permettant de gérer les demandes de variation budget couvre ce besoin. un autre ticket reprend le besoin pour le primo chiffrage.
