### ISSUE TITLE
id:238244 Sélection dans les filtres

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#289]
Par exemple, dans Charge/répartition charge/rechercher par filtre :<br /><br /><br /> **Affichage concerné**<br />Multi-affichage : partout où on ouvre un filtre.<br /> <br /> **Décrivez la demande d'évolution**<br />Il existe déjà un bouton "Tout désélectionner", serait-il possible d'avoir un bouton "Tout sélectionner" ?<br /> <br /> **Informations complémentaires**<br />Cf exemple de filtre joint<br />**Liste des pièces jointes:**<br /><a href="https://awa.tnext.loc/api/public/Capture%20filtre-286775.jpg" target="_blank" >https://awa.tnext.loc/api/public/Capture%20filtre-286775.jpg</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Type de demande d'évolution**<br />Type : ajout<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Francois TERRIEN fterrien 238244 Manager<br /> **Détails du serveur**<br />Version DB: 4.42.0; Version Soft: v1.0.14-Beta; Version Back: v1.0.13-Beta<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0<br />Adresse du PC :10.24.100.174<br />

**Comment by lokkotara** [comment]
Il est possible de reprendre le même principe que sur l'affichage "Affectation des ressources" ou lorsque rien n'est coché, le bouton affiche "Tout sélectionner" et lorsqu'il y a au moins une case coché, le bouton affiche alors "Tout déselctionner". Il serait mis en place sur le filtre ressource et le filtre projet.

**Comment by lokkotara** [comment]
Cette fonctionnalité a été prise en compte et sera disponible dans l'appli à partir de la v1.0.15.

Cordialement,
