### ISSUE TITLE
id:423920 Saisie semi-automatique lors de la répartition des actuals

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#290]
<br /> **Affichage concerné**<br /> Actuals à répartir (workload-allocation)<br /> <br /> **Décrivez la demande d'évolution**<br />Afin de simplifier la saisie des actuals sur une ligne projet, créer un bouton additionnel à côté de la zone de saisie des heures. Ce bouton permettrait d'assigner automatiquement sur la ligne sélectionnée la totalité des heures à affecter. Cela afin d'éviter sur chaque ligne de juste recopier le chiffre.<br />L'unique moment où il serait nécessaire de rentrer le chiffre exact dans la zone de saisie, serait lorsqu'on souhaite faire une répartition sur plusieurs lignes projet.<br /><br />Permettrait un gain de temps et d'efficacité lors de la remontée du pointage d'un grand nombre d'activités en supprimant la saisie manuelle qui est dans ce cas précis un simple recopiage (aucun intérêt).<br /> <br /> **Informations complémentaires**<br />Sur la capture d'écran en pièce jointe, il y a 28,8hrs à affecter, 2 lignes sont dispo. Je souhaite affecter la totalité des heures sur la deuxième ligne. Je coche ou clique sur le bouton de saisie semi-automatique et la totalité des heures sont rentrées automatiquement.<br />**Liste des pièces jointes:**<br /><a href="https://awa.tnext.loc/api/public/Capture%20d%E2%80%99%C3%A9cran%202024-03-15%20152113-211523.png" target="_blank" >https://awa.tnext.loc/api/public/Capture%20d%E2%80%99%C3%A9cran%202024-03-15%20152113-211523.png</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Type de demande d'évolution**<br />Type : ajout<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Loic SAELINS lsaelin 423920 Manager<br /> **Détails du serveur**<br />Version DB: 4.42.0; Version Soft: v1.0.14-Beta-8-g400960e; Version Back: v1.0.13-Beta-8-g0154c31<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0<br />Adresse du PC :10.24.100.61<br />

**Comment by lokkotara** [comment]
Possibilité d'ajouter un bouton à côte du champ à répartir. Au clic, ajoute le reste à répartir de l'actual concerné à la valeur du champ.

**Comment by dtisnegr** [comment]
evolution faite
