### ISSUE TITLE
id:200959906 Impossible de filtrer sur l'APLS Id dans l'affichage resource-creation

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#291]
<br /> **Affichage concerné**<br />Resource-creation<br /> <br /> **Décrivez le bug**<br />Lorsqu'on filtre sur la colonne ALPS, aucun résultat ne s'affiche, peu importe la sélection<br /> <br /> **A reproduire**<br /> Les étapes permettant de reproduire le comportement indésirable :<br /> 1. Sur l'affichage resource-creation<br /> 2. Je clique sur filtrer par ALPS<br /> 3. Je choisi n'importe quelle valeur et je clique sur OK<br /> 4. L'erreur se reproduit<br /><br /> **Comportement attendu**<br /> Filtre sur l'ALPS Id sélectionné<br /><br />**Liste des pièces jointes:**<br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : oui<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 4<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Daniel DDY e_ddupuy 200959906 Admin<br /> **Détails du serveur**<br />Version DB: 4.42.0; Version Soft: v1.0.14-Beta-8-g400960e; Version Back: v1.0.13-Beta-8-g0154c31<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0<br />Adresse du PC :10.22.112.171<br />

**Comment by dtisnegr** [comment]
corrigé
