### ISSUE TITLE
id:200959906 Bugs sur Activity-management sur le nouveau projet 'VHST APAC'

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#292]
<br /> **Affichage concerné**<br />Gestion des activités<br /> <br /> **Décrivez le bug**<br />En vue sous forme de liste, certaine activités n'ont pas de tâche associé.<br />En vue matricielle, des colonnes en trop sur les activités ayant des sous-tâches.<br /> <br /> **A reproduire**<br /> Les étapes permettant de reproduire le comportement indésirable :<br /> 1. Sur l'affichage 'Activité' puis 'Gestion'<br /> 2. Je clique sur 'Power' puis 'VHST APAC'<br /> 3. En vue sous forme de liste, sur certaines activités, la vue tâche n'apparaît pas<br /> 4. En vue matricielle, des colonne superflues apparaissent<br /><br />**Liste des pièces jointes:**<br /><a href="https://awa.tnext.loc/api/public/Bug%20Activity-Management-437201.JPG" target="_blank" >https://awa.tnext.loc/api/public/Bug%20Activity-Management-437201.JPG</a><br /><a href="https://awa.tnext.loc/api/public/Bug%20Activity-Management_2-536705.JPG" target="_blank" >https://awa.tnext.loc/api/public/Bug%20Activity-Management_2-536705.JPG</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : non<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 2<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle : DDY e_ddupuy 200959906 Admin<br /> **Détails du serveur**<br />Version DB: 4.44.3; Version Soft: v1.0.15-Beta; Version Back: v1.0.14-Beta<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0<br />Adresse du PC :10.22.112.171<br />

**Comment by lokkotara** [comment]
Les données d'importation ainsi que la logique d'affichage a été revu et ne devrait plus reproduire ce comportement. Il est cependant difficile de reproduire exactement le même bug car le projet en question n'est plus remonté.

Cordialement,
