### ISSUE TITLE
id:521415 Mauvais calcul delta projet

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#293]
<br /> **Affichage concerné**<br />Répartition de la charge (en heures)<br /> <br /> **Décrivez le bug**<br />L'ajout d'heures dans une case vide, modifie le calcul du delta projet.<br />Si on repasse cette case en valeur d'origine par le bouton dédié, le calcul du delta projet ne se modifie pas.<br />A noter que si on modifie cette même cellule à la valeur de 0, le calcul se fait correctement<br /> <br /><br />**Liste des pièces jointes:**<br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : non<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 2<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Jean-Yves RITZMANN 521415 521415 Manager<br /> **Détails du serveur**<br />Version DB: 4.44.3; Version Soft: v1.0.15-Beta; Version Back: v1.0.14-Beta<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0<br />Adresse du PC :10.24.102.229<br />

**Comment by lokkotara** [comment]
La méthode prenant en charge le calcul des totaux activités et projets n'était pas rééxécuctée Cela a été modifié et sera visible à partir de la v.1.0.16.  
Cordialement,
