### ISSUE TITLE
id:200959906 Evolution sur vue project-creation

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#294]
<br /> **Affichage concerné**<br />Affichage Création/Modification de projet<br /> <br /> **Décrivez la demande d'évolution**<br />Ne pas quitter la vue directement lorsque l'on appuie sur "valider les changements" mais plutôt faire apparaître une modale indiquant que les modification ont bien été prises en compte et rester sur la vue.<br />**Liste des pièces jointes:**<br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Type de demande d'évolution**<br />Type : modification<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle : DDY e_ddupuy 200959906 Admin<br /> **Détails du serveur**<br />Version DB: 4.44.3; Version Soft: v1.0.15-Beta; Version Back: v1.0.14-Beta<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0<br />Adresse du PC :10.243.98.2<br />

**Comment by dtisnegr** [comment]
rectification faite
