### ISSUE TITLE
id:200959906 Vue project-management : impossible de désactiver une option

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#295]
<br /> **Affichage concerné**<br />Vue project-management<br /> <br /> **Décrivez le bug**<br />Je décoche une option.<br />Mes choix ne sont pas pris en compte lorsque j'appuie sur "Valider les changement"<br /><br />**Liste des pièces jointes:**<br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : oui<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 4<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle : DDY e_ddupuy 200959906 Admin<br /> **Détails du serveur**<br />Version DB: 4.44.3; Version Soft: v1.0.15-Beta; Version Back: v1.0.14-Beta<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0<br />Adresse du PC :10.243.98.3<br />

**Comment by dtisnegr** [comment]
bug corrigé
