### ISSUE TITLE
id:200959906 Gestion des projets en catégorie Hors Demand Plan

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#296]
<br /> **Affichage concerné**<br />Tous les affichages ayant un graphe<br /> <br /> **Décrivez le bug**<br />La charge Hors Demand Plan ne doit pas apparaître dans les graphes ni dans la liste des projets sauf pour les vues resource-allocation, project-management et project-creation.<br /> <br /><br />**Liste des pièces jointes:**<br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : oui<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 4<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle : DDY e_ddupuy 200959906 Admin<br /> **Détails du serveur**<br />Version DB: 4.44.3; Version Soft: v1.0.15-Beta; Version Back: v1.0.14-Beta<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0<br />Adresse du PC :10.22.112.171<br />

**Comment by lokkotara** [comment]
Au 10/06/2024 (lancement en production), il n' y a pas de hors demand plan dans l'appli. Cependant, à la prochaine revue de charge, il est nécessaire de se questionner pour savoir comment gérer le futur hors demand plan.

Il ne doit plus apparaître dans la charge mais doit pouvoir être consulter par Daniel.

Proposition : Lorsque l'on archive un projet (affichage "création de projet") , il n'apparaît plus dans les autres affichages.
