### ISSUE TITLE
id:244473 Bug ou clarification sur présence ALSTOM OLD à l'affectation + sur mode calcul delta activité

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#298]
<br /> **Affichage concerné**<br />Affectation des ressources<br /> <br /> **Décrivez le bug**<br />Lors de la réaffectation d'activité d'une ressource active vers du générique, une partie transférée vers une ressource "ALSTOM OLD"<br />+ Lors de cette manip, constat d'un comportement à confirmer sur le calcul du taol activité et Delta activité <br /> <br /> **A reproduire**<br /> Les étapes permettant de reproduire le comportement indésirable :<br />1. Affectation ressource / RAMS/ IPCEI2 HTPG (capture1)<br />2. Supprimer ressource Badr de activit" RAMS SGR ->  (capture 2). Il reste 166,5H de Total à Badr<br />3. Valider les changements, constat qu'il reste plus que 118.4H à Badr et qu'une ressource ALSTOM OLD avec 48,1H est apparu (capture3)<br />4. Changement menu pour réaliser le pointage de Badr sur le mois de Mars (il avait du forecast dans passé)<br />5. REtour à l'affichage Affectation ressource : le total de Badr a changé mais également le delta activité (capture 4) : +99.H alors qu'il était à +233.1<br /><br /> **Comportement attendu**<br />2 points:<br />- Pas de ressource ALSTOM OLD attendu . Si on supprime une ressource avec forecast dans passé, tout le budget doit rester sur cette ressource <br />- Le delta activité doit inclure le forecast dans passé et doit être la somme de tout le forecast et tout le spent<br /><br />**Liste des pièces jointes:**<br /><a href="https://awa.tnext.loc/api/public/Capture1-59567.JPG" target="_blank" >https://awa.tnext.loc/api/public/Capture1-59567.JPG</a><br /><a href="https://awa.tnext.loc/api/public/Capture2-81940.JPG" target="_blank" >https://awa.tnext.loc/api/public/Capture2-81940.JPG</a><br /><a href="https://awa.tnext.loc/api/public/Capture3-677582.JPG" target="_blank" >https://awa.tnext.loc/api/public/Capture3-677582.JPG</a><br /><a href="https://awa.tnext.loc/api/public/Capture4-700018.JPG" target="_blank" >https://awa.tnext.loc/api/public/Capture4-700018.JPG</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : non<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 2<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Johana VALLY jvally 244473 Manager<br /> **Détails du serveur**<br />Version DB: 4.44.3; Version Soft: v1.0.15-Beta; Version Back: v1.0.14-Beta<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0<br />Adresse du PC :10.243.98.2<br />

**Comment by lokkotara** [comment]
La suppression du dépensé sur la ressource n'est plus transféré sur Alstom old et la fonction du bouton "supprimer" a été modifié pour ne supprimer que le prévisionnel. De plus, le bug concernant la mise à jour des colonnes delta a été résolu et est disponible dans la v1.0.0 de production. Cordialement,
