### ISSUE TITLE
id:244473 Incohérence dans liste des FDL prev selon les vues

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#299]
<br /> **Affichage concerné**<br />Filtre projet de "Affectations des ressources" et "Répartition de la charge"<br /> <br /> **Décrivez le bug**<br />Incohérence dans la liste des FDL Prev entre "Affectations des ressources" et "Répartition de la charge"<br /> <br /> **A reproduire**<br /> Les étapes permettant de reproduire le comportement indésirable :<br />1. Sur affichage Affectation des ressource , recherche FDL Forecast RAMS AM30 SNCB Armoires. 74H de contrat (Pour info: réaffectation de générique vers Presta_LGM et tentative d'affectation de la charge qui ne semble pas fonctionner - duplication des charges. Du coup tentative pour faire cette répartition sous autre affichage) (Cf liste Projet Forecast en capture 1)<br />1. Sur affichage Repartition charge, recherche FDL Forecast RAMS AM30 SNCB Armoires => n'existe pas (Cf liste Projet Forecast en capture 2)<br /><br /> **Comportement attendu**<br />Liste cohérente des projets entre les affichages<br /> <br /><br /><br />**Liste des pièces jointes:**<br /><a href="https://awa.tnext.loc/api/public/Capture1-70543.JPG" target="_blank" >https://awa.tnext.loc/api/public/Capture1-70543.JPG</a><br /><a href="https://awa.tnext.loc/api/public/Capture2-94463.JPG" target="_blank" >https://awa.tnext.loc/api/public/Capture2-94463.JPG</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : non<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 2<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Johana VALLY jvally 244473 Manager<br /> **Détails du serveur**<br />Version DB: 4.44.3; Version Soft: v1.0.15-Beta; Version Back: v1.0.14-Beta<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0<br />Adresse du PC :10.243.98.2<br />

**Comment by lokkotara** [comment]
Le souci d'incohérence entre affichages a été rectifié. Après vérification dans la version de production (v1.0.0), le projet apparaît correctement sur ces deux affichages. 
Je clos donc le ticket
