### ISSUE TITLE
id:244473 Affectation ressource: Affichage  "Choix des activités" pas dans même ordre que liste activités

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#300]
<br /> **Affichage concerné**<br />Affectation des ressources, fenêtre "Choix des activités"<br /> <br /> **Décrivez la demande d'évolution**<br /> Pour modifier une ressource sur une activités une fenêtre Choix Activités s'ouvre mais elle n'est pas trier de la même façon que la liste d'activités (capture 1)<br /><br />Cela peut être galère pour les affectations de ressource lors d'une création de projet sur les métiers qui ont beaucoup de lignes d'activités<br /><br /> <br />**Liste des pièces jointes:**<br /><a href="https://awa.tnext.loc/api/public/Capture1-325564.JPG" target="_blank" >https://awa.tnext.loc/api/public/Capture1-325564.JPG</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Type de demande d'évolution**<br />Type : ajout<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Johana VALLY jvally 244473 Manager<br /> **Détails du serveur**<br />Version DB: 4.44.3; Version Soft: v1.0.15-Beta; Version Back: v1.0.14-Beta<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0<br />Adresse du PC :10.243.98.2<br />

**Comment by lokkotara** [comment]
Ceci était dû à un effet de bord suite à la modification de la fonction concernée. Cela a été rectifiée à partir de la v1.0.0. Cordialement,
