### ISSUE TITLE
id:244473 Changement majeur d'approche sur visu du générique

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#301]
<br /> **Affichage concerné**<br />Répartition charge <br /> <br /> **Décrivez la demande d'évolution**<br />Changement majeur entre ancien outil et nouveau sur la gestion du générique<br />Dans répartition charge, les activités laissées à une ressources génériques ne sont plus visibles <br />Avec la gestion par écart on pourrait être tenté de conclure que l'on a des marges sur le projet<br /><br />Est il possible d'envisager un msg sur ce type d'affichage pour alerter qu'il existe de la charge non affectée?<br /><br />**Liste des pièces jointes:**<br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Type de demande d'évolution**<br />Type : ajout<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Johana VALLY jvally 244473 Manager<br /> **Détails du serveur**<br />Version DB: 4.44.3; Version Soft: v1.0.15-Beta; Version Back: v1.0.14-Beta<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0<br />Adresse du PC :10.243.98.2<br />

**Comment by lokkotara** [comment]
Après vérification sur l'application en version de production v1.0.0, la charge du générique apparaît correctement sur l'affichage et est donc pris en compte pour le calcul des deltas. Je clos donc favorablement cette demande.
