### ISSUE TITLE
id:206314 menu déroulant ne s'ouvre plus

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#302]
<br /> **Affichage concerné**<br />Apercu charge<br /> <br /> **Décrivez le bug**<br />Une fois cliqué sur Apercu charge, le menu déroulant ne fonctionne plus, la console renvoie en permanence l'érreur suivante de la capture<br /> <br /> **A reproduire**<br /><br /><br /> **Comportement attendu**<br /> Une description précise et concise du comportement attendu<br /> <br /> **Informations complémentaires**<br /> Ajoutez toutes autres informations qui permettraient une meilleure compréhension<br />Fabien GOY (Manager)<br />Version DB: 4.44.3 (2024-04-08)<br />Version Soft : v1.0.15-Beta-32-gebe2f8f<br />Version Back : v1.0.14-Beta-19-g397cf55<br />**Liste des pièces jointes:**<br /><a href="https://awa-dev.tnext.loc/api/public/Capture%20d%E2%80%99%C3%A9cran%202024-04-22%20151027-133928.png" target="_blank" >https://awa-dev.tnext.loc/api/public/Capture%20d%E2%80%99%C3%A9cran%202024-04-22%20151027-133928.png</a><br /><a href="https://awa-dev.tnext.loc/api/public/Capture%20d%E2%80%99%C3%A9cran%202024-04-22%20151222-915416.png" target="_blank" >https://awa-dev.tnext.loc/api/public/Capture%20d%E2%80%99%C3%A9cran%202024-04-22%20151222-915416.png</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : non<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 2<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Fabien GOY fgoy 206314 Manager<br /> **Détails du serveur**<br />Version DB: 4.44.3; Version Soft: v1.0.15-Beta-32-gebe2f8f; Version Back: v1.0.14-Beta-19-g397cf55<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36<br />Adresse du PC :10.22.108.171<br />

**Comment by lokkotara** [comment]
Ce bug ne semble pas être reproduit malgré nos essais. En regardant de plus près, je vois que l'url des captures d'écran indique qu'elles ont été réalisées sur le serveur de dev et non celui de production. Celui-ci étant moins stable car servant à nos essais, je vous invite à reproduire les étapes précédentes sur  cette adresse : https://awa.tnext.loc/ afin de vérifier si le bug se reproduit. 

Je ferme cette issue et vous invite à en ouvrir une nouvelle si le bug se reproduisait.

Cordialement,
