### ISSUE TITLE
id:244473 Bug sur sleciton d'une Option d'affichage sur le Tableau de bord de la charge

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#303]
<br /> **Affichage concerné**<br />Tableau de bord de la charge / Option d'affichage<br /> <br /> **Décrivez le bug**<br />Message d'erreur apparait à la selection d'une option d'afficahge<br /> <br /> **A reproduire**<br /><br />Tableau de bord<br />Metier RAMS<br />Clic sur Option d'affichage<br /><br />Test sur le deuxième choix de la liste ou le troisieme => message d'erreur (cf pièce jointe)<br /><br />Il est possible de revenir à un autre affichage et de continuer à travailler sur l'appli<br />**Liste des pièces jointes:**<br /><a href="https://awa.tnext.loc/api/public/Capture-72677.JPG" target="_blank" >https://awa.tnext.loc/api/public/Capture-72677.JPG</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : non<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 2<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Johana VALLY jvally 244473 Manager<br /> **Détails du serveur**<br />Version DB: 4.44.3; Version Soft: v1.0.15-Beta; Version Back: v1.0.14-Beta<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0<br />Adresse du PC :10.24.103.93<br />

**Comment by lokkotara** [comment]
Le souci était causé par un problème de mise à jour des droits de certaines requêtes sur cet affichage. Le bug est résolu et sera appliqué à la v 16.

Cordialement,
