### ISSUE TITLE
id:206314 Erreur de couleurs Projets dans workload-dashboard

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#304]
<br /> **Affichage concerné**<br />workload-dashboard avec affichage par Projet<br /> <br /> **Décrivez le bug**<br />J'ai remarqué que l'affichage des superpositions des projets a un soucis sur les couleurs. Dans mon exemple, TGV2020 s'arretait en Mai23, et MPL16 commençait en Mai23. Par contre quand on affiche les 2 projets, la couleur de MPL16 passe de Rose à Rose/Vert<br />Cela crée une difficulté de comprendre comment est faite la charge<br /> <br /><br /><br />**Liste des pièces jointes:**<br /><a href="https://awa-dev.tnext.loc/api/public/TGV2020-741834.png" target="_blank" >https://awa-dev.tnext.loc/api/public/TGV2020-741834.png</a><br /><a href="https://awa-dev.tnext.loc/api/public/MPL16-29376.png" target="_blank" >https://awa-dev.tnext.loc/api/public/MPL16-29376.png</a><br /><a href="https://awa-dev.tnext.loc/api/public/2%20projets-866800.png" target="_blank" >https://awa-dev.tnext.loc/api/public/2%20projets-866800.png</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : oui<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 4<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Fabien GOY fgoy 206314 Manager<br /> **Détails du serveur**<br />Version DB: 4.45.1; Version Soft: v1.0.15-Beta-42-g9377ced; Version Back: v1.0.14-Beta-37-gce4b7ec<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36<br />Adresse du PC :10.24.101.208<br />

**Comment by lokkotara** [comment]
Cet effet indésirable est une mécanique interne de la librairie utilisée pour les graphs. La solution apportée a été de mettre l'opacité de chaque couleur à 100%. Ce changement sera disponible à partir de la v 16.

Cordialement,
