### ISSUE TITLE
id:244473 Bug dans l'import presta

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#305]
<br /> **Affichage concerné**<br />Import prestaire<br /> <br /> **Décrivez le bug**<br />Sur un fichier d'import avec 3 lignes, l'import est annoncé ok mais la charge n'est affecté qu'à une seule ligne<br /> <br /> **A reproduire**<br /> Les étapes permettant de reproduire le comportement indésirable :<br />1. Import Prestataires selon fichier execel joint<br />2. Affichage import OK (Cf. image1)<br />3. Vérification de l'import: Répartition charge/ Métier RAMS/ Ressource Presta LGM, recherche des 3 lignes<br />4. Toute la charge équivalente reportée sur une seule activité la deuxième SmCO3 (capture2)<br /><br />**Liste des pièces jointes:**<br /><a href="https://awa.tnext.loc/api/public/Actuals%20PrestaLGM%202403_test-184349.xlsx" target="_blank" >https://awa.tnext.loc/api/public/Actuals%20PrestaLGM%202403_test-184349.xlsx</a><br /><a href="https://awa.tnext.loc/api/public/Image1-654036.png" target="_blank" >https://awa.tnext.loc/api/public/Image1-654036.png</a><br /><a href="https://awa.tnext.loc/api/public/Capture2-88044.JPG" target="_blank" >https://awa.tnext.loc/api/public/Capture2-88044.JPG</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : non<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 2<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Johana VALLY jvally 244473 Manager<br /> **Détails du serveur**<br />Version DB: 4.44.3; Version Soft: v1.0.15-Beta; Version Back: v1.0.14-Beta<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0<br />Adresse du PC :10.243.98.3<br />

**Comment by lokkotara** [comment]
Il y avait effectivement un bug ne faisant pas remonter les actuals presta dans la modale des actuals (non visible sur les screenshots). Comme discuté ensemble, il y avait aussi une incompréhension avec le peuplement qui donnait l'impression que les actuals importés s'étaient directement répartis sur une ligne. Tout ceci a été reglé et sera disponible à partir de la v16.
