### ISSUE TITLE
id:244473 Besoin de clarifier le mode opératoire pour gérer les corrections de pointages déjà validés 

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#306]
<br />Avant déploiement de l'outil il faudra expliquer comment gérer les corrections de pointages déjà validés<br /><br />Ce qui arrive de temps en temps est de devoir corriger un pointage pour diverses raisons: <br />Le mode opératoire doit être clarifier<br />**Liste des pièces jointes:**<br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Type de demande d'évolution**<br />Type : ajout<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Johana VALLY jvally 244473 Manager<br /> **Détails du serveur**<br />Version DB: 4.44.3; Version Soft: v1.0.15-Beta; Version Back: v1.0.14-Beta<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0<br />Adresse du PC :10.243.98.3<br />

**Comment by lokkotara** [comment]
Une fonctionnalité pour corriger son dépensé jusqu'à 3 mois dans le passé a été ajouté dans l'appli. Il a été montré dans les diverses présentations pré-lancement comment effectuer cette correction. Cordialement,
