### ISSUE TITLE
id:206314 Inversion graphe Historique de charge

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#307]
<br /> **Affichage concerné**<br />Historique de charge<br /> <br /> **Décrivez la demande d'évolution**<br />Le graphe en bas de la page est à lire de gauche à droite, c'est assez perturbant. Il faudrait plutôt le mettre dans l'autre sens chronologique, comme tous les autres graphiques de l'application.<br />**Liste des pièces jointes:**<br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Type de demande d'évolution**<br />Type : modification<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Fabien GOY fgoy 206314 Manager<br /> **Détails du serveur**<br />Version DB: 4.46.2; Version Soft: v1.0.15-Beta-65-gf283e8c; Version Back: v1.0.14-Beta-57-g0d3c4f2<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36<br />Adresse du PC :10.22.108.171<br />

**Comment by lokkotara** [comment]
Le sens chronologique du tableau reste inchangé. Les premières lignes restent les lignes les plus récentes. Par contre, le graphique a été remis dans le même sens de lecture que sur les autres affichages (plus ancien à gauche et plus récent à droite). Je clôture donc ce ticket.

Cordialement,
