### ISSUE TITLE
id:244473 Taux horaires presta non correct

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#308]
<br /> A l'import d'activité de prestations, la correspondance € => h est faite avec un taux horaire de 60€<br /><br />Il faut que cette valeur soit modifiable ou en ligne avec le taux Alstom<br /><br />**Liste des pièces jointes:**<br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : non<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 2<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Johana VALLY jvally 244473 Manager<br /> **Détails du serveur**<br />Version DB: 4.47.2; Version Soft: v1.0.15-Beta-87-g55c13f9; Version Back: v1.0.14-Beta-65-g8969fd3<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0<br />Adresse du PC :10.243.98.2<br />

**Comment by lokkotara** [comment]
Les deux taux horaires que nous appliquons dans l'affichage "import des actuals" (30 et 60 €) ont été décidé par le Codep et ne sont pas prévu pour être modifiable.

Cordialement,
