### ISSUE TITLE
id:19997 Affectation plusieurs OTP sur une activité

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#314]
<br /> 		**Affichage concerné**<br /> 			Affectation OTP<br /> 		<br /> 		**Décrivez la demande d'évolution**<br /> 		Il faudrait pouvoir affecter plusieurs OTP sur une même activité<br /> 		<br /> 		**Informations complémentaires**<br /> 		Plusieurs personnes travaillent sur une même activité mais avec des OTP différents...<br /><br />**Liste des pièces jointes:**<br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Type de demande d'évolution**<br />Type : modification<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Vincent MICKIEWICZ vmickiew 19997 Manager<br /> **Détails du serveur**<br />Version DB: 4.47.3; Version Soft: v1.0.16-Beta; Version Back: v1.0.15-Beta<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0<br />Adresse du PC :10.24.101.156<br />

**Comment by lokkotara** [comment]
D'un point de vue technique, il n'est pas possible de répondre favorablement à cette demande de part l'architecture de notre base de données.

Cordialement,
