### ISSUE TITLE
id:19997 Affectation OTP : OTP introuvable dans la liste

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#315]
<br /> 		**Affichage concerné**<br /> 		Affectation OTP<br /> 		<br /> 		**Décrivez le bug**<br /> 		Sur le projet Aleas2, impossible d'affecter l'OTP PI-4930-0005A-112000M400 (qui existe bien...) sur une activité : cet OTP n'apparait dans la liste proposée.<br /> 		<br /> 		**A reproduire**<br /> 		Les étapes permettant de reproduire le comportement indésirable :<br /> 		1. Sur l'affichage '.Affectation OTP.', projet Aleas_2<br /> 		2. Je sélectionne une activité pour affecter un OTP<br /> 		3. La liste proposée ne contient pas l'OTP voulu<br /> 		4. L'erreur se reproduit<br /><br /> 		**Comportement attendu**<br /> 		Avoir accès à tous les OTP existants<br /> 		<br /> 		**Informations complémentaires**<br /> 		Ajoutez toutes autres informations qui permettraient une meilleure compréhension<br /><br />**Liste des pièces jointes:**<br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : oui<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 4<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Vincent MICKIEWICZ vmickiew 19997 Manager<br /> **Détails du serveur**<br />Version DB: 4.47.3; Version Soft: v1.0.16-Beta; Version Back: v1.0.15-Beta<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0<br />Adresse du PC :10.24.101.156<br />

**Comment by lokkotara** [comment]
La fenêtre additionnelle permettant d'afficher la liste des OTP a été modifié et permet maintenant de passer des de la liste des OTP présents sur le projet à la liste complète des OTP de l'appli. Après vérification sur la version v1.0.0, cet OTP s'affiche correctement dans la liste. Cordialement,
