### ISSUE TITLE
id:509974 connection avec matricule

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#316]
connexion avec l'ID impossible (509974)<br /><br />Contournement avec le user clearcase (frios)<br />**Liste des pièces jointes:**<br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : non<br />Contournement possible : oui<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 1<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Frédéric RIOS frios 509974 Manager<br /> **Détails du serveur**<br />Version DB: 4.47.3; Version Soft: v1.0.16-Beta; Version Back: v1.0.15-Beta<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0<br />Adresse du PC :10.24.103.22<br />

**Comment by lokkotara** [comment]
Il ne s'agit pas d'un bug mais bien du fonctionnement normal de l'authentification qui n'est pas propre à notre application. Pour éviter- ce souci, on a précisé depuis ces informations dans la vidéo tuto ainsi que lors des sessions de présentation de l'outil.

Cordialement,
