### ISSUE TITLE
id:20120 Configuration utilisateur non prise en compte

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#317]
<br /> J'ai paramétré mon affichage pour afficher ma répartition de la charge a l'ouverture mais quand je me connecte, c'est l'apercu de la charge qui est affiché<br /><br /> 		<br />**Liste des pièces jointes:**<br /><a href="https://awa.tnext.loc/api/public/Capture-6505.PNG" target="_blank" >https://awa.tnext.loc/api/public/Capture-6505.PNG</a><br /><a href="https://awa.tnext.loc/api/public/Capture2-28404.PNG" target="_blank" >https://awa.tnext.loc/api/public/Capture2-28404.PNG</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : non<br />Contournement possible : oui<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 1<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Michel BOYER mboyer 20120 User<br /> **Détails du serveur**<br />Version DB: 4.47.3; Version Soft: v1.0.16-Beta; Version Back: v1.0.15-Beta<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0<br />Adresse du PC :10.22.112.149<br />

**Comment by lokkotara** [comment]
Un problème d'autorisation pouvait être à l'origine de ce bug. Il a été corrigé depuis. Après avoir fait l'essai sur la version 1.0.0 (production), le comportement souhaité est obtenu. Je clos donc cet incident.
