### ISSUE TITLE
id:485538 Impossible de créer une nouvelle activité

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#320]
Après avoir sélectionné ma ressource (Mathieu BOUNHOURE) et avoir cliqué répartition de la charge --> répartir les actuals --> répartition auto, je me retrouve avec certaines activités qui ne sont pas pointées automatiquement. Du coup je clique sur le bouton "Ajouter une activité" mais rien ne se passe. Est-ce que c'est un bug ou est-ce que j'ai raté quelque chose ?<br /> 	<br /><br /><br />**Liste des pièces jointes:**<br /><a href="https://awa.tnext.loc/api/public/Capture-688556.JPG" target="_blank" >https://awa.tnext.loc/api/public/Capture-688556.JPG</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : non<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 2<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Mathieu BOUNHOURE mbounhou 485538 User<br /> **Détails du serveur**<br />Version DB: 4.47.3; Version Soft: v1.0.16-Beta; Version Back: v1.0.15-Beta<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0<br />Adresse du PC :10.22.106.235<br />

**Comment by lokkotara** [comment]
En effet, il s'agissait d'un problème d'autorisation de la requête. Le changement sera pris en compte à partir de la v1.0.0.

Cordialement,
