### ISSUE TITLE
id:244473 Non redisponibilisation d'une activité utilisée pour de la répartition automatique 

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#321]
<br /> 		**Affichage concerné**<br /> 		Répartion automatique / Répartir les actuals<br /> 		<br /> 		**Décrivez le bug**<br /> 		Si on utilise une répartion automatique , les ligne ne sont plus utilisables ultérieurement pour y réaffecter d'autres lignes de pointage (pour le cas d'une correction de FAKE par exemple)<br /> 		<br /> 		**A reproduire**<br />Filtre PreM / Rockys 		<br />Répartion automatique / Répartir les actuals<br />Clic sur répartition automatique<br />La première ligne de pointage OBES trouve l'affectation automatiquement (capture1)<br />Suppression des 7.4H de la 3eme ligne pour la placer sur la 2eme<br />Pour l'affectation du reste du pointage, les lignes qui ont été utilisée ou mise à zéro ne sont plus utilisables (capture2)<br /><br /> 		**Comportement attendu**<br />En conditions nominales cela ne devrait pas poser de problème car tout le pointage ne sera fait qu'avec la rémontée Alista 		<br />Mais pourrait poser problème avec la gestion des FAKE?<br /><br /> 		**Informations complémentaires**<br /> 		Ajoutez toutes autres informations qui permettraient une meilleure compréhension<br /><br />**Liste des pièces jointes:**<br /><a href="https://awa.tnext.loc/api/public/Capture1-284633.JPG" target="_blank" >https://awa.tnext.loc/api/public/Capture1-284633.JPG</a><br /><a href="https://awa.tnext.loc/api/public/Capture2-903158.JPG" target="_blank" >https://awa.tnext.loc/api/public/Capture2-903158.JPG</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : non<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 2<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Johana VALLY jvally 244473 Manager<br /> **Détails du serveur**<br />Version DB: 4.47.3; Version Soft: v1.0.16-Beta; Version Back: v1.0.15-Beta<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0<br />Adresse du PC :10.243.98.3<br />

**Comment by lokkotara** [comment]
En effet, les activités sur lesquelles on avaient réparties des heures ne redevenaient pas disponible après que l'on enlève les heures réparties dessus. Cela est corrigé et sera disponible à partir de la v1.0.2

Cordialement,
