### ISSUE TITLE
id:206314 Probleme import FdL

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#324]
<br /> 		**Affichage concerné**<br /> 		Apercu Charge<br /> 		<br /> 		**Décrivez le bug**<br /> 		Lors de l'import des FdL, il y a eu un bug. Des activités que j'avais fait avant 2020 sont apparues toutes en Mars22, voir capture d'écran<br /> 		<br /> 		<br />**Liste des pièces jointes:**<br /><a href="https://awa-dev.tnext.loc/api/public/Capture%20d%E2%80%99%C3%A9cran%202024-06-05%20093611-926029.png" target="_blank" >https://awa-dev.tnext.loc/api/public/Capture%20d%E2%80%99%C3%A9cran%202024-06-05%20093611-926029.png</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : non<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 2<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Fabien GOY fgoy 206314 Manager<br /> **Détails du serveur**<br />Version DB: 4.47.4; Version Soft: v1.0.16-Beta-2-ga831998; Version Back: v1.0.15-Beta<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36<br />Adresse du PC :10.24.103.55<br />

**Comment by lokkotara** [comment]
Ce n'est pas un bug d'import. Cela vient du fait que les FDL ont été prolongées et donc que l'historique a été perdu lors de la prolongation. Il ne reste qu'un total du mois précédent la fiche de lot.

Je clos donc ce ticket.
