### ISSUE TITLE
id:260184 Gestion des k€ matières

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#325]
Bonjour,<br /><br />Dans les fiches de lot, pour le sous métier MEIS de Traction Control, nous avions des lignes liés au k€ pour des achats externes et liés à la maintenance des simulateurs.<br /><br />Je vous mets 2 imprims écran d'exemple de la fiche de lot du projet FNM-HMU.<br /><br />Comment cela a-t-il été transformé dans AWA?<br /><br />Merci<br />Cordialement,<br />Sylvain<br /><br /><br />**Liste des pièces jointes:**<br /><a href="https://awa.tnext.loc/api/public/FdL_FNM_HMU_part1-340857.JPG" target="_blank" >https://awa.tnext.loc/api/public/FdL_FNM_HMU_part1-340857.JPG</a><br /><a href="https://awa.tnext.loc/api/public/FdL_FNM_HMU_part2-209464.JPG" target="_blank" >https://awa.tnext.loc/api/public/FdL_FNM_HMU_part2-209464.JPG</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : non<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 2<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Sylvain TASTET stastet 260184 User<br /> **Détails du serveur**<br />Version DB: 4.47.3; Version Soft: v1.0.16-Beta; Version Back: v1.0.15-Beta<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0<br />Adresse du PC :10.22.108.79<br />

**Comment by lokkotara** [comment]
Cela ne rentre pas dans le périmètre d’exécution de l'application. Cela doit être traité en dehors. Cordialement,
