### ISSUE TITLE
id:521415 Répartition des actuals. Conservation du delta projet pas simple

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#327]
<br /> 		**Affichage concerné**<br /> 		Dans la répartition des actuals.<br /> 		<br /> 		**Décrivez la demande d'évolution**<br />Lors de la répartition des actuals, si le spent déclaré ne correspond pas au forecast, l’écart se répercute sur le delta projet. Il est donc nécessaire de replanifier le forecast. Mais celà ne peut se faire que dans la vue "répartition de la charge".<br />==> Il faut donc se souvenir de tous les écarts pour les répercuter, ce n'est pas le plus simple surtout si le delta projet n'est pas 0.<br />A voir si on peut ajouter l'option de repercuter automatiquement l'ecart sur le forecast futur. <br />- En cas de dépassement : prendre les jours sur le (ou les 1ers) mois suivant ayant du forecast. Dégrader si pas assez ou pas du tout (avec un avertissement peut-etre)<br />- En cas de non consommation, ajouter le delta en forecast sur le mois n+1. <br /><br />	<br /> 		**Informations complémentaires**<br /> 		Ajoutez toutes autres informations qui permettraient une meilleure compréhension.<br /> 		N'hésitez pas à rajouter des schémas, organigrammes, dessins dans les fichiers joints.<br /><br />**Liste des pièces jointes:**<br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Type de demande d'évolution**<br />Type : ajout<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Jean-Yves RITZMANN 521415 521415 Manager<br /> **Détails du serveur**<br />Version DB: 4.47.3; Version Soft: v1.0.16-Beta; Version Back: v1.0.15-Beta<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0<br />Adresse du PC :10.24.100.32<br />

**Comment by dtisnegr** [comment]
L'option de reforecast automatique a été ajoutée, elle sera disponible dans la prochaine version.
Pour activer cette option il faudra aller dans les préférences utilisateurs et activer l'option de reforecast automatique.
Fonctionnement : s'il reste du forecast après avoir mis à jour son spent, le delta correspondant sera replanifié au dernier mois de l'activité ayant de la charge. S'il manque du forecast, ce delta sera pris en partant des derniers mois. S'il n'y a pas assez de forecast sur toute la ligne par rapport au spent renseigné, tout le forecast sera supprimé et l'activité apparaitra en dégradation.
Ainsi dans la plupart des cas, l'équilibre total activité et spent+forecast est préservé lors des mises à jour.
A noter : ce même fonctionnement s'applique quand on clique sur le bouton nettoyer (le forecast est automatiquement replanifié) et quand on change la répartition du spent entre plusieurs lignes d'activité depuis le tableau de répartition de la charge.
