### ISSUE TITLE
id:423920 Ajout activité dans la répartition des actuals non fonctionnel

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#329]
<br /> 		**Affichage concerné**<br /> 		Répartition des actuals<br /> 		<br /> 		**Décrivez le bug**<br /> 		Le bouton "Ajouter une activité" ne fonctionne pas. Quand on clique dessus, il ne crée pas de nouvelle ligne.<br /> 		<br /> 		**A reproduire**<br />1- Aller sur la répartition des actuals d'une personne<br />2- Sélectionner un actual à répartir<br />3- Cliquer sur "Plus de résultats"<br />4- Descendre tout en bas du menu déroulant<br />5- Cliquer sur "Ajouter une activité"<br /><br /> 		**Comportement attendu**<br /> 		Une nouvelle activité devrait se créer, ce n'est pas le cas.<br /> 		<br /> 		**Informations complémentaires**<br /> 		Même problème chez deux autres collègues. Même soucis qu'importe le rôle (User ou Manager). Le problème semble être généralisé et indépendant de la personne ou du compte.<br /><br />**Liste des pièces jointes:**<br /><a href="https://awa.tnext.loc/api/public/Capture%20d%E2%80%99%C3%A9cran%202024-06-06%20134417-176044.png" target="_blank" >https://awa.tnext.loc/api/public/Capture%20d%E2%80%99%C3%A9cran%202024-06-06%20134417-176044.png</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : oui<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 4<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Loic SAELINS lsaelin 423920 Manager<br /> **Détails du serveur**<br />Version DB: 4.47.3; Version Soft: v1.0.16-Beta; Version Back: v1.0.15-Beta<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0<br />Adresse du PC :10.24.103.223<br />

**Comment by lokkotara** [comment]
En effet, il manquait l'autorisation pour cette fonctionnalité. Cela a été ajouté dès à présent sur la version "bac à sable". Il sera aussi disponible à partir de la v 1.0.0.

Cordialement,
