### ISSUE TITLE
id:423920 Ressource manquante dans le listing

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#331]
<br /> 		**Affichage concerné**<br /> 		Tous<br /> 		<br /> 		**Décrivez le bug**<br /> 		La ressource "Merlin VISAGE" n’apparaît pas dans les filtres et est introuvable alors qu'il apparaissait dans les fiches de lot.<br /> 		<br /> 		**A reproduire**<br /> 		Essayer de filtrer sur cette ressource dans n'importe quel affichage<br /><br /> 		**Comportement attendu**<br /> 		Ressource disponible<br /> 		<br /> 		**Informations complémentaires**<br /> 		C'est bizarre car il était présent dans les FDLs. J'ai pensé que son statut d'alternant pouvait y être pour quelque chose mais j'ai trouvé un autre alternant dans les filtres donc ça ne semble pas être ça.<br /><br />**Liste des pièces jointes:**<br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : oui<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 4<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Loic SAELINS lsaelin 423920 Manager<br /> **Détails du serveur**<br />Version DB: 5.0.0; Version Soft: v1.0.0; Version Back: v1.0.0<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0<br />Adresse du PC :10.24.103.223<br />

**Comment by lokkotara** [comment]
La logique de filtrage ne prenait pas suffisamment de cas d'usage en compte comme une ressource temporairement absente ou une ressource pas encore présente. Cela a été corrigé en local et sera poussé prochainement. Je ne ferme pas de suite tant que je n'ai pas de date précise pour la sortie de ce correctif. Cordialement,

**Comment by lokkotara** [comment]
Le correctif est appliqué le 12/06/24 à partir de la v1.0.1
