### ISSUE TITLE
id:20120 en tant que responsable métier, je n'ai pas acces au menu gestion de ressource pour planifier ma charge

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#333]
<br /> 		Dans le menu principal<br />la gestion de ressource n'est pas dispo pour moi<br />je ne peux pas mettre mon nom en face des taches que je dois assurer (support responsable métier)<br />donc impossible de planifier la charge<br />**Liste des pièces jointes:**<br /><a href="https://awa.tnext.loc/api/public/Capture-618618.PNG" target="_blank" >https://awa.tnext.loc/api/public/Capture-618618.PNG</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : oui<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 4<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Michel BOYER mboyer 20120 User<br /> **Détails du serveur**<br />Version DB: 5.0.0; Version Soft: v1.0.0; Version Back: v1.0.0<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0<br />Adresse du PC :10.22.112.149<br />

**Comment by lokkotara** [comment]
Ce souci vient du fait d'ajouter une ressource sur une activité sans y affecter en même temps au moins une heure de charge. C'est un comportement voulu de l'application et se résout en affectant au moins une heure avant de valider.
Je clos donc ce ticket.
