### ISSUE TITLE
id:509974 Problème OTP

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#335]
bonjour,<br />lors de la répartition du pointage, 1 activité n'a pas réussi automatiquement à être affecter (OSTA).<br />J'ai selectionné à la main la FdL OSTA (N° OTP WBS Generic) bien rattaché au service RAMS<br /><br />Aprés avoir valider mon pointage, je me rend compte que le pointage sur OSTA est passé sur l'Activité PREM du TGV2020 (sur lequel je ne suis pas identifié)!!!!!!<br /><br /><br /><br />**Liste des pièces jointes:**<br /><a href="https://awa.tnext.loc/api/public/2024-06-11%2010_30_43-Bo%C3%AEte%20de%20r%C3%A9ception%20-%20frederic.rios%40alstomgroup.com%20-%20Outlook-440521.png" target="_blank" >https://awa.tnext.loc/api/public/2024-06-11%2010_30_43-Bo%C3%AEte%20de%20r%C3%A9ception%20-%20frederic.rios%40alstomgroup.com%20-%20Outlook-440521.png</a><br /><a href="https://awa.tnext.loc/api/public/2024-06-11%2010_31_17-Bo%C3%AEte%20de%20r%C3%A9ception%20-%20frederic.rios%40alstomgroup.com%20-%20Outlook-760832.png" target="_blank" >https://awa.tnext.loc/api/public/2024-06-11%2010_31_17-Bo%C3%AEte%20de%20r%C3%A9ception%20-%20frederic.rios%40alstomgroup.com%20-%20Outlook-760832.png</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : non<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 2<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Frédéric RIOS frios 509974 Manager<br /> **Détails du serveur**<br />Version DB: 5.0.0; Version Soft: v1.0.0; Version Back: v1.0.0<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0<br />Adresse du PC :10.24.101.49<br />

**Comment by lokkotara** [comment]
Merci d'avoir remonté ce bug qui aurait pu être très bloquant et toucher potentiellement toutes les ressources. En effet, le souci venait d'un souci sur la syntaxe de l'OTP générique. 

Cette syntaxe a été modifiée. De plus, la ligne créée sur le métier PrEM a été retirée et l'OTP qui avait été modifié sur l'activité "Intégration V0 big-datas" a été remis à sa précédente valeur.

Cordialement,
