### ISSUE TITLE
id:263833 Reporting du Spent

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#336]
Lorsqu'on fait "Répartir les actuals", il y a 2 cas de figures : <br />* OTP present dans la FdL, la répartition du spent est bien reportée dans l'onglet Répartition de la charge => OK pas de probleme<br />* OTP non present dans la FdL, il faut cliquer sur "Plus de résultats" pour mettre le spent mais dans ce cas là, le spent n'est pas reportée dans l'onglet Répartition de la charge => NOK probleme<br />**Liste des pièces jointes:**<br /><a href="https://awa.tnext.loc/api/public/Reporting%20spent-539336.docx" target="_blank" >https://awa.tnext.loc/api/public/Reporting%20spent-539336.docx</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : oui<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 4<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Alexandre ROUMAS aroumas 263833 User<br /> **Détails du serveur**<br />Version DB: 5.0.0; Version Soft: v1.0.0; Version Back: v1.0.0<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0<br />Adresse du PC :10.24.102.138<br />

**Comment by lokkotara** [comment]
Cela était provoqué par un effet de bord lorsque l'on répartissait son pointage sur une activité portant l'otp générique "WBS_generic". Cela a été corrigé le 11/06/24. Je clos donc le ticket
