### ISSUE TITLE
id:486723 Impossible de modifier le budget d'une activité

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#337]
<br /> 		**Affichage concerné**<br /> 		Répartition charge / Gestion budget<br /> 		<br /> 		**Décrivez le bug**<br /> 		J'ai un delta activité de -14.8j sur l'activité "rapport chute" du projet "22CBNG2 Lanzaderas". Je m'aperçois que le budget de cette activité n'a pas été exporté depuis la FdL. J'essais donc de màj le budget de l'activité mais l'outil ne le permet pas.<br /> 		<br /> 		**A reproduire**<br /> 		Les étapes permettant de reproduire le comportement indésirable :<br /> 		1. Sur l'affichage 'Gestion budget'<br /> 		2. Je clique sur 'RAMS/22CBNG2 Lanzaderas.'<br /> 		3. Je clique sur l'activité "rapport chute" pour modifier son budget<br /> 		4. la fenêtre pour modifier le budget ne s'affiche pas.<br /><br /> 		**Comportement attendu**<br /> 		Apparition de la fenêtre permettant de modifie le budget<br /> 		<br /> 		**Informations complémentaires**<br /> 		<br /><br />**Liste des pièces jointes:**<br /><a href="https://awa.tnext.loc/api/public/Pb%20activit%C3%A9%2022CB%20Lanzaderas-574035.docx" target="_blank" >https://awa.tnext.loc/api/public/Pb%20activit%C3%A9%2022CB%20Lanzaderas-574035.docx</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : non<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 2<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Juan BOTERO jbotero_ 486723 Manager<br /> **Détails du serveur**<br />Version DB: 5.0.0; Version Soft: v1.0.0; Version Back: v1.0.0<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0<br />Adresse du PC :10.22.112.151<br />

**Comment by lokkotara** [comment]
Comme vu ensemble le 14/06/24, cela n'était pas dû à un bug de l'application et nécessitait une démonstration de la fonctionnalité et une prise en main de l'outil. Je clos donc ce ticket.
