### ISSUE TITLE
id:486723 Budget gaps non remonté

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#338]
<br /> 		**Affichage concerné**<br /> 		Gestion budget<br /> 		<br /> 		**Décrivez le bug**<br /> 		Le budget prévu en gap 2, 3, 4,... des FdL n'a pas été remonté sur AWA<br /> 		<br /> 		**A reproduire**<br /> 		Les étapes permettant de reproduire le comportement indésirable :<br /> 		1. Sur l'affichage "Gestion budget/RAMS/22CBNG3 TRAXX"<br /> 		2. Je clique sur l'activité "RST clé en main..."<br /> 		3. Budget "0" alors que bien défini dans la FdL<br /> 		4. Impossible d'affecter un budget<br /><br /> 		**Comportement attendu**<br /> 		Que le budget de la FdL soit pris en compte, sinon de pouvoir le mettre à jour<br /> 		<br /> 		<br /><br />**Liste des pièces jointes:**<br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : oui<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 4<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Juan BOTERO jbotero_ 486723 Manager<br /> **Détails du serveur**<br />Version DB: 5.0.0; Version Soft: v1.0.0; Version Back: v1.0.0<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0<br />Adresse du PC :10.22.112.151<br />

**Comment by lokkotara** [comment]
Concerne la même chose que la réponse apportée au ticket concernant l'affectation de budget dans l'appli. 

Cordialement,
