### ISSUE TITLE
id:486723 Affectation à activité erronée

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#339]
<br /> 		**Affichage concerné**<br /> 		Charge/répartition charge<br /> 		<br /> 		**Décrivez le bug**<br /> 		Je ne sais pas pourquoi je suis affecté à l'activité "Locos Madhepura"<br /> 		<br /> 		**A reproduire**<br /> 		Les étapes permettant de reproduire le comportement indésirable :<br /> 		1. Sur l'affichage "Charge/répartition charge"<br /> 	 	2. Je descend jusqu'à l'activité "Locos Madhepura"<br /> 		3. Je ne connais pas cette activité<br /><br /> 		**Comportement attendu**<br /> 		Non affichage de l'activité<br /> 		<br /> 		<br /><br />**Liste des pièces jointes:**<br /><a href="https://awa.tnext.loc/api/public/Pb%20activit%C3%A9%20Locos%20Madhepura-959942.docx" target="_blank" >https://awa.tnext.loc/api/public/Pb%20activit%C3%A9%20Locos%20Madhepura-959942.docx</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : non<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 2<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Juan BOTERO jbotero_ 486723 Manager<br /> **Détails du serveur**<br />Version DB: 5.0.0; Version Soft: v1.0.0; Version Back: v1.0.0<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0<br />Adresse du PC :10.22.112.151<br />

**Comment by lokkotara** [comment]
Cela était dû à un effet de bord lorsque l'on répartissait le pointage sur une activité portant l'otp générique "WBS_generic". Cela a été corrigé le 12/06/24. Vous pouvez dès à présent répartir ce pointage (il est de nouveau disponible dans la fenêtre additionnelle "répartir les actuals") sur la bonne activité. Je laisse encore temporairement ce ticket ouvert jusqu'à ce que vous ayez pu tester que cela fonctionnait de nouveau comme attendu.
