### ISSUE TITLE
id:244473 Incoéhrence entre affichage Affectation ressource et affichage Répartion charge

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#340]
<br /> 		**Affichage concerné**<br /> 		Erreur a priori sur affichage affectation ressource<br /> 		<br /> 		**Décrivez le bug**<br /> 		La réaffectation d'une activité sur l'affichage Réparttion Charge semble mal prise en compte dans l'affichage Affectation ressource<br /> 		<br /> 		**A reproduire**<br /> Connection sous RAMS/ MF19 Armoires <br />Vue Répartion charge<br />Correction de forecast dans passé et réaffectation de la charge en prévisionnel<br />Affichage corecte de la charge Cf Capture 1<br />Ouverture de la vue Plannification Cf Capture 2<br />La charge n'est plus cohérente entre les 2 affichages (elle l'était avant la manip de répartition de charge)<br /><br /><br />**Liste des pièces jointes:**<br /><a href="https://awa.tnext.loc/api/public/capture1-569255.JPG" target="_blank" >https://awa.tnext.loc/api/public/capture1-569255.JPG</a><br /><a href="https://awa.tnext.loc/api/public/Capture2-697737.JPG" target="_blank" >https://awa.tnext.loc/api/public/Capture2-697737.JPG</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : non<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 2<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Johana VALLY jvally 244473 Manager<br /> **Détails du serveur**<br />Version DB: 5.0.0; Version Soft: v1.0.0; Version Back: v1.0.0<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0<br />Adresse du PC :10.22.112.114<br />

**Comment by lokkotara** [comment]
Cette modification a été effectuée et est disponible à partir de la v1.0.1. Je clos donc ce ticket.
