### ISSUE TITLE
id:244473 Erreur d'import des gap BGLR

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#341]
<br /> 		**Affichage concerné**<br /> 		Pas un prb d'affichage mais problème peut être vu sous Planification des ressources / RAMS / Loco KZ6A (offre)<br /> 		<br /> 		**Décrivez le bug**<br /> A l'import des FDL sous AWA, les GAP BGLR pour le chiffrage BGLR ont été importé dans l'outil de charge<br />AWA : Capture 1 => il resterait 4440H à planifier<br />FdL : Capture 2 et 3 => cela  correspondait à la charge que BGLR devra exécuter<br /> 		<br /> 		**Comportement attendu**<br />A priori comme c'est un outil de charge TRB, il faudrait faire disparaître cette charge qui n'est pas à planifier à TRB<br />Mais quelque soit la décision il faudrait communiquer clairement aux métiers ce qui'ils doivent faire<br /> 		<br /> <br />**Liste des pièces jointes:**<br /><a href="https://awa.tnext.loc/api/public/capture1-517970.JPG" target="_blank" >https://awa.tnext.loc/api/public/capture1-517970.JPG</a><br /><a href="https://awa.tnext.loc/api/public/Capture2-511465.JPG" target="_blank" >https://awa.tnext.loc/api/public/Capture2-511465.JPG</a><br /><a href="https://awa.tnext.loc/api/public/Capture3-978420.JPG" target="_blank" >https://awa.tnext.loc/api/public/Capture3-978420.JPG</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : non<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 2<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Johana VALLY jvally 244473 Manager<br /> **Détails du serveur**<br />Version DB: 5.0.0; Version Soft: v1.0.0; Version Back: v1.0.0<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0<br />Adresse du PC :10.22.112.114<br />

**Comment by lokkotara** [comment]
Bonjour. En effet, tous les gaps présents dans les fiches de lots ont été importés sans prendre en compte s'ils étaient actifs ou non.
Cela nécessite donc de modifier manuellement dans l'appli les gaps que l'on ne souhaite pas prendre en compte dans le total du budget. Ce changement sera effectif à partir de la v1.0.2 qui devrait arriver dans les prochains jours. 

Cordialement,
