### ISSUE TITLE
id:198746 Gestion de projet: ajout métier à 1 projet impossible

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#342]
<br /> 		**Affichage concerné**<br /> 		Gestion de projet: <br /> 		<br /> 		**Décrivez le bug**<br /> 		Impossible d'ajouter un métier à 1 projet donné. <br /> 		<br /> 		**A reproduire**<br /> 		je choisi le projet septa electrobox,<br />je cherche à ajouter les métier Management Wiring TD et S&A Traction<br />je sélectionne ces 2 métiers,<br />au moment de cliquer sur valider les changements, rien ne se passe et les cases sont désélectionnées  <br /><br /> 		**Comportement attendu**<br /> 		les 2 métiers auraient dû être ajouté au métier<br /> 		<br /> 		**Informations complémentaires**<br /> 		comportement similaire avec un autre compte Adrien ENGEL rôle manager et Daniel Dupuy role admin<br /><br />**Liste des pièces jointes:**<br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : oui<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 4<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Adrien ENGEL aengel 198746 Manager<br /> **Détails du serveur**<br />Version DB: 5.0.0; Version Soft: v1.0.0; Version Back: v1.0.0<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0<br />Adresse du PC :10.22.106.244<br />

**Comment by lokkotara** [comment]
Une erreur dans la syntaxe de l'otp générique fait échouer la requête pour ajouter les métiers sur le projet. 

Les changements ont été fait localement et devrait être poussés aujourd'hui ou demain sur la version de production. 

Je laisse donc pour le moment le ticket ouvert jusque là.

Cordialement,

**Comment by lokkotara** [comment]
Les changements seront effectifs le 12/06/24 à partir de la v1.0.1
