### ISSUE TITLE
id:244473 Liste OTP non à jour 

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#343]
<br /> 		**Affichage concerné**<br /> 	Affectation OTP Projet<br /> 		<br /> 		**Décrivez le bug**<br />Besoin d'affecter un OTP selon consigne du PreM N06 du 14/05/06<br /> 		<br /> 		**A reproduire**<br />Ouvrir Affectation OTP Projet, séleciton RAMS projet N06<br />REcherche OTP fourni par PreM (capture 1)<br />=> OTP non dispo (capture 2)<br /><br />**Liste des pièces jointes:**<br /><a href="https://awa.tnext.loc/api/public/capture1-345190.JPG" target="_blank" >https://awa.tnext.loc/api/public/capture1-345190.JPG</a><br /><a href="https://awa.tnext.loc/api/public/Capture2-558355.JPG" target="_blank" >https://awa.tnext.loc/api/public/Capture2-558355.JPG</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : non<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 2<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Johana VALLY jvally 244473 Manager<br /> **Détails du serveur**<br />Version DB: 5.0.0; Version Soft: v1.0.0; Version Back: v1.0.0<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0<br />Adresse du PC :10.22.112.114<br />

**Comment by lokkotara** [comment]
Bonjour Johana,

Malheureusement, à l'heure actuelle, il nous a été impossible d'obtenir une transaction pour un import de nouveaux OTP dans l'appli.
Il revient donc à chacune.chacun (ayant le rôle manager) de créer les OTP nécessaires dans l'affichage prévu à cet effet (Gestion des OTP).

Nous savons que ce n'est pas l'idéal mais ne pouvons pas faire mieux avec les autorisations que nous avons.

Cordialement,
