### ISSUE TITLE
id:244473 Impossibilité de création de nouvel OTP de plus de 23 caractères

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#344]
<br /> 		**Affichage concerné**<br />Gestion des OTP<br /> 		<br /> 		**Décrivez le bug**<br />Pas de possibilité de créer le nouvel OTP PN-4930-9028B-PWTDAD700A<br /> 		<br /> 		**A reproduire**<br />Fenetre Gestion de OTP<br />Tentative création nouvel OTP  pour RAMS N06 : PN-4930-9028B-PWTDAD700A<br />Jusqu'à la saisie des caractères "PN-4930-9028B-PWTDAD700" il y a toujours le possibilité de CREER l'OTP (Cf Capture1)<br />A la saisie du dernier caractère la fenêtre se modifie , on ne peux que modifier l'OTP (Capture2)<br />La tentative de rentrer à nouveau le même OTP dans la sasie de modif et de cliquer sur Modifier OTP ne permet pas de créer l'OTP<br /><br /> 		**Comportement attendu**<br /> 		Une description précise et concise du comportement attendu<br /> 		<br /> 		**Informations complémentaires**<br /> 		Ajoutez toutes autres informations qui permettraient une meilleure compréhension<br /><br />**Liste des pièces jointes:**<br /><a href="https://awa.tnext.loc/api/public/Capture1-410279.JPG" target="_blank" >https://awa.tnext.loc/api/public/Capture1-410279.JPG</a><br /><a href="https://awa.tnext.loc/api/public/Capture2-248673.JPG" target="_blank" >https://awa.tnext.loc/api/public/Capture2-248673.JPG</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : non<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 2<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Johana VALLY jvally 244473 Manager<br /> **Détails du serveur**<br />Version DB: 5.0.0; Version Soft: v1.0.0; Version Back: v1.0.0<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0<br />Adresse du PC :10.22.112.114<br />

**Comment by lokkotara** [comment]
Une amélioration de cet affichage va être mis en place très prochainement pour garantir une facilité d'utilisation. Cordialement,
