### ISSUE TITLE
id:423920 Ressource manquante

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#345]
<br /> 		**Affichage concerné**<br /> 		Répartition de la charge<br /> 		<br /> 		**Décrivez le bug**<br /> 		La ressource "Nicolas ARNAULT" n'apparait pas dans les filtres de la répartition de la charge.<br />La ressource est accessible via filtre sur l'aperçu de la charge mais pas sur la répartition de la charge.<br />Sa capacité n'est pas nulle dans le passé, mais il est bizarre qu'elle soit à 0 sur le métier Design Leader Traction.<br /> 		<br /> 		**A reproduire**<br /> 		Faire une recherche par filtre sur la répartition de la charge<br /><br /> 		**Comportement attendu**<br /> 		Ressource disponible dans le filtre.<br /> 		<br /> 		**Informations complémentaires**<br /> 		La ressource n'était pas active. Je l'ai réactivé mais ça n'a pas changé le problème.<br />Il a bien de la charge prévisionnelle dans le futur.<br /><br />La bascule AWA coïncide avec sa prise de poste ailleurs à Alstom, il a pu se passer un changement de statut un peu hattif ?<br /><br />**Liste des pièces jointes:**<br /><a href="https://awa.tnext.loc/api/public/Capture%20d%E2%80%99%C3%A9cran%202024-06-13%20085950-57572.png" target="_blank" >https://awa.tnext.loc/api/public/Capture%20d%E2%80%99%C3%A9cran%202024-06-13%20085950-57572.png</a><br /><a href="https://awa.tnext.loc/api/public/Capture%20d%E2%80%99%C3%A9cran%202024-06-13%20085619-214185.png" target="_blank" >https://awa.tnext.loc/api/public/Capture%20d%E2%80%99%C3%A9cran%202024-06-13%20085619-214185.png</a><br /><a href="https://awa.tnext.loc/api/public/Capture%20d%E2%80%99%C3%A9cran%202024-06-13%20085113-442245.png" target="_blank" >https://awa.tnext.loc/api/public/Capture%20d%E2%80%99%C3%A9cran%202024-06-13%20085113-442245.png</a><br /><a href="https://awa.tnext.loc/api/public/Capture%20d%E2%80%99%C3%A9cran%202024-06-13%20085041-916143.png" target="_blank" >https://awa.tnext.loc/api/public/Capture%20d%E2%80%99%C3%A9cran%202024-06-13%20085041-916143.png</a><br /><a href="https://awa.tnext.loc/api/public/Capture%20d%E2%80%99%C3%A9cran%202024-06-13%20084945-950959.png" target="_blank" >https://awa.tnext.loc/api/public/Capture%20d%E2%80%99%C3%A9cran%202024-06-13%20084945-950959.png</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : oui<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 4<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Loic SAELINS lsaelin 423920 Manager<br /> **Détails du serveur**<br />Version DB: 5.0.0; Version Soft: v1.0.1; Version Back: v1.0.1<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0<br />Adresse du PC :10.24.102.106<br />

**Comment by lokkotara** [comment]
Ce problème avait été résolu lors d'un ticket précédent mais le changement de code n'avait pas été poussé correctement dans l'application. Cela sera réglé à partir de la v1.0.2 qui devrait arriver d'ici quelques jours. Cordialement,
