### ISSUE TITLE
id:238244 Un nom n'apparaît pas dans la liste

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#346]
<br /> 		**Affichage concerné**<br /> 		Précisez l'affichage concerné. Utilisez 'multi-affichages' si l'issue concerne plus d'un affichage<br /> 		<br />Charge/Répartition charge/Filtres<br />Multi-affichage : je ne sais pas<br /><br /> 		**Décrivez le bug**<br /> 		Une description concise et précise du bug<br /><br />Dans le filtre des ressources, mon intérimaire SANTORO Mathieu n'apparaît pas, ni dans la recherche, ni dans la liste.<br />Pourtant, j'ai reçu à l'avoir dans ma répartition des actuals lorsque j'ai sélectionné tout mon métier (TD/Mechanical - Traction).<br /> 		<br /> 		**A reproduire**<br /> 		Les étapes permettant de reproduire le comportement indésirable :<br /> 		1. Sur l'affichage 'Charge/Répartition charge/Filtres'<br /> 		2. Je clique sur 'Ressources'<br /> 		3. Soit je tape le début du nom ou je descends dans le tableau, SANTORO n'est pas présent.'<br /> 		4. L'erreur se reproduit<br /><br /> 		**Comportement attendu**<br /> 		Une description précise et concise du comportement attendu<br /> 		<br /> 		**Informations complémentaires**<br /> 		Ajoutez toutes autres informations qui permettraient une meilleure compréhension<br /><br />**Liste des pièces jointes:**<br /><a href="https://awa.tnext.loc/api/public/AWA_2-901877.JPG" target="_blank" >https://awa.tnext.loc/api/public/AWA_2-901877.JPG</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : non<br />Contournement possible : oui<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 1<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :François TERRIEN fterrien 238244 Manager<br /> **Détails du serveur**<br />Version DB: 5.0.0; Version Soft: v1.0.1; Version Back: v1.0.1<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0<br />Adresse du PC :10.243.98.3<br />

**Comment by lokkotara** [comment]
Ce problème avait été résolu lors d'un ticket précédent mais le changement de code n'avait pas été poussé correctement dans l'application. Cela sera réglé à partir de la v1.0.2 qui devrait arriver d'ici quelques jours. Cordialement,
