### ISSUE TITLE
id:493742 Charge en fin de FdL

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#347]
Bonjour,<br /><br />Dans les fiches de lot, la charge qui n'est pas planifiée est mise en fin de fiche de lot.<br />Dans l'exemple ci-joint, plusieurs jours sont indiqués dans la case > avr - 27. Cette charge n'apparait pas dans l'outil AWA, est-ce normal ?<br /><br />Cordialement,<br /><br />Hadi<br /><br />**Liste des pièces jointes:**<br /><a href="https://awa.tnext.loc/api/public/Capture_charge_NT77-846605.JPG" target="_blank" >https://awa.tnext.loc/api/public/Capture_charge_NT77-846605.JPG</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Type de demande d'évolution**<br />Type : ajout<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Hadi TARTOUSSI 493742 493742 Manager<br /> **Détails du serveur**<br />Version DB: 5.0.0; Version Soft: v1.0.1; Version Back: v1.0.1<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0<br />Adresse du PC :10.24.101.149<br />

**Comment by lokkotara** [comment]
Bonjour,

Il est normal de ne pas retrouver ces valeurs dans l'application. En effet , après décision du CODEP, il a été décidé de ne pas l'importer.
On retrouve la valeur totale sous forme de delta et c'est à la charge des ressources de replanifier ce qui est nécessaire.

Cordialement,
