### ISSUE TITLE
id:403133 reforecast automatique

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#351]
<br /> 		**Affichage concerné**<br /> 		répartition de la charge.<br /> 		<br /> 		**Décrivez la demande d'évolution**<br /> 		avoir la possibilité d'activer le reforecast automatique lors du spent. S'il y a plus de spent que de forecast, prendre le forecast nécessaire sur plusieurs mois si possible sinon dégradation. S'il y a moins de spent que de forecast, replanifier le forecast restant.<br /> 		<br /> 		**Informations complémentaires**<br /> 		Fonctionnalité existante dans flup, voir pour les règles à appliquer pour le reforecast (mois suivant, dernier mois d'activité, ... ?). De plus, dans flup, quand il n'y a plus de forecast disponible pour la ressource, s'il y en a sur d'autres ressources de la même activité, ça propose de prendre du forecast chez les autres. On est libre de choisir de le faire ou non et de choisir la ressource chez qui on le prend. Cette proposition se fait tant qu'il manque du forecast. Ex: il manque 20h pour la ressource 1, je peux prendre les 10h qu'il y a sur la ressource 2, puis les 5h qu'il y a sur la ressource 3 et ensuite je dégrade.<br /><br />**Liste des pièces jointes:**<br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Type de demande d'évolution**<br />Type : ajout<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Damien TISNÉ-GRIMAUD e_dtisne 403133 Admin<br /> **Détails du serveur**<br />Version DB: 5.0.0; Version Soft: v1.0.1; Version Back: v1.0.1<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0<br />Adresse du PC :10.243.98.2<br />

**Comment by dtisnegr** [comment]
Fait mais que pour le scope de la ressource. 
c'est à dire qu'on ne va pas prendre des heures sur les autres ressources présentes sur l'activité. Cette action est à faire manuellement pour rééquilibrer le budget
