### ISSUE TITLE
id:480245 Ressource TIYO

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#354]
<br /> 		**Affichage concerné**<br /> 		Ressource --> Capacité<br /> 		<br /> 		**Décrivez le bug**<br /> 		Je ne trouve pas la ressource TIYO dans les ressource à ajouter<br /> 		<br /> 		**A reproduire**<br /> 		NA<br /><br /> 		**Comportement attendu**<br /> 		NA<br /> 		<br /> 		**Informations complémentaires**<br /> 		Je souhaites rajouter la ressource dans l'équipe Validation systeme traction<br /><br />**Liste des pièces jointes:**<br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : oui<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 4<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Davy BONNASSIES 480245 480245 Manager<br /> **Détails du serveur**<br />Version DB: 5.0.0; Version Soft: v1.0.1; Version Back: v1.0.1<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0<br />Adresse du PC :10.24.100.96<br />

**Comment by lokkotara** [comment]
La ressource presta-TIYO est inactive dans l'application, donc elle ne remonte pas dans l'affichage. Cependant un effet de bord empêche l’exécution de la requête pour la modification de son statut (inactif -> actif). Il est corrigé et sera disponible à partir de la v1.0.2
