### ISSUE TITLE
id:198746 Impossibilité de gérer ressource multi métier

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#355]
<br />Dans la visu gestion de la capacité des ressources: <br />Ressource PRESTA AKKODIS FGI paramétrée sur 2 métiers<br />était 100% "EHI Traction", au chargement de la base<br />j'ai ajouté le métier "S&A Traction"<br /> <br />Lors de l’ajout à une activité dans planification des ressources<br />Ex : ici projet Electrobox SEPTA<br />Ressource PRESTA AKKODIS FGI non présente dans la liste pour une activité S&A Traction<br /> <br /><br />**Liste des pièces jointes:**<br /><a href="https://awa.tnext.loc/api/public/ticket%20ressource%20multi%20m%C3%A9tier-186940.docx" target="_blank" >https://awa.tnext.loc/api/public/ticket%20ressource%20multi%20m%C3%A9tier-186940.docx</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : oui<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 4<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Adrien ENGEL aengel 198746 Manager<br /> **Détails du serveur**<br />Version DB: 5.0.0; Version Soft: v1.0.1; Version Back: v1.0.1<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0<br />Adresse du PC :10.22.106.244<br />

**Comment by lokkotara** [comment]
La requête permettant de récupérer correctement les ressources a été mise à jour dans l'affichage "Planification des ressources" et sera disponible à partir de la v1.0.2. Cordialement,
