### ISSUE TITLE
id:200959906 Gestion des projets : la liste des projets n'est pas classée par type de projet

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#356]
<br /> 		**Affichage concerné**<br /> 		Gestion des projets<br /> 		<br /> 		**Décrivez le bug**<br /> 		Le tri des projets n'est pas appliqué lorsque l'on ouvre la vue Gestion des projets. Il apparaît uniquement lors d'une nouvelle recherche<br /> 		<br /> 		**A reproduire**<br /> 		Les étapes permettant de reproduire le comportement indésirable :<br /> 		1. Sur l'affichage 'Gestion des projets'<br /> 		2. Les projets sont triés par ordre alphabétique uniquement<br /> 		3. On choisit un premier projet<br /> 		4. Lorsque l'on clique sur "Nouveau projet" la liste est trié par type de projets (ferme, extra, forecast, R&D prévisionnel)<br /><br /> 		**Comportement attendu**<br /> 		Le tri des projets doit être présent lorsque l'on clique sur la vue Gestion des projets<br /><br />**Liste des pièces jointes:**<br /><a href="https://awa.tnext.loc/api/public/Filtre%20initial%20gestion%20des%20projets-155771.JPG" target="_blank" >https://awa.tnext.loc/api/public/Filtre%20initial%20gestion%20des%20projets-155771.JPG</a><br /><a href="https://awa.tnext.loc/api/public/Filtre%20nouvelle%20recherche%20Gestion%20des%20projets-216448.JPG" target="_blank" >https://awa.tnext.loc/api/public/Filtre%20nouvelle%20recherche%20Gestion%20des%20projets-216448.JPG</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : oui<br />Contournement possible : oui<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 3<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Daniel DUPUY e_ddupuy 200959906 Admin<br /> **Détails du serveur**<br />Version DB: 5.0.0; Version Soft: v1.0.1; Version Back: v1.0.1<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0<br />Adresse du PC :10.24.103.30<br />

**Comment by lokkotara** [comment]
Cet effet de bord était aussi présent sur l'affichage "Tableau de bord des projets" et venait d'un booléen pour trier sur filterable-list qui n'était pas renseigné. Le changement sera visible à partir de la v1.0.2
