### ISSUE TITLE
id:174744 Supprimer Générique

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#358]
Supprimer générique sur une activité quand une ressource est affectée pour éviter de surcharger le tableau.<br /><br />**Liste des pièces jointes:**<br /><a href="https://awa.tnext.loc/api/public/Suppression%20G%C3%A9n%C3%A9rique-291356.JPG" target="_blank" >https://awa.tnext.loc/api/public/Suppression%20G%C3%A9n%C3%A9rique-291356.JPG</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Type de demande d'évolution**<br />Type : ajout<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Guillaume MUR gmur 174744 Manager<br /> **Détails du serveur**<br />Version DB: 5.0.0; Version Soft: v1.0.1; Version Back: v1.0.1<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0<br />Adresse du PC :10.24.101.120<br />

**Comment by lokkotara** [comment]
La ligne générique sans planification est une fonctionnalité propre à l'affichage "Planification des ressources" . Cela répond à plusieurs besoins, en phase offre comme en phase projet (primo-planification, transfert de charge d'une ressource vers le générique, nouvelle planification, etc...). Il n'est donc pas prévu de retirer la ligne générique sur les activités.
