### ISSUE TITLE
id:238244 Incohérence de fonctionnement

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#365]
<br /> 		**Affichage concerné**<br /> 		Charge/Répartition charge<br /> 		<br /> 		**Décrivez le bug**<br /> 		Après avoir repartis mes actuals, il reste une activité avec du forecast sur le mois passé. Je veux décaler ce forecast sur le mois en cours.<br />J'obtiens un comportement différent suivant l'ordre de la séquence suivi ==> Cf. ppt joint.<br /><br />A noter que le forecast nettoyé (donc retiré) apparaît avec un signe "+" qui n'est pas cohérent avec l'ajout d'une charge qui apparaît elle aussi avec une signe "+".<br /> 		<br /> 		**A reproduire**<br /> 		Voir ppt.<br /><br /> 		**Comportement attendu**<br /> 		Même comportement dans les deux séquences, avec un 0 final en EAV.<br /> 		<br /> 		**Informations complémentaires**<br /> 		NA<br /><br />**Liste des pièces jointes:**<br /><a href="https://awa.tnext.loc/api/public/AWA_incoh%C3%A9rence%20fonctionnement-280164.pptx" target="_blank" >https://awa.tnext.loc/api/public/AWA_incoh%C3%A9rence%20fonctionnement-280164.pptx</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : oui<br />Contournement possible : oui<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 3<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :François TERRIEN fterrien 238244 Manager<br /> **Détails du serveur**<br />Version DB: 5.0.0; Version Soft: v1.0.1; Version Back: v1.0.1<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0<br />Adresse du PC :10.24.103.182<br />

**Comment by lokkotara** [comment]
En effet, le nettoyage du forecast dans le passé entraînait un comportement non désiré en ajoutant sa valeur à la colonne EAV (au lieu de le soustraire). Cela a été corrigé et sera disponible à partir de la v1.0.2.

Cordialement,
