### ISSUE TITLE
id:471595 Activité non remontée de la FdL initiale

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#366]
Bonjour, <br /><br />Il y a une activité (TrVE) qui ne s'est pas transférée de ma fiche de lot NT77_TRC vers AWA. J'ai donc rajouté cette ligne dans les gaps, mais je ne suis pas en mesure d'ajouter le pointage qui avait déjà été effectué jusqu'à présent.<br /><br />Avez vous une solution pour pointer dans le passé par exemple?<br />**Liste des pièces jointes:**<br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : non<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 2<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Olivier RICHARD orichard 471595 Manager<br /> **Détails du serveur**<br />Version DB: 5.0.0; Version Soft: v1.0.1; Version Back: v1.0.1<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0<br />Adresse du PC :10.24.102.205<br />

**Comment by lokkotara** [comment]
L'activité correspondante avait bien été poussé dans l'application, seulement elle se trouvait sur un nouveau métier dans AWA (TrVE). Je clos donc le ticket
