### ISSUE TITLE
id:20105 impossible d'effectuer les actuals pour la réessource PRESTA CAP GEMINI

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#367]
<br /> 		**Affichage concerné**<br /> 		répartition charge / actuals<br /><br /> 		<br /> 		**Décrivez le bug**<br /> 		lors des actuals, AWA me propose de valider un pointage qui ne correspond pas à l'activité de notre prestataire ( qui est PRESTA CAPGEMINI WWW, mais pour lequel je n avais pas mis de capacité). Je suppose que ca concerne des projets d'autre métier car non presta CAPGEMINI déjà utilisé ( valid copo, Ctr Cde)<br /><br />j ai prévu d'effectuer les changement de ressource PRESTA CAPGEMINI => PRESTA CAPGEMINI WWW mais à faire apres  les actueal sont OK<br /> 		<br /> 		*merci<br />Philippe JALBY<br /><br />**Liste des pièces jointes:**<br /><a href="https://awa.tnext.loc/api/public/pb%20actual%20prest%20CAP%20G-852558.PNG" target="_blank" >https://awa.tnext.loc/api/public/pb%20actual%20prest%20CAP%20G-852558.PNG</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : oui<br />Contournement possible : oui<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 3<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Philippe JALBY pjalby 20105 Manager<br /> **Détails du serveur**<br />Version DB: 5.0.0; Version Soft: v1.0.1; Version Back: v1.0.1<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0<br />Adresse du PC :10.24.101.3<br />

**Comment by lokkotara** [comment]
En effet, la charge prévue sur "prestaWW" dans les FdL avait été imputée à la ressource "presta capgemini" au lieu de la ressource "presta capgemini www".  Cela a été corrigé le 25/06/2024 et permet dès à présent de pouvoir répartir les pointages sur la bonne ressource. Cordialement,
