### ISSUE TITLE
id:172975 Manque ressource management/expertise pour Control command

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#369]
<br /> 		**Affichage concerné**<br /> 		Répartition Charge/ Aperçu de la charge<br /> 		<br /> 		**Décrivez le bug**<br /> Je n'ai pas la ressource management-expertise (dans Control/command) ce qui fait que je ne peux pas mettre à jour la charge. (Répartition charge, exemple avec le projet Control Box ESU)<br />Egalement je ne peux pas visualiser la charge de cette ressource (comme elle n'existe pas) dans Aperçu de la charge.<br /> 		<br /> Il faudrait ajouter cette ressource qui est utilisée comme la ressource générique.<br />Je pense pouvoir ajouter cette ressource mais comme elle existe déjà dans les projets, je préfère voir avec vous avant.<br /><br />Merci<br />**Liste des pièces jointes:**<br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : oui<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 4<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Fabien DEHOURS fdehours 172975 Manager<br /> **Détails du serveur**<br />Version DB: 5.0.0; Version Soft: v1.0.2; Version Back: v1.0.2<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0<br />Adresse du PC :10.24.102.99<br />

**Comment by lokkotara** [comment]
Les ressources "management/expertise" et "relecteur/vérificateur" n'ont pas été décelées avant et ont été poussées en l'état dans la nouvelle appli. Seulement, il n'a pas été prévu d'autres ressources génériques autre que "ressource générique". Il faudrait gérer la capa de la ressource etc.. Donc après discussion ensemble le 25/06/24, je vais transférer toute la charge des ressources "management/expertise" et "relecteur/vérificateur" sur la ressource "générique". Pour les métiers, tout ce qui était à management/expertise sera mis sur le métier management - expertise et tout ce qui était relecteur/vérificateur sera mis sur le métier control/command. 

Je ne fermerai ce ticket qu'après avoir vérifié que les changements vous convenait. Cordialement,
