### ISSUE TITLE
id:164094 Même n° OTP pour tous les métiers dans projet ICNG Germany

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#370]
<br /> 		**Affichage concerné**<br /> 		Toutes les vues, mais plus visible sous la vue de Gestion de Projet<br /> 		<br /> 		**Décrivez le bug**<br /> 		Tous les métiers ont le même n° OTP identifié (PN-4930-9010C-1FA00D3600)<br /> 		<br /> 		**A reproduire** 		<br />               N/A<br /><br /> 		**Comportement attendu**<br /> 		Il devrait y a voir 1 n° OTP par métier<br /> 		<br /> 		**Informations complémentaires**<br /> 		Les n° attendus : <br />PN-4930-9010C-1FA00D3100	TRB ICNG Germany PREM<br />PN-4930-9010C-1FA00D3200	TRB ICNG Germany TSE<br />PN-4930-9010C-1FA00D3600	TRB ICNG Germany POWER Engineering<br />PN-4930-9010C-1FA00D3400	TRB ICNG Germany Mechanical Design & Eco<br />PN-4930-9010C-1FA00D3410	TRB ICNG Germany Simulations<br />PN-4930-9010C-1FA00D3420	TRB ICNG Germany Wiring Scheme<br />PN-4930-9010C-1FA00D3610	TRB ICNG Germany Thermal & Acoustic<br />PN-4930-9010C-1FA00D3500	TRB ICNG Germany TCIS Logiciel<br />PN-4930-9010C-1FA00D3900	TRB ICNG Germany RAMS & Fiability<br />PN-4930-9010C-1FA00D3700	TRB ICNG Germany System Validation<br />PN-4930-9010C-1FA00D3710	TRB ICNG Germany Components Validation<br />PN-4930-9010C-1FA00D3800	TRB ICNG Germany MEI Validation<br />PN-4930-9010C-1FA00D3300	TRB ICNG Germany CEM<br /><br /><br />**Liste des pièces jointes:**<br /><a href="https://awa.tnext.loc/api/public/Bug%20meme%20OTP-463209.bmp" target="_blank" >https://awa.tnext.loc/api/public/Bug%20meme%20OTP-463209.bmp</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : oui<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 4<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Frédéric VERNET fvernet 164094 Manager<br /> **Détails du serveur**<br />Version DB: 5.0.0; Version Soft: v1.0.1; Version Back: v1.0.1<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0<br />Adresse du PC :10.24.101.112<br />

**Comment by lokkotara** [comment]
Il s'agit d'une mauvaise manipulation humaine sur l'application. Les écarts ont été rectifiés le 25/06/24 par l'équipe de dev et sont directement consultables sur la version de production. Je clos donc le ticket
