### ISSUE TITLE
id:408475 Zoom sur le budget projet

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#371]
<br /> 		**Gestion du budget des activités**<br /> 		 		<br /> 		**Ajouter un zoom pour permettre d'avoir une ligne par groupe de métiers (même découpage que celui retenu avec le plus petit zoom sur l'affichage "Aperçu charge"**<br /> 		<br /> 		**Cette demande permet au PrEM de suivre les évolutions de budget par métier (et non par acitivité détaillée), notamment après chaque revue financière**<br /> 		<br /><br />**Liste des pièces jointes:**<br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Type de demande d'évolution**<br />Type : modification<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Maité VACHON 408475 408475 Manager<br /> **Détails du serveur**<br />Version DB: 5.0.0; Version Soft: v1.0.2; Version Back: v1.0.2<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0<br />Adresse du PC :10.24.103.225<br />

**Comment by lokkotara** [comment]
Cette évolution sera couvert par le nouvel affichage "Gestion budget projet".
