### ISSUE TITLE
id:426597 Historique charge LOCO H4 IPCEI

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#372]
<br /> 		**Affichage concerné**<br /> 		CHarge/Répartition de charge.<br /> 		<br /> 		**Décrivez la demande d'évolution**<br /> 		Ajouter phase contrat absente sur AWA vs FdL<br /> 		<br /> 		**Informations complémentaires**<br /> 		Perte de l'historique du dépensé de la phase SGR Mechanical jusqu'à mars 2024<br />Perte du reste à faire qui n'avait pas encore été planifié après mars 2024.<br /><br />**Liste des pièces jointes:**<br /><a href="https://awa.tnext.loc/api/public/LOCO%20H4%20IPCEI-715294.pptx" target="_blank" >https://awa.tnext.loc/api/public/LOCO%20H4%20IPCEI-715294.pptx</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Type de demande d'évolution**<br />Type : ajout<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Yann CHEVAL ycheval 426597 Manager<br /> **Détails du serveur**<br />Version DB: 5.0.0; Version Soft: v1.0.2; Version Back: v1.0.2<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0<br />Adresse du PC :10.24.102.111<br />

**Comment by lokkotara** [comment]
Bonjour,

Les activités dont vous parlez ont bien été prises en compte lors du peuplement pour la mise en production. Seulement, sur l'affichage "Répartition de la charge" n'apparaissent que les activités ayant de la charge dans la fenêtre de temps. Or cette activité n'a de la charge que jusqu'en février 2024 (la fenêtre de temps sur cet affichage ne prend que 3 mois en arrière, donc mars 2024. On peut cependant vérifier que cette activité apparaît sur cette capture d'écran de l'affichage "Aperçu de la charge" (car la fenêtre de temps est différente et commence à un an dans le passé, donc juin 2023)

![Image](https://github.com/Alstom-WebFdl/ticket-service/assets/9353050/856a4c8e-13e0-41cf-b57e-2b1ac9924ea0)

Lorsque l'activité souhaitée n'apparaît pas dans le tableau de l'affichage "Répartition de la charge" car sa charge n'est pas dans la fenêtre de temps, il est possible de prévoir sa charge sur cette activité depuis l'affichage "Planification des ressources" comme sur cette capture :

![Image](https://github.com/Alstom-WebFdl/ticket-service/assets/9353050/03ed97df-7673-4b8a-99fa-f37a9b5ad4fa)

Je clos donc ce ticket.
