### ISSUE TITLE
id:408475 Affichage ligne total du budget

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#373]
<br /> 		**Gestion du budget des activités**<br /> 	<br /> 		<br /> 		**Pour le projet "IPCEI HTPG", les totaux par gap ne s'affichent pas (alors que ça marche pour d'autres projets)**<br /> 		<br />**Liste des pièces jointes:**<br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : non<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 2<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Maité VACHON 408475 408475 Manager<br /> **Détails du serveur**<br />Version DB: 5.0.0; Version Soft: v1.0.2; Version Back: v1.0.2<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0<br />Adresse du PC :10.243.98.3<br />

**Comment by lokkotara** [comment]
Il peut arriver que la ligne mette un peu plus de temps que le reste à s'afficher, donnant l'impression qu'elle n'est pas présente. Comme vu ensemble ce jour, elle finit par s'afficher correctement. Je clos donc cet incident.

Cordialement,
