### ISSUE TITLE
id:476028 Fdl FNM: Pb de remonté d'activité

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#374]
<br /> **Affichage concerné**<br /> 	PLANNIFICATION<br /> <br />		**Décrivez le bug**<br /> Projet: FNM<br /><br />Les activités Trains (en phase 0) sont bien remontées (68J *7.4h) mais mais pas séparées par les lignes suivantes de la fdl, à l'exception de la ligne "Déplacement Voyages sur sites d'essais".<br />**Liste des pièces jointes:**<br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : non<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 2<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Christophe FINESTRE cfinestr 476028 Manager<br /> **Détails du serveur**<br />Version DB: 5.0.0; Version Soft: v1.0.2; Version Back: v1.0.2<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0<br />Adresse du PC :10.22.106.208<br />

**Comment by Daniel-Dupuy** [comment]
Le problème venait d'une mauvaise utilisation de la FdL_Valid Système_FNM HMU qui a empêché que le transfert vers AWA se fasse correctement.
Premièrement, l'activité synthèse "Essai sur Train" a été importée alors qu'elle ne le devait pas. Le pb résidait au fait que la formule de la colonne "Σ des Gaps" n'avait pas été supprimée.
Ensuite, certaines activités n'ont pas été importées car le nom avait été modifié entre l'onglet "Contrat" et l'onglet "Planning délivrable" de la FdL.
L'activité "Essai sur train" a été supprimée".
Les activités manquantes et leur charge associée ont été ajoutées dans AWA.
