### ISSUE TITLE
id:480245 Nouvelle ressource non disponible pour affectation de charge

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#375]
<br /> 		**Affichage concerné**<br /> 		 'multi-affichages' <br /> 		<br /> 		**Décrivez le bug**<br /><br /> 		J'ai créé une nouvelle ressource CAPGEMINI BCE, je lui ai attribué de la capacité  mais elle ne remonte pas dans les autres vues pour lui affecter de la charge ou bien remonté ses actuals.<br /> 		<br /> 		<br /><br />**Liste des pièces jointes:**<br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : non<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 2<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Davy BONNASSIES 480245 480245 Manager<br /> **Détails du serveur**<br />Version DB: 5.0.0; Version Soft: v1.0.2; Version Back: v1.0.2<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0<br />Adresse du PC :10.243.98.2<br />

**Comment by lokkotara** [comment]
Bonjour,

 Pour qu'une ressource apparaisse dans le tableau de l'affichage "Répartition de la charge", il faut qu'elle ait au moins une entrée de charge sur une activité, dans la fenêtre de temps. Or une nouvelle ressource n'a par défaut aucune charge. 

Donc après avoir créé la ressource et lui avoir attribué de la capa comme vous l'avez fait, il faut aller sur "Planification des ressources" et ajouter la nouvelle ressource sur au moins une activité et au moins 1 heure. 

Cependant, pour ce dernier point, un souci dans la requête ne prenait pas en compte tous les cas d'usage (comme celui-ci) et ne remontait pas toutes les bonnes ressources. Les changements ont été effectués localement et seront disponible dans l'appli dès la v1.0.3
