### ISSUE TITLE
id:238244 Faux forecast dans le passé

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#376]
**Affichage concerné**<br />1. Dans la vue Charge/Tableau de bord<br />Métier « Mechanical Design – Traction », Ressource « Générique »<br />Résultat : pas de charge prévisionnelle passé<br /><br />2. Dans la vue Charge/Tableau de bord avec Options d’affichage « Projet »<br />Métier « Mechanical Design – Traction », Ressource « Générique »<br />Résultat : 333 h de charge prévisionnelle passé<br /><br />3. Dans la vue Charge/Prévisionnel passé<br />Métier « Mechanical Design – Traction », Ressource « Générique »<br />Résultat : pas de charge prévisionnelle passé<br /> 		<br /> 		**Décrivez le bug**<br /> 		Suivant l'Option d'affichage sélectionnée, du forecast passé est remonté.<br /> 		<br /> 		**A reproduire**<br /> 		Cf. PPT joint<br /><br /> 		**Comportement attendu**<br /> 		Une description précise et concise du comportement attendu<br /> 		<br /> 		**Informations complémentaires**<br /> 		On peut considérer qu'il y a un contournement possible en jouant sur les options d'affichage.<br /><br />**Liste des pièces jointes:**<br /><a href="https://awa.tnext.loc/api/public/240626_AWA_faux%20forecast%20pass%C3%A9-318447.pptx" target="_blank" >https://awa.tnext.loc/api/public/240626_AWA_faux%20forecast%20pass%C3%A9-318447.pptx</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : oui<br />Contournement possible : oui<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 3<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :François TERRIEN fterrien 238244 Manager<br /> **Détails du serveur**<br />Version DB: 5.0.0; Version Soft: v1.0.2; Version Back: v1.0.2<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0<br />Adresse du PC :10.243.98.3<br />

**Comment by lokkotara** [comment]
Ce bug était dû à une mise à jour de la requête qui appelle les datas. 

Elles avaient été faites sur la requête par type de projet (c'est pour cela que pour celle-là, il n'y avait pas de forecast dans le passé). 

Ce changement n'avait pas été répercuté sur les requêtes des autres types d'affichage. Cela a été corrigé localement et sera disponible sur le serveur de production dès la v1.0.3

Cordialement,
