### ISSUE TITLE
id:265160 Affichage capacité BLR sur tableau de bord charge

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#378]
<br />Sur l'affichage du tableau de bord charge, la capacité SEC_BCC n'est pas affichée (BLR_POWER) (voir copie d'écran)<br /><br />Une capacité de 2 ETP est réservée sur cette ressource.<br /><br />La courbe affiche 0 sur la capacité SEC_BCC.<br />**Liste des pièces jointes:**<br /><a href="https://awa.tnext.loc/api/public/Capture%20d%27%C3%A9cran%202024-06-27%20093402-37634.png" target="_blank" >https://awa.tnext.loc/api/public/Capture%20d%27%C3%A9cran%202024-06-27%20093402-37634.png</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : non<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 2<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Yann ROGARD yrogard 265160 Manager<br /> **Détails du serveur**<br />Version DB: 5.0.0; Version Soft: v1.0.2; Version Back: v1.0.2<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0<br />Adresse du PC :10.243.98.2<br />

**Comment by lokkotara** [comment]
En effet, un effet de bord empêchait la requête pour la capa pour le BCC d'être prise en compte correctement. Cela a été corrigé localement et sera disponible sur la production dès la v1.0.3

Cordialement,
