### ISSUE TITLE
id:437695 Transverse offre 2 

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#379]
<br /> 		**Affichage concerné**<br />Répartition de la charge<br /> 		<br /> 		**Décrivez le bug**<br />Le projet transverse offre 2 regroupe plusieurs OTP qui n'ont rien à voir les uns avec les autres et gênent la répartition des actuals et les prévisionnels dans le passé<br /> 		<br /> 		<br /> 		**Comportement attendu**<br /> 		Il devrait être possible dans ce cas de filtrer par OTP ?<br /> 		<br /> 	<br />**Liste des pièces jointes:**<br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : oui<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 4<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Stéphanie LAFON-PLACETTE slafon_p 437695 Manager<br /> **Détails du serveur**<br />Version DB: 5.0.0; Version Soft: v1.0.2; Version Back: v1.0.2<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0<br />Adresse du PC :10.24.102.143<br />

**Comment by lokkotara** [comment]
Comme vu ensemble ce jour, je clos ce ticket pour vous laisser en soumettre un nouveau avec plus de détail sur le cas d'usage, les attendus, les bloquants actuels, etc.. Cordialement,
