### ISSUE TITLE
id:426597 Historique charge LOCO H4 IPCEI WIRING

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#380]
<br /> 		**Affichage concerné**<br /> 		FdL WIRING LOCO H4 IPCEI vs AWA<br /> 		<br /> 		**Décrivez le bug**<br /> 		Certaines tâches ont été attribuées au métier EHI alors qu'elles auraient dû être affectées au métier S&A<br />**Liste des pièces jointes:**<br /><a href="https://awa.tnext.loc/api/public/LOCO%20H4%20IPCEI-WIRING-315456.pptx" target="_blank" >https://awa.tnext.loc/api/public/LOCO%20H4%20IPCEI-WIRING-315456.pptx</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : non<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 2<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Yann CHEVAL ycheval 426597 Manager<br /> **Détails du serveur**<br />Version DB: 5.0.0; Version Soft: v1.0.2; Version Back: v1.0.2<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0<br />Adresse du PC :10.243.98.3<br />

**Comment by Daniel-Dupuy** [comment]
Le problème venait du choix qui a été fait pour Wiring concernant l'import des FdL vers AWA. Le métier final pris en compte dans AWA est celui indiqué dans le plan de charge de Wiring ce qui a entrainé des effets de bord au niveau du tags de certaines activités qui sont passées de EHI vers S&A, Management vers S&A, ou Mangement vers EHI.
Les activités ont été réaffectées au bon métier dans la base de données utilisée par AWA.
