### ISSUE TITLE
id:247383 AJOUT OTP : OTP manquant dans la liste

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#381]
Dans le menu Activité/ Affectation OTP<br />Impossible de trouver le bon OTP dans la liste<br /><br /> 	<br />Sur le projet Regiolis TFA, un mauvais OTP est affecté au métier control commande.<br /><br />Quand il a fallu changer l'OTP via le menu Activité/ Affectation OTP, <br />le bon OTP n'apparait pas dans la liste de choix.<br /><br />Voir le fichier joint avec les captures d'écran.<br /><br />NOTE: Le mauvais OTP était logué dans la fiche de lot control commande du projet TFA.<br />**Liste des pièces jointes:**<br /><a href="https://awa.tnext.loc/api/public/AffectationOTP_Bug-502361.docx" target="_blank" >https://awa.tnext.loc/api/public/AffectationOTP_Bug-502361.docx</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : non<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 2<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Nathalie YERLE nyerle 247383 Manager<br /> **Détails du serveur**<br />Version DB: 5.0.0; Version Soft: v1.0.3; Version Back: v1.0.3<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0<br />Adresse du PC :10.24.101.55<br />

**Comment by lokkotara** [comment]
Pour accéder à la liste complète des otp présents dans la base de données (dont le PI-4930-9029C-1FA00D300), il suffit de cliquer sur le bouton "Voir liste complète"

![Image](https://github.com/Alstom-WebFdl/ticket-service/assets/9353050/b23157b6-d20b-4ddb-9eb3-951cbba02fc9)

Je clos donc ce ticket. Cordialement,
