### ISSUE TITLE
id:148280 reforecast automatique

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#382]
<br /><br /> 		**Affichage concerné**<br />Onglet planification de la charge<br /><br /> 		**Décrivez la demande d'évolution**<br />Lorsque l'on met à jour la charge dans l'onglet "planification de la charge', en faisant 'nettoyer', cela serait intéressant de décaler automatiquement les heures non-pointées sur le mois suivants (ou plusieurs mois suivants, ou dernier mois de l'activité)<br /><br /> 		**Informations complémentaires**<br /><br /><br />**Liste des pièces jointes:**<br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Type de demande d'évolution**<br />Type : modification<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Emmanuel BATISTA ebatista 148280 Manager<br /> **Détails du serveur**<br />Version DB: 5.0.0; Version Soft: v1.0.3; Version Back: v1.0.3<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0<br />Adresse du PC :10.24.100.59<br />

**Comment by dtisnegr** [comment]
L'évolution sera disponible dans la prochaine version. 
Pour activer cette option il faudra aller dans les préférences utilisateurs et activer l'option de reforecast automatique.
