### ISSUE TITLE
id:423920 Affichage infos partiellement masquées

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#385]
<br /> 		**Affichage concerné**<br /> 		Aperçu de la charge<br /> 		<br /> 		**Décrivez la demande d'évolution**<br /> 		Sur l'affichage répartition de la charge, lorsque l'on survole le nom des ressources dans le tableau, un point d'interrogation apparait et affiche le nom complet si il est tronqué. Cette fonction n'est pas disponible sur l'affichage aperçu de la charge alors que le tableau est identique ou presque. Du coup certains noms sont tronqués et quand il s'agit de prestataires il est impossible de les différencier.<br /> 		<br /> 		**Informations complémentaires**<br /> 		Faire idem que sur l'affichage répartition de la charge.<br /><br />**Liste des pièces jointes:**<br /><a href="https://awa.tnext.loc/api/public/Capture%20d%E2%80%99%C3%A9cran%202024-07-02%20101219-113990.png" target="_blank" >https://awa.tnext.loc/api/public/Capture%20d%E2%80%99%C3%A9cran%202024-07-02%20101219-113990.png</a><br /><a href="https://awa.tnext.loc/api/public/Sans%20titre-881800.png" target="_blank" >https://awa.tnext.loc/api/public/Sans%20titre-881800.png</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Type de demande d'évolution**<br />Type : ajout<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Loic SAELINS lsaelin 423920 Manager<br /> **Détails du serveur**<br />Version DB: 5.0.0; Version Soft: v1.0.3; Version Back: v1.0.3<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0<br />Adresse du PC :10.24.102.106<br />

**Comment by lokkotara** [comment]
Cette évolution a été acceptée car facile à mettre en place et bloquant pour l'utilisateur si elle n'est pas mise en place. Cette évolution sera disponible à partir de la v1.0.4.

Cordialement,
