### ISSUE TITLE
id:206314 Affichage Jalons tronqués

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#386]
<br /> 		**Affichage concerné**<br /> 		Gestion des projets<br /> 		<br /> 		**Décrivez le bug**<br /> 		Les dates de Jalon ne s'affichent pas en entier<br /><br /><br /> 		**Comportement attendu**<br /> 		Il faudrait afficher les dates sous la forme 07/24 au lieu de Juillet 2024<br /> 		<br /> <br />**Liste des pièces jointes:**<br /><a href="https://awa-dev.tnext.loc/api/public/Capture%20d%E2%80%99%C3%A9cran%202024-07-02%20115302-425843.png" target="_blank" >https://awa-dev.tnext.loc/api/public/Capture%20d%E2%80%99%C3%A9cran%202024-07-02%20115302-425843.png</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : oui<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 4<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Fabien GOY fgoy 206314 Manager<br /> **Détails du serveur**<br />Version DB: 5.0.0; Version Soft: v1.0.2-2-g2d18a3e; Version Back: v1.0.2-4-g724b7e5<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36<br />Adresse du PC :10.24.103.248<br />

**Comment by lokkotara** [comment]
Il suffisait simplement de laisser plus d'espace pour l'affichage de la date en baissant la taille disponible pour les intitulés de jalon. Cette modification sera disponible à partir de la v1.0.4. 

Cordialement,
