### ISSUE TITLE
id:526995 Pointage mois précédent a disparu pour 2 OTP

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#389]
<br /> 		**Affichage concerné**<br /> 		Précisez l'affichage concerné. Utilisez 'multi-affichages' si l'issue concerne plus d'un affichage<br />=> repartition de charge<br /> 		<br /> 		**Décrivez le bug**<br /> 		Une description concise et précise du bug<br />Au pointage de juin, j'ai du refaire le pointage d'activités du mois de mai alors que je les avaient déjà pointés (validé par le manager) 		<br /><br />A voir si cela se repoduit à nouveau en juillet<br /><br />Contournement : refaire le pointage du mois précédent.<br />**Liste des pièces jointes:**<br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : non<br />Contournement possible : oui<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 1<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Xavier GUILLAUME 526995 526995 Manager<br /> **Détails du serveur**<br />Version DB: 5.0.0; Version Soft: v1.0.3; Version Back: v1.0.3<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0<br />Adresse du PC :10.22.112.140<br />

**Comment by lokkotara** [comment]
Comme vu ensemble ce jour, le bug empêchant de rectifier son pointage en affectant 0 comme valeur va être modifié à partir de la v1.0.4. Je clos donc ce ticket.
