### ISSUE TITLE
id:476028 Fdl FNM: Pb Forecast fin de projet

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#391]
Bonjour,<br />j'avais indiqué en fin de projet, peut être à tort, des Forecast négatifs.<br />Ces prévisions remontent dans la charge globale projet, mais je ne peux les supprimer .<br />Pouvez vous corriger cela ?<br />**Liste des pièces jointes:**<br /><a href="https://awa.tnext.loc/api/public/FNM_FCT_N%C3%A9gatif-94748.PNG" target="_blank" >https://awa.tnext.loc/api/public/FNM_FCT_N%C3%A9gatif-94748.PNG</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : non<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 2<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Christophe FINESTRE cfinestr 476028 Manager<br /> **Détails du serveur**<br />Version DB: 5.0.0; Version Soft: v1.0.3; Version Back: v1.0.3<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0<br />Adresse du PC :10.22.106.208<br />

**Comment by lokkotara** [comment]
Les deux lignes correspondant au dépensé négatif dans le futur ont été supprimées de la base de données. Je clos donc ce ticket.
