### ISSUE TITLE
id:403133 Equations dans les input de saisie des heures

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#392]
<br /> 		**Affichage concerné**<br /> 		Modale de saisie des heures (plannification des ressources, répartition de la charge, gestion budget)<br /> 		<br /> 		**Décrivez la demande d'évolution**<br /> 		Pouvoir faire des équations dans l'input de saisie : ex. "0-7.4" ou "7.4+14.8"<br /> 		<br /> 		**Informations complémentaires**<br /> 		Ajoutez toutes autres informations qui permettraient une meilleure compréhension.<br /> 		N'hésitez pas à rajouter des schémas, organigrammes, dessins dans les fichiers joints.<br /><br />**Liste des pièces jointes:**<br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Type de demande d'évolution**<br />Type : ajout<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Damien TISNÉ-GRIMAUD e_dtisne 403133 Admin<br /> **Détails du serveur**<br />Version DB: 5.0.0; Version Soft: v1.0.4; Version Back: v1.0.4<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:126.0) Gecko/20100101 Firefox/126.0<br />Adresse du PC :10.22.106.90<br />

**Comment by dtisnegr** [comment]
évolution traitée
