### ISSUE TITLE
id:403133 ordre des gaps dans la vue gestion budget

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#395]
<br /> 		**Affichage concerné**<br /> 		gestion budget des activités<br /> 		<br /> 		**Décrivez le bug**<br /> 		Dans la vue matricielle, les budgets ne sont pas alignés en face des bons gap<br /> 		<br /> 		**A reproduire**<br /> 		choisir le métier TRSE<br />le projet 3UH+_3UF+ projet FALBALA<br />pour la 1ere activité, le budget se trouve sur le gap principal+Phase 1 et 2 alors que dans la vue matricielle il est sur le gap principal<br />   <br /><br /> 		**Comportement attendu**<br /> 		Une description précise et concise du comportement attendu<br /> 		<br /> 		**Informations complémentaires**<br /> 		Ajoutez toutes autres informations qui permettraient une meilleure compréhension<br /><br />**Liste des pièces jointes:**<br /><a href="https://awa.tnext.loc/api/public/1-685951.PNG" target="_blank" >https://awa.tnext.loc/api/public/1-685951.PNG</a><br /><a href="https://awa.tnext.loc/api/public/2-242692.PNG" target="_blank" >https://awa.tnext.loc/api/public/2-242692.PNG</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : oui<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 4<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Damien TISNÉ-GRIMAUD e_dtisne 403133 Admin<br /> **Détails du serveur**<br />Version DB: 5.0.0; Version Soft: v1.0.5; Version Back: v1.0.5<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:126.0) Gecko/20100101 Firefox/126.0<br />Adresse du PC :10.22.106.90<br />

**Comment by lokkotara** [comment]
En effet, la requête permettant de récupérer les données de la vue matricielle ne tenait pas compte de l'ordre des gaps. Donc un gap enregistré en base de données après les autres mais ayant un ordre antérieur provoquait cet effet de bord. Le changement sera visible à partir de la v1.0.6
