### ISSUE TITLE
id:98823 retrouver l'onglet "FDL rev table"

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#396]
Bonjour l'équipe support, Je ne sais pas retrouver la vue "FDL rev table", sur laquelle on avait le contrat initial pour le métier, le dépensé et le RAF. Cela permet d'avoir la vue complète du budget et de pouvoir faire une relecture pour les actuals ;) Si elle n'existe pas, peut on la rajouter s'il vous plait <br />Merci<br />Bonne journée<br />Céline<br /> 		**Affichage concerné**<br /> 		Précisez l'affichage concerné. Utilisez 'multi-affichages' si la demande d'évolution concerne plus d'un affichage. S'il s'agit d'une demande de nouvel affichage, le préciser.<br /> 		<br /> 		**Décrivez la demande d'évolution**<br /> 		Une description précise de la demande d'évolution. Une description algorithmique, avec les différentes étapes, serait un plus.<br /> 		<br /> 		**Informations complémentaires**<br /> 		Ajoutez toutes autres informations qui permettraient une meilleure compréhension.<br /> 		N'hésitez pas à rajouter des schémas, organigrammes, dessins dans les fichiers joints.<br /><br />**Liste des pièces jointes:**<br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Type de demande d'évolution**<br />Type : ajout<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Céline RIGAUD cegros 98823 Manager<br /> **Détails du serveur**<br />Version DB: 5.0.0; Version Soft: v1.0.5; Version Back: v1.0.5<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0<br />Adresse du PC :10.24.102.185<br />

**Comment by lokkotara** [comment]
Après discussion ce jour, je ferme ce ticket pour vous permettre de refaire une demande avec plus de détail sur la fonctionnalité attendue et le besoin actuellement non pris en compte. Cordialement,
