### ISSUE TITLE
id:98823 Céline RIGAUD est maintenant moitier TDL Traction :)

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#397]
Bonjour, Est il possible d'affecter une ressource (ici donc moi Céline RIGAUD) sur deux métiers s'il vous plait? j'ai fait la modif de capa dans l'onglet Ressource\capacité mais je n'apparait pas dans les ressources du métier 'Design Leader Traction"<br />MErci :)<br />Ca devrait être le dernier ;)<br />Bonne journée<br />Céline<br /> 		**Affichage concerné**<br /> 		Précisez l'affichage concerné. Utilisez 'multi-affichages' si l'issue concerne plus d'un affichage<br /> 		<br /> 		**Décrivez le bug**<br /> 		Une description concise et précise du bug<br /> 		<br /> 		**A reproduire**<br /> 		Les étapes permettant de reproduire le comportement indésirable :<br /> 		1. Sur l'affichage '...'<br /> 		2. Je clique sur '....'<br /> 		3. Je descend le tableau '....'<br /> 		4. L'erreur se reproduit<br /><br /> 		**Comportement attendu**<br /> 		Une description précise et concise du comportement attendu<br /> 		<br /> 		**Informations complémentaires**<br /> 		Ajoutez toutes autres informations qui permettraient une meilleure compréhension<br /><br />**Liste des pièces jointes:**<br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : non<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 2<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Céline RIGAUD cegros 98823 Manager<br /> **Détails du serveur**<br />Version DB: 5.0.0; Version Soft: v1.0.5; Version Back: v1.0.5<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0<br />Adresse du PC :10.24.102.185<br />

**Comment by lokkotara** [comment]
Il s'agissait d'un manque de compréhension sur le fonctionnement de l'appli. Nous avons pu voir ensemble comment procéder pour obtenir le résultat souhaité. Je clos donc ce ticket.
