### ISSUE TITLE
id:172975 Manque ressource control/Command Emilie Lefebvre

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#413]
<br /> Bonjour, <br /><br />Emilie Lefebvre n'est pas déclarée dans la liste des ressources Traction Control. <br /><br />Peut-on la rajouter ? <br /><br />Merci<br />Fabien<br /><br />**Liste des pièces jointes:**<br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : non<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 2<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Fabien DEHOURS fdehours 172975 Manager<br /> **Détails du serveur**<br />Version DB: 5.0.0; Version Soft: v1.0.5; Version Back: v1.0.5<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0<br />Adresse du PC :10.24.102.99<br />

**Comment by lokkotara** [comment]
Bonjour, en fait Emilie est déclarée en tant que ressource inactive dans l'appli (elle n'avait pas de charge au peuplement de la mise en production). Cela a pour effet de ne pas la faire remonter sur certaines listes (dans les filtres ou l'affichage de la capa). Pour résoudre ce souci, il suffit de la repasser en ressource active dans l'affichage "Gestion des ressources". Cordialement,
