### ISSUE TITLE
id:521415 Nettoyage impossible du forecast dans le passé

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#418]
<br /> 		**Affichage concerné**<br /> 		Répartition de la charge<br /> 		<br /> 		**Décrivez le bug**<br /> 		Problème n°1 : Les heures qui étaient du forecast dans les FdL ne peuvent pas êtres enlevés via AWA.<br />Pouvez vous les supprimer?<br /><br /> 		Problème n°2 : pour les actuals presta, au mois de mai, il y a des heures à répartir qui ne provienne pas d'un import et ne sont pas cohérent avec les BL.<br />Pourvez vous aussi supprimer?<br /><br />cf fichier en PJ<br /> 		<br /><br />**Liste des pièces jointes:**<br /><a href="https://awa.tnext.loc/api/public/Forecast%20Passe%20AWA-568358.xlsx" target="_blank" >https://awa.tnext.loc/api/public/Forecast%20Passe%20AWA-568358.xlsx</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : oui<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 4<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Jean-Yves RITZMANN 521415 521415 Manager<br /> **Détails du serveur**<br />Version DB: 5.0.0; Version Soft: v1.0.5; Version Back: v1.0.5<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0<br />Adresse du PC :10.22.106.249<br />

**Comment by lokkotara** [comment]
Ces heures importées des fiches de lots en tant que "heures dépensées" ne peuvent pas être retirées depuis l'appli. J'ai donc effectué l'action ce jour en base de données. Concernant le deuxième point cela peut correspondre à des pointages importées par un autre métier pour la même presta générique. la prochaine mise à jour (v1.0.6) permettra de faire la répartition des mois suivants même lorsque tous les pointages des mois précédents n'ont pas tous été faits. Elle devrait arriver d'ici la fin de la semaine. Cordialement,
