### ISSUE TITLE
id:206314 Changement DFQ pas pris en compte dans Gestion de projet

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#423]
<br /> 		**Affichage concerné**<br /> 		Gestion de projet<br /> 		<br /> 		**Décrivez le bug**<br /> 		<br /><br /> 		<br /> 		**A reproduire**<br /> 		1.Mise à jour des infos dans Gestion de projet: dates DFQ et nom du PrEM<br /> 		2. changement vers un nouvel affichage<br /> 		3. retour vers Gestion de projet: le nom PrEM et dates DFQ sont celles qui étaient au début, donc modifications pas prises en compte<br />**Liste des pièces jointes:**<br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : non<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 2<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Fabien GOY fgoy 206314 Manager<br /> **Détails du serveur**<br />Version DB: 5.0.0; Version Soft: v1.0.3-22-gd28e916; Version Back: v1.0.3-15-g6f4b93f<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36<br />Adresse du PC :10.24.101.179<br />

**Comment by lokkotara** [comment]
C'était un problème d'URL. En effet, vos actions étaient effectuées sur notre serveur de développement au lieu du serveur de production. Je clos donc le ticket
