### ISSUE TITLE
id:480245 Double problème

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#427]
<br />1) Serait-il possible d'annuler l'entrée presta suivante (voir la PJ) ?<br />Il y a eu un problème lors du BL et l'entrée est fausse au niveau de l'OTP. Le pointage à été fait conforme en intégrant directement la charge au bon endroit, il reste cependant cet actuals qui ne peux pas être affecté et bloque les pointages du mois suivant. <br /><br />2) L'actuals relatif à l'activité de CAPGEMINI_ABI du mois de Juin coïncide avec une activité prévu et pourtant lors de la validation, la ligne n'apparait pas validée (pas de crosscheck vert).<br /> <br /><br />**Liste des pièces jointes:**<br /><a href="https://awa.tnext.loc/api/public/Actuals%20%C3%A0%20annul%C3%A9-6149.png" target="_blank" >https://awa.tnext.loc/api/public/Actuals%20%C3%A0%20annul%C3%A9-6149.png</a><br /><a href="https://awa.tnext.loc/api/public/Actuals%20impossible%20%C3%A0%20valid%C3%A9-980629.png" target="_blank" >https://awa.tnext.loc/api/public/Actuals%20impossible%20%C3%A0%20valid%C3%A9-980629.png</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : oui<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 4<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Davy BONNASSIES 480245 480245 Manager<br /> **Détails du serveur**<br />Version DB: 5.0.0; Version Soft: v1.0.5; Version Back: v1.0.5<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0<br />Adresse du PC :10.24.102.155<br />

**Comment by lokkotara** [comment]
Ce jour, l'entrée de pointage a bien été supprimée 

![Image](https://github.com/user-attachments/assets/fcc93440-9a56-4857-bb00-61d11703ac02)

Pour le souci de l'icône de pointage réparti, c'est un effet de bord qui est résolu à partir de la v1.0.6. 

Cordialement,
