### ISSUE TITLE
id:404934 Pas possible de répartir les actuals sur mois de mai alors que je peux faire le mois de juin 

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#428]
Sur l'import des actuals pour les mois de mai et juin (effectué en même temps) je ne peux mettre à jour mai avant juin. sur PRESTA LATESYS MECHA SIMULATION<br />**Liste des pièces jointes:**<br /><a href="https://awa.tnext.loc/api/public/Capture%20d%E2%80%99%C3%A9cran%202024-07-17%20142810-474086.png" target="_blank" >https://awa.tnext.loc/api/public/Capture%20d%E2%80%99%C3%A9cran%202024-07-17%20142810-474086.png</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : non<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 2<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Thomas MORÈRE 404934 404934 Manager<br /> **Détails du serveur**<br />Version DB: 5.0.0; Version Soft: v1.0.5; Version Back: v1.0.5<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0<br />Adresse du PC :10.243.98.2<br />

**Comment by lokkotara** [comment]
Cet effet de bord indésirable n'apparaît plus à partir de la v1.0.6 car les pointages des autres mois ne sont plus désactivés.

Je clos donc ce ticket
