### ISSUE TITLE
id:403133 pb à la création du ticket

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#435]
<br /> 		**Affichage concerné**<br /> 		création ticket<br /> 		<br /> 		**Décrivez le bug**<br /> 		le ticket se crée mais je n'ai pas eu l'alert de confirmation avec le numéro, d'où le ticket en tripe...<br /><br />**Liste des pièces jointes:**<br /><a href="https://awa.tnext.loc/api/public/Capture-681237.PNG" target="_blank" >https://awa.tnext.loc/api/public/Capture-681237.PNG</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : oui<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 4<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Damien TISNÉ-GRIMAUD e_dtisne 403133 Admin<br /> **Détails du serveur**<br />Version DB: 5.0.0; Version Soft: v1.0.5; Version Back: v1.0.5<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:126.0) Gecko/20100101 Firefox/126.0<br />Adresse du PC :10.22.106.90<br />

**Comment by lokkotara** [comment]
Un loader a été rajouté sur le bouton de validation, à partir de la mise à jour v1.0.6, afin d'éviter de reproduire cet effet indésirable. Je clos donc le ticket
