### ISSUE TITLE
id:244473 Pas de prise en compte du séparateur décimale  ","

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#436]
<br /> 		**Affichage concerné**<br /> Planification<br /> 		<br /> 		**Décrivez le bug**<br />Sous la vue planification , le séparateur décimale virgule n'est pas pris en compte<br />Il faut utiliser le point "."<br /><br />Capture 1: saisie d'une charge avec décimale en ","<br />Captaure 2 : pas de prise en compte de la virgule<br /><br />**Liste des pièces jointes:**<br /><a href="https://awa.tnext.loc/api/public/Capture1-366826.JPG" target="_blank" >https://awa.tnext.loc/api/public/Capture1-366826.JPG</a><br /><a href="https://awa.tnext.loc/api/public/Capture2-74479.JPG" target="_blank" >https://awa.tnext.loc/api/public/Capture2-74479.JPG</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : non<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 2<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Johana VALLY jvally 244473 Manager<br /> **Détails du serveur**<br />Version DB: 5.0.0; Version Soft: v1.0.6; Version Back: v1.0.6<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0<br />Adresse du PC :10.243.98.2<br />

**Comment by lokkotara** [comment]
Cet effet de bord est causé par le même code que le ticket #437 et sa correction sera aussi disponible à partir de la v1.0.7.
