### ISSUE TITLE
id:244473 PAs de prise en compte de la charge Planifié si "0" devant la valeur

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#437]
<br /> 		**Affichage concerné**<br /> 	Planification<br /> 		<br /> 		**Décrivez le bug**<br />Saisie d'une charge sous planification en saisissant un zéro devant la valeur de charge <br />Cf Capture 1<br />La saisie ne peut être validée <br />Il faut supprimer le 0<br />A priori pas un problème précédemment ou au moins sous affichage répartition charge <br /><br />**Liste des pièces jointes:**<br /><a href="https://awa.tnext.loc/api/public/Capture1-234457.JPG" target="_blank" >https://awa.tnext.loc/api/public/Capture1-234457.JPG</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : non<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 2<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Johana VALLY jvally 244473 Manager<br /> **Détails du serveur**<br />Version DB: 5.0.0; Version Soft: v1.0.6; Version Back: v1.0.6<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0<br />Adresse du PC :10.243.98.2<br />

**Comment by lokkotara** [comment]
En effet, depuis la mise à jour précédente, une erreur du navigateur empêche la sauvegarde de la valeur si elle commence par un 0. Ce souci est corrigé localement et sera disponible à partir de la v1.0.7. Cordialement,
