### ISSUE TITLE
id:19997 blocage appli

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#438]
<br /> 		**Affichage concerné**<br /> 		répartition charge<br /> 		<br /> 		**Décrivez le bug**<br /> 		lors du passage sur l'écran répartition de charge, après qqs secondes, un message d'erreur apparait (voir capture jointe) et aucun résultat ne s'affiche.<br />Les autres écrans semblent corrects.<br /> 		<br /> 		**A reproduire**<br /> 		Les étapes permettant de reproduire le comportement indésirable :<br /> 		1. Sur l'affichage '...'<br /> 		2. Je clique sur '....'<br /> 		3. Je descend le tableau '....'<br /> 		4. L'erreur se reproduit<br /><br /> 		**Comportement attendu**<br /> 		Une description précise et concise du comportement attendu<br /> 		<br /> 		**Informations complémentaires**<br /> 		Ajoutez toutes autres informations qui permettraient une meilleure compréhension<br /><br />**Liste des pièces jointes:**<br /><a href="https://awa.tnext.loc/api/public/bugAWA-801232.PNG" target="_blank" >https://awa.tnext.loc/api/public/bugAWA-801232.PNG</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : non<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 2<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Vincent MICKIEWICZ vmickiew 19997 Manager<br /> **Détails du serveur**<br />Version DB: 5.0.0; Version Soft: v1.0.6; Version Back: v1.0.6<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0<br />Adresse du PC :10.24.100.186<br />

**Comment by lokkotara** [comment]
Cet effet indésirable est apparu avec la dernière mise à jour. Un correctif sera disponible à partir de la v1.0.7 de l'application. Cordialement,
