### ISSUE TITLE
id:206314 Erreur de frappe dans "Changer la fenetre de temps"

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#440]
<br /> 		**Affichage concerné**<br /> 		Aperçu de la charge<br /> 		<br /> 		**Décrivez le bug**<br /> 		On peut écrire n'importe quoi dans la fenetre pour changer la fenetre de temps<br /> 		On peut valider et cela ne genère pas de correction<br /> 		<br /> 		**Comportement attendu**<br /> 		Il serait bien qu'un popup s'affiche en expliquant que la date n'est pas OK<br /> 	<br />**Liste des pièces jointes:**<br /><a href="https://awa.tnext.loc/api/public/Capture%20d%E2%80%99%C3%A9cran%202024-07-24%20153111-472621.png" target="_blank" >https://awa.tnext.loc/api/public/Capture%20d%E2%80%99%C3%A9cran%202024-07-24%20153111-472621.png</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : non<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 2<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Fabien GOY fgoy 206314 Manager<br /> **Détails du serveur**<br />Version DB: 5.0.0; Version Soft: v1.0.6; Version Back: v1.0.6<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36<br />Adresse du PC :10.22.108.171<br />

**Comment by lokkotara** [comment]
La fenêtre additionnelle est en train d'être modifiée visuellement afin de faciliter le renseignement d'une date. De plus, cela permettra d'harmoniser le rendu visuel sur tous les navigateurs.
