### ISSUE TITLE
id:128881 Bug saisie heurs sur Gestion du budget

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#441]
Lorsque l'on ajoute une activité et que l'on que l'on ne saisie pas de suite le nombre d'heure il <br />n'est plus possible de le faire (sur cette page)<br />Dans le Screen-shot le cas Nok est arrivé après une manip.<br />Le cas Ok c'est pour la saisie sans faire d'autre manip. comme changer d'écran ou d'application<br /><br />**Liste des pièces jointes:**<br /><a href="https://awa.tnext.loc/api/public/Ajout%20activit%C3%A9-541017.PNG" target="_blank" >https://awa.tnext.loc/api/public/Ajout%20activit%C3%A9-541017.PNG</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : oui<br />Contournement possible : oui<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 3<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Emmanuel CHAIX echaix 128881 Manager<br /> **Détails du serveur**<br />Version DB: 5.0.0; Version Soft: v1.0.7; Version Back: v1.0.7<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0<br />Adresse du PC :10.243.98.2<br />

**Comment by lokkotara** [comment]
Comme vu ensemble ce jour, ce fonctionnement est celui attendu sur cet affichage. Cet affichage fait partie de la prochaine brique de mise à jour de l'appli (V2 -> Gestion des variations de Budget).

Je clos donc ce ticket
