### ISSUE TITLE
id:415046 Planification ressources : bug metier VALR & ISA sur mpl16

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#442]
<br /> 		**Affichage concerné**<br /> 		Dans planification ressources, projet mpl16<br /> 		<br /> 		**Décrivez le bug**<br />               Si choix metier parent (Traction Control) alors impossible d'ajouter/modifier ressources sur metier VALR & ISA<br /> 		<br /> 		**A reproduire**<br /> 		Les étapes permettant de reproduire le comportement indésirable :<br /> 		1. Sur l'affichage planification ressources'<br /> 		2. Je clique sur 'metier VALR & ISA'<br /> 		3. Je clique sur ajouter ou modifier ressources<br /> 		4. L'activité Logiciel V150 n'apparaît pas<br /><br /> 		**Comportement attendu**<br /> 		Une description précise et concise du comportement attendu<br /> 		<br /> 		**Informations complémentaires**<br /> 		Vu avec Daniel DUPUY<br /><br />**Liste des pièces jointes:**<br /><a href="https://awa.tnext.loc/api/public/Capture-181475.JPG" target="_blank" >https://awa.tnext.loc/api/public/Capture-181475.JPG</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : oui<br />Contournement possible : oui<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 3<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Olivier ANDRIEU oandrieu 415046 Manager<br /> **Détails du serveur**<br />Version DB: 5.0.0; Version Soft: v1.0.7; Version Back: v1.0.7<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0<br />Adresse du PC :10.22.108.253<br />

**Comment by lokkotara** [comment]
Cet effet de bord était dû à un souci dans la requête pour récupérer la liste d'activités sur cet affichage. Le code a été modifié localement et sera disponible à partir de la v1.0.8. 

Cordialement,
