### ISSUE TITLE
id:238244 Changer l'ordre des séries

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#444]
<br /> 		**Affichage concerné**<br /> 		Dans l'affichage "Tableau de bord de la charge" avec "Options d’affichage : Type de ressource"<br /> 		<br /> 		**Décrivez la demande d'évolution**<br /> 		Changer l'ordre des série de manière à ce que CDI (charge allouée) soit la série la plus lisible (et non Générique qui est la charge non-allouée).<br /> 		<br /> 		**Informations complémentaires**<br /> 		Cf ppt joint<br /><br />**Liste des pièces jointes:**<br /><a href="https://awa.tnext.loc/api/public/240814_AWA_ordre-des-series-293324.pptx" target="_blank" >https://awa.tnext.loc/api/public/240814_AWA_ordre-des-series-293324.pptx</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Type de demande d'évolution**<br />Type : modification<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :François TERRIEN fterrien 238244 Manager<br /> **Détails du serveur**<br />Version DB: 5.0.0; Version Soft: v1.0.7; Version Back: v1.0.7<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0<br />Adresse du PC :10.24.102.184<br />

**Comment by lokkotara** [comment]
L'ordre d'affichage des statuts de ressources a été modifié comme suit :

1. CDI
2. CDD
3. Interimaire
4. Alternant
5. Stagiaire
6. VIE
7. ND_HAF
8. Interne générique
9. Prestataire
10. Prestataire générique
11. SEC

Je clos donc cette demande d'évolution.
