### ISSUE TITLE
id:238244 Incohérence de nettoyage/charge dans le passé ?

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#445]
<br /> 		**Affichage concerné**<br /> 		Y a-t-il bien une incohérence ou un bug entre les données affichées sur "Répartition de la charge (en heures)" et "Charge prévisionnelle dans le passé" ?<br /> 		<br /> 		**Décrivez le bug**<br /> 		Dans "Répartition de la charge (en heures)", j'ai réalisé la répartition des actuals, puis nettoyer le prévisionnel non utilisé sur les mois passés.<br />Quand je vais voir la situation dans "Charge prévisionnelle dans le passé", je constate que j'ai des heures non réparties sur les activités qui ont pourtant été traitées à l'étape précédente.<br /> 		<br /> 		**A reproduire**<br /> 		Cf. ppt joint<br /><br /> 		**Comportement attendu**<br /> 		Réussir à dissocier ce qui est réellement de la charge prévisionnelle dans le passé. <br /> 		<br /> 		**Informations complémentaires**<br /> 		Cf ppt joint<br />**Liste des pièces jointes:**<br /><a href="https://awa.tnext.loc/api/public/240814_AWA_bug%20nettoyage-530567.pptx" target="_blank" >https://awa.tnext.loc/api/public/240814_AWA_bug%20nettoyage-530567.pptx</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : oui<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 4<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :François TERRIEN fterrien 238244 Manager<br /> **Détails du serveur**<br />Version DB: 5.0.0; Version Soft: v1.0.7; Version Back: v1.0.7<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0<br />Adresse du PC :10.24.102.184<br />

**Comment by lokkotara** [comment]
En effet, il y a un effet de bord entre les deux affichages. Cela est dû à la requête pour l'affichage "Prévisionnel dans le passé" qui ne prenait pas en compte la particularité de notre BDD. Ce souci a été réglé en local et sera disponible ) partir de la v1.0.8.

Cordialement,
