### ISSUE TITLE
id:238244 Incohérence totaux entre deux vues ?

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#447]
<br /> 		**Affichage concerné**<br /> 		Vue surveillance projet et vue planification des ressources<br /> 		<br /> 		**Décrivez le bug**<br /> 		Projet : TGV2020 - Traction<br /> 		Métier : Design Leader - Traction<br /> 		<br /> 		**A reproduire**<br /> 		Les étapes permettant de reproduire le comportement indésirable :<br /> 		1. Sur l'affichage 'surveillance projet'<br /> 		2. Je clique sur la valeur en heures de charge (1472,6 heures)<br /> 		3. J'arrive alors sur la vue planification des ressources<br /> 		4. J'additionne les heures de charge de chacune des activités et j'obtiens 1428,2 heures et non 1472,6 heures.<br /> 		5. Je ne sais pas dire sur quelle activité sont les 44,4 heures d'écart entre les deux totaux de charge.<br /><br /> 		**Comportement attendu**<br /> 		Une description précise et concise du comportement attendu<br /> 		<br /> 		**Informations complémentaires**<br /> 		Ajoutez toutes autres informations qui permettraient une meilleure compréhension<br /><br />**Liste des pièces jointes:**<br /><a href="https://awa.tnext.loc/api/public/240820_AWA_totaux%20incoh%C3%A9rents-592093.pptx" target="_blank" >https://awa.tnext.loc/api/public/240820_AWA_totaux%20incoh%C3%A9rents-592093.pptx</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : oui<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 4<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :François TERRIEN fterrien 238244 Manager<br /> **Détails du serveur**<br />Version DB: 5.0.0; Version Soft: v1.0.7; Version Back: v1.0.7<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0<br />Adresse du PC :10.24.102.184<br />

**Comment by lokkotara** [comment]
Cet effet de bord provient de la construction de la requête qui ne prend pas en compte le distingo entre charge dépensée et prévisionnelle. Ceci est corrigé localement et sera disponible à partir de la v1.0.8.

Cordialement,
