### ISSUE TITLE
id:159224 bugg prévisionnel passé

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#452]
<br /> 		**Affichage concerné**<br /> 		Prévisionnel passé<br /> 		<br /> 		**Décrivez le bug**<br /> 		l'affichage remonte du spent en "prévisionnel passé" sur M-2 et/Ou M-3, dès lors qu'il y a du prévisionnel passé sur M-1<br /> 		<br /> 		<br /><br /> 		**Comportement attendu**<br /> 		Besoin de n'avoir que le prévissionnel passé<br /> 		<br /> 		**Informations complémentaires**<br /> 		Je cherchais à faire un KPI de prévisionnel passé mais infaisable avec ce bugg ==> ça rend la demande assez urgente sauf si autre moyen d'avoir la liste<br /><br />**Liste des pièces jointes:**<br /><a href="https://awa.tnext.loc/api/public/Yann%20cheval%20-%20pr%C3%A9visionnel%20pass%C3%A9-910212.jpg" target="_blank" >https://awa.tnext.loc/api/public/Yann%20cheval%20-%20pr%C3%A9visionnel%20pass%C3%A9-910212.jpg</a><br /><a href="https://awa.tnext.loc/api/public/Yann%20cheval%20-%20r%C3%A9parttion%20charge-638971.jpg" target="_blank" >https://awa.tnext.loc/api/public/Yann%20cheval%20-%20r%C3%A9parttion%20charge-638971.jpg</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : oui<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 4<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Valentin  TACHET vtachet 159224 Manager<br /> **Détails du serveur**<br />Version DB: 5.0.0; Version Soft: v1.0.7; Version Back: v1.0.7<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0<br />Adresse du PC :10.24.101.112<br />

**Comment by lokkotara** [comment]
Un correctif est déjà appliqué en local et sera disponible à partir de la v1.0.8.

Cordialement,
