### ISSUE TITLE
id:238244 Permettre d'éditer dans la vue matricielle (Activité/Gestion budget)

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#454]
<br /> 		**Affichage concerné**<br /> 		Constaté sur l'affichage Activité/Gestion budget<br /> 		<br /> 		**Décrivez la demande d'évolution**<br /> 		Dans la vue "liste", il est possible d'éditer le nom et la phase des activités.<br />L'édition n'est pas possible lorsque l'on est dans la vue "matricielle".<br />La demande consiste à ajouter les commandes d'édition dans la vue matricielle, pour plus de réactivité.<br /> 		<br /> 		**Informations complémentaires**<br /> 		Cf. ppt<br /><br />**Liste des pièces jointes:**<br /><a href="https://awa.tnext.loc/api/public/240823_AWA_editer-nom-activite-320630.pptx" target="_blank" >https://awa.tnext.loc/api/public/240823_AWA_editer-nom-activite-320630.pptx</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Type de demande d'évolution**<br />Type : ajout<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :François TERRIEN fterrien 238244 Manager<br /> **Détails du serveur**<br />Version DB: 5.0.0; Version Soft: v1.0.7; Version Back: v1.0.7<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0<br />Adresse du PC :10.24.102.184<br />

**Comment by lokkotara** [comment]
Cette demande sera couverte lors du déploiement de la V2.

Cordialement,
