### ISSUE TITLE
id:193407 Affichage charge par OTP puis par métiers

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#462]
<br /> 		**Affichage concerné**<br /> 		Multi affichage ou un affichage propre avec les OTP<br /> 		<br /> 		**Décrivez la demande d'évolution**<br /> 		L'affichage par OTP et par métier, permettrait une interface plus facile avec finances pour prise en compte dans ODYC.<br /> 		<br /> 		**Informations complémentaires**<br /> 		Willy BODIN a exprimé la demande, si besoin ne pas hésitez à me contacter joints.<br /><br /><br />**Liste des pièces jointes:**<br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Type de demande d'évolution**<br />Type : ajout<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Willy BODIN wbodin 193407 SSM<br /> **Détails du serveur**<br />Version DB: 5.0.2; Version Soft: v1.0.8; Version Back: v1.0.8<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36 Edg/127.0.0.0<br />Adresse du PC :10.22.112.231<br />

**Comment by lokkotara** [comment]
L'OTP étant modifiable sans tenir compte de l'historique, cette vue ne reflèterait pas la réalité de l'historique de l'OTP.

Cordialement,
