### ISSUE TITLE
Premier ticket

### ISSUE THREAD

**Issue by lokkotara** [Alstom-WebFdl/ticket-service#468]
Tout d'abord bienvenue parmi nous ;)

Ce ticket ne sert qu'à s'assurer que le système de ticketing fonctionne bien.

Tu peux donc le clôturer après avoir laisser un commentaire.

**Comment by isma-tj** [comment]
Merci beaucoup @lokkotara pour tonaide à m’installer et à m’intégrer dans l’équipe. Je suis enthousiaste à l’idée de contribuer et d’avancer sur ce projet !
