### ISSUE TITLE
id:238244 Actuals validé mais non réparti

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#477]
**Affichage concerné**<br />Charge/répartition<br /> 		<br /> 		**Décrivez le bug**<br />Pour le mois d'août 2024, mes actuals indiquent des heures sur le projet SEPTA street cars EDC.<br />La répartition automatique m'avait trouvé le provisionnel, j'avais validé etc.<br />En regardant ce matin, je vois que la case est cochée mais pourtant c'est indiqué 0/3.7.<br /><br />Cf. image jointe.<br /> 		<br /> 		**A reproduire**<br />Choisir ressource TERRIEN et projet SEPTA streetcars<br />Faire Répartir les actuals<br /><br />Ai-je fait une fausse manip ?<br /><br /><br /> 		**Comportement attendu**<br />0/3.7 => pas coché et pas validé<br />3.7/3.7 => coché<br /> 		<br /> 		**Informations complémentaires**<br /> 		Ajoutez toutes autres informations qui permettraient une meilleure compréhension<br /><br />**Liste des pièces jointes:**<br /><a href="https://awa.tnext.loc/api/public/240913_AWA_Septa-943026.JPG" target="_blank" >https://awa.tnext.loc/api/public/240913_AWA_Septa-943026.JPG</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : non<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 2<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :François TERRIEN fterrien 238244 Manager<br /> **Détails du serveur**<br />Version DB: 5.0.2; Version Soft: v1.0.9; Version Back: v1.0.9<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36 Edg/127.0.0.0<br />Adresse du PC :10.24.103.181<br />

**Comment by lokkotara** [comment]
Bonjour,

Merci pour votre retour.

Après plusieurs essais, nous n'avons pas réussi à reproduire ce comportement. Il est possible que les derniers changements apportés au code aient résolu cet effet non désiré.

Nous fermons donc ce ticket. Cependant, nous restons à votre disposition si le problème réapparaît ou si vous avez d'autres questions.

Cordialement,
