### ISSUE TITLE
id:200959906 Affichage 'Actuals à répartir' : Pas de résultat et bouton 'Plus de résultat' non disponible

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#478]
<br /> 		**Affichage concerné**<br /> 		Affichage 'Actuals à répartir'<br /> 		<br /> 		**Décrivez le bug**<br /> 		Pour les Actuals de mai-24 (hors fenêtre de temps), aucune activité n'apparaît, et seul le bouton 'Ajouter une activité' est disponible.<br />A partir des Actuals de Juin-24 (dans la fenêtre de temps), la liste des activités filtrées dans la vue 'Répartition de la charge' apparaissent mais seul le bouton 'Ajouter une activité' est disponible<br /> 		<br /> 		**A reproduire**<br /> 		Les étapes permettant de reproduire le comportement indésirable :<br /> 		1. Sur l'affichage 'Répartition de la charge'<br /> 		2. Je filtre sur Projet "Baden-Württemberg - Armoires" et sur Ressource "BLR FMI EDC"<br /> 		3. Je clique sur 'Répartir les Actuals'<br /> 		4. Le bug se produit quand je sélectionne l'Actual de mai-24 et les Actuals avec OTP GA-4930-0010-MU26 de juin et juil-é'<br /><br /> 		**Comportement attendu**<br /> 		Pour mai-24 (hors fenêtre de temps, la liste d'activités doit apparaître et le bouton 'Plus de résultats' doit être disponible.<br />Pour les Actuals dans la fenêtre de temps, le bouton 'Plus de résultats' doit être disponible.<br /><br /><br />**Liste des pièces jointes:**<br /><a href="https://awa.tnext.loc/api/public/Filtre%20dans%20R%C3%A9partition%20de%20la%20charge-572349.JPG" target="_blank" >https://awa.tnext.loc/api/public/Filtre%20dans%20R%C3%A9partition%20de%20la%20charge-572349.JPG</a><br /><a href="https://awa.tnext.loc/api/public/Bug%20aucune%20activit%C3%A9%20propos%C3%A9e%20et%20bouton%20Plus%20de%20r%C3%A9sultat%20manquant-762864.JPG" target="_blank" >https://awa.tnext.loc/api/public/Bug%20aucune%20activit%C3%A9%20propos%C3%A9e%20et%20bouton%20Plus%20de%20r%C3%A9sultat%20manquant-762864.JPG</a><br /><a href="https://awa.tnext.loc/api/public/Bug%20bouton%20Plus%20de%20r%C3%A9sultat%20manquant-870946.JPG" target="_blank" >https://awa.tnext.loc/api/public/Bug%20bouton%20Plus%20de%20r%C3%A9sultat%20manquant-870946.JPG</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : non<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 2<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Daniel DUPUY e_ddupuy 200959906 Admin<br /> **Détails du serveur**<br />Version DB: 5.0.2; Version Soft: v1.0.9; Version Back: v1.0.9<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36 Edg/127.0.0.0<br />Adresse du PC :10.22.112.171<br />

**Comment by lokkotara** [comment]
Un correctif a été apporté localement et est en train d'être testé sur le serveur de développement. Il refactorise le système d'affichage des boutons. Aussi un message d'information explique maintenant à l'utilisateur lorsque le périmètre séléctionné dans le tableau de charge ne retourne aucune activité pour un pointage dépensé.

Je laisse ce ticket ouvert en attendant l'application du correctif sur la prochaine mise à jour v1.0.10.
