### ISSUE TITLE
id:180337 pb de forcast auto lors du nettoyage

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#481]
<br /> 		**Affichage concerné**<br /> 		Répartition de la charge<br /> 		<br /> 		**Décrivez le bug**<br /> 		le reforcast auto ne se fait pas<br /> 		<br /> 		**A reproduire**<br /> 		Les étapes permettant de reproduire le comportement indésirable :<br /> 		1. Sur l'affichage '...'<br /> 		2. Je clique sur '....'<br /> 		3. Je descend le tableau '....'<br /> 		4. L'erreur se reproduit<br /><br /> 		**Comportement attendu**<br /> 		Une description précise et concise du comportement attendu<br /> 		<br /> 		**Informations complémentaires**<br /> 		Ajoutez toutes autres informations qui permettraient une meilleure compréhension<br /><br />**Liste des pièces jointes:**<br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : non<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 2<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Christophe DISDIER cdisdier 180337 Manager<br /> **Détails du serveur**<br />Version DB: 5.0.2; Version Soft: v1.0.9; Version Back: v1.0.9<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36 Edg/127.0.0.0<br />Adresse du PC :10.24.102.18<br />

**Comment by lokkotara** [comment]
Bonjour,

Nous vous remercions pour votre signalement.

Nous avons identifié qu'un effet de bord non souhaité est à l'origine de votre problème. En effet, la valeur du bouton "Reforecast auto activé" n'est pas correctement lue si l'utilisateur n'a pas cliqué au moins une fois sur "Valider les changements" se trouvant dans les préférences utilisateur (ancien emplacement de ce bouton). Ce bug sera corrigé dans la prochaine mise à jour (v1.0.10).

En attendant, voici une solution de contournement :

1. Cliquez sur le menu déroulant en haut à droite (icône avec trois traits horizontaux).
2. Cliquez sur l'icône représentant un bonhomme avec un engrenage (préférences utilisateur).
3.  Assurez-vous qu'aucun filtre n'est déjà sélectionné ou confirmez que vous souhaitez les garder comme préférences.
4. Cliquez sur "Valider les changements".

Cela devrait vous permettre d'utiliser la fonctionnalité de reforecast automatique sans problème.

Nous laissons ce ticket ouvert jusqu'à la résolution définitive de votre souci.

Cordialement,

**Comment by lokkotara** [comment]
Le correctif à été apporté avec la v1.0.10 actuellement en production depuis le 09/10/2024. Je clos donc ce ticket.
Cordialement,
