### ISSUE TITLE
id:238244 Actuals toujours visible le mois suivant

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#482]
<br /> 		**Affichage concerné**<br />Charge/Répartition/Répartir les Actuals<br /> 		<br /> 		**Décrivez le bug**<br />Le bug en lui-même n'est pas gênant.<br /><br />En voulant répartir les Actuals du mois d'août, la page affiche encore des heures (pour seulement deux ressources) déjà réparties du mois de juillet.<br />=> Cf image jointe<br /> 		<br /> 		**A reproduire**<br />Charge/Répartition<br />Filtre sur métier "Mechanical Design - Traction" et Ressources "Presta xx"<br />Répartir les Actuals<br /><br /> 		**Comportement attendu**<br />Les Actuals déjà répartis des mois précédents ne sont plus affichés.<br /><br /><br />**Liste des pièces jointes:**<br /><a href="https://awa.tnext.loc/api/public/240927_AWA_Actuals-641235.JPG" target="_blank" >https://awa.tnext.loc/api/public/240927_AWA_Actuals-641235.JPG</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : oui<br />Contournement possible : oui<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 3<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :François TERRIEN fterrien 238244 Manager<br /> **Détails du serveur**<br />Version DB: 5.0.2; Version Soft: v1.0.9; Version Back: v1.0.9<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 Edg/128.0.0.0<br />Adresse du PC :10.24.101.181<br />

**Comment by lokkotara** [comment]
Bonjour,

Nous vous remercions pour votre retour.

Le comportement que vous décrivez est effectivement attendu. Les pointages qui n'ont pas été entièrement répartis, ainsi que ceux qui ont été répartis dans le mois en cours, doivent rester visibles dans la liste des actuals. Cela inclut les deux lignes apparaissant en juillet dans votre capture d'écran. Ce fonctionnement permet d'éviter que les pointages ne disparaissent immédiatement après répartition, ce qui pourrait nuire à l'expérience utilisateur.

Nous espérons avoir répondu à votre question et fermons donc ce ticket. N'hésitez pas à nous recontacter pour toute autre question ou clarification.

Cordialement,
