### ISSUE TITLE
id:200959906 Bug affichage décimal dans vue activity-management en vue matricielle

### ISSUE THREAD

**Issue by gboule65** [Alstom-WebFdl/ticket-service#498]
<br /> 		**Affichage concerné**<br /> 		Gestion du budget des activités (en heures), projet "ESU TRAM AL ULA", méthier "Thermal design"<br /> 		<br /> 		**Décrivez le bug**<br /> 		Sur une entrée contenant des sous-tâches, l'affichage du total n'est pas arrondi à un digit<br /> 		<br /> 		**A reproduire**<br /> 		Les étapes permettant de reproduire le comportement indésirable :<br /> 		1. Sur l'affichage 'Bestion du budget'<br /> 		2. Je choisis le métier sur 'Thermal design'<br /> 		3. Je choisis le projet 'ESU TRAM AL ULA'<br /> 		4. Sur le GAP1 'Design system ESU' et l'activité 'Activités Design + cycle DfQ', la valeur affichée est 214.60000000000002<br /><br /> 		**Comportement attendu**<br /> 		Nombre décimaux arrondis à 0,1<br /><br />**Liste des pièces jointes:**<br /><a href="https://awa.tnext.loc/api/public/Bug%20affichage%20d%C3%A9cimal%20vue%20Gerstion%20du%20budget-554965.png" target="_blank" >https://awa.tnext.loc/api/public/Bug%20affichage%20d%C3%A9cimal%20vue%20Gerstion%20du%20budget-554965.png</a><br /><br /><br /><br />@Alstom-WebFdl/method-tools<br />**Criticité du ticket**<br />Problème multi-utilisateurs : non<br />Contournement possible : non<br />Criticité calculée (1 à 4, 4 étant le plus critique) : 2<br />**Détails de l'utilisateur**<br />Nom, Prénom, login, id Alps, Rôle :Daniel DUPUY e_ddupuy 200959906 Workload manager<br /> **Détails du serveur**<br />Version DB: 5.0.2; Version Soft: v1.0.11; Version Back: v1.0.12<br /><br />**Détails du PC/Browser:**<br />HTTP_USER_AGENT :Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0<br />Adresse du PC :10.22.112.66<br />

**Comment by lokkotara** [comment]
Ne sera plus d'actualité à partir de la V2 car il n'y a plus la fenêtre additionnelle pour les sous-tâches. Je clos donc ce ticket
