### ISSUE TITLE
Bug de la requête POST lors de l'export

### ISSUE THREAD

**Issue by lokkotara** [Alstom-WebFdl/ticket-service#90]
Sur l'affichage workload-overview, lorsque je clique sur le bouton export, cela lance la création d'un fichier.xlsx . Cependant il contient seulement le message suivant :

![Image](https://github.com/Alstom-WebFdl/ticket-service/assets/9353050/d99a1bb8-3e69-4007-97ac-31d549e5384c)

**Comment by gboule65** [comment]
Il manque une lib php qui se nomme "intl" : apt-get install php7-intl
